#!/usr/bin/env python3
"""
records.py -- a catalog record (remake/catalog/<ID>.json, remake/research/CATALOG_SPEC.md) for every structure a
generated town lays out, so every building is its own design (the user, 2026-10-06: "The buildings will all be
unique, generated by the rules we just defined").

The rules, and where they come from:
  * what a house looks like in each era band: the tokenized Great Lakes corpus (research/buildings/regions/
    great_lakes/tokens, 632 buildings; token_stats.txt) -- form, storeys, walls, porch, roof, windows, chimneys,
    foundation, colours, condition -- blended with the style scholarship's band priors (02_styles.md) where the corpus
    is thin (after 1945)
  * compatibility (03_compatibility.md, Groat; the design-review criteria): a block face shares its massing and
    setback -- each face draws a dominant form and storey count that most of its houses follow, the rest vary
  * the lot (LOTS.md §5): garage by band (rear on the alley in the old grid, side or attached later), front fences
    rare and old, side and rear lines by setting (§3 table), outbuildings, yard extras by era
  * change over time (urban_layout/03): older houses gain additions, aluminium or vinyl over wood, enclosed porches;
    condition from the corpus's shares
  * names: households' surnames from the bible's lineages; businesses named for families and places; never brands
Every choice is a function of (town seed, structure id): rerunning gives the same town.

    recs = make_records(structures, seed)      structures: [{id, use, band, lot_w, lot_d, face, label, ...}]
"""
import glob
import hashlib
import json
import math
import os
import random
import sys
from collections import Counter, defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TOK = os.path.join(ROOT, "research", "buildings", "regions", "great_lakes", "tokens")
FT = 0.3048
sys.path.insert(0, os.path.join(ROOT, "tools", "bible"))


def rnd_for(seed, *key):
    h = hashlib.blake2b("|".join(map(str, (seed,) + key)).encode(), digest_size=8).digest()
    return random.Random(int.from_bytes(h, "little"))


def wpick(r, weights):
    items = [(k, w) for k, w in weights.items() if w > 0]
    tot = sum(w for _, w in items)
    x = r.random() * tot
    for k, w in items:
        x -= w
        if x <= 0:
            return k
    return items[-1][0]


# ------------------------------------------------------------------ the corpus, per band
TOKEN_BAND = {"rail": ("railroad_1860_1900", "canal_1830_1860"), "streetcar": ("streetcar_1890_1930",),
              "interwar": ("interwar_1920_1945",), "postwar": ("postwar_1945_1965",), "suburban": ("suburban_1965_1990",),
              "late": ("late_1990_2010",), "current": ("current_2010_on",)}


def corpus():
    c = defaultdict(lambda: defaultdict(Counter))
    for f in glob.glob(os.path.join(TOK, "*.json")):
        t = json.load(open(f))
        tk = t.get("tokens", [])
        if "use:house" not in tk:
            continue
        b = (t.get("place") or {}).get("band")
        for x in tk:
            fam, _, val = x.partition(":")
            c[b][fam][val] += 1
    return c


# the style scholarship's priors per band (02_styles.md §1-§5; 05 Boeing's eras; LOTS §1): form weights
PRIOR_FORM = {
    "rail": {"i_house": 3, "upright_and_wing": 3, "gable_front": 4, "italianate_cube": 2, "side_gable_cottage": 2,
             "queen_anne_irregular": 1.5, "workers_cottage": 2, "gable_front_and_wing": 2},
    "streetcar": {"gable_front": 4, "foursquare": 3, "bungalow": 3, "queen_anne_irregular": 1, "workers_cottage": 2,
                  "gable_front_and_wing": 1.5, "upright_and_wing": 1},
    "interwar": {"bungalow": 3, "foursquare": 2, "cape_cod": 2, "tudor": 2, "dutch_colonial": 1, "minimal_traditional": 1,
                 "american_small_house": 1, "two_storey_colonial": 1.5},
    "postwar": {"ranch": 4, "minimal_traditional": 3, "cape_cod": 2, "american_small_house": 2.5, "split_level": 1},
    "suburban": {"split_level": 3, "ranch": 3, "two_storey_colonial": 2.5, "raised_ranch": 1.5, "dutch_colonial": 0.6, "a_frame": 0.05},
    "late": {"two_storey_colonial": 3.5, "ranch": 2, "neo_eclectic": 2, "split_level": 0.4, "builder_contemporary": 1},
    "current": {"builder_contemporary": 3, "two_storey_colonial": 2, "ranch": 2, "neo_eclectic": 1, "modern_box": 0.6},
}
# token form -> the house generator's archetype (remake/blender/gen/house.py ARCH), and its usual storeys
ARCH = {"i_house": ("i_house", 2), "upright_and_wing": ("upright_and_wing", 2), "gable_front": ("gable_front", 2),
        "gable_front_and_wing": ("upright_and_wing", 1.5), "hall_and_parlor": ("side_gable_cottage", 1),
        "side_gable_cottage": ("side_gable_cottage", 1), "ontario_cottage": ("side_gable_cottage", 1.5),
        "workers_cottage": ("workers_cottage", 1.5), "foursquare": ("foursquare", 2), "bungalow": ("bungalow", 1.5),
        "homestead_temple": ("gable_front", 1.5), "pyramidal_cottage": ("side_gable_cottage", 1),
        "queen_anne_irregular": ("queen_anne", 2), "italianate_cube": ("italianate", 2), "cape_cod": ("cape_cod", 1.5),
        "minimal_traditional": ("minimal_traditional", 1), "ranch": ("ranch", 1), "raised_ranch": ("split_level", 1),
        "split_level": ("split_level", 1), "bi_level": ("split_level", 1), "american_small_house": ("american_small_house", 1),
        "two_storey_colonial": ("i_house", 2), "neo_eclectic": ("tudor_revival", 2), "builder_contemporary": ("gable_front", 2),
        "modern_box": ("prairie_box", 2), "a_frame": ("a_frame", 1.5), "prairie_box": ("prairie_box", 2), "shotgun": ("shotgun", 1),
        "tudor": ("tudor_revival", 1.5), "dutch_colonial": ("dutch_colonial", 2), "temple_front": ("gable_front", 2),
        "double_house": ("i_house", 2), "two_flat": ("gable_front", 2)}
WALLS = {"rail": {"clapboard": 6, "brick": 2, "drop_siding": 1}, "streetcar": {"clapboard": 6, "brick": 1.5, "wood_shingle": 1, "stucco": 0.5},
         "interwar": {"clapboard": 4, "brick": 3, "stucco": 1.5, "wood_shingle": 0.7}, "postwar": {"brick": 3, "clapboard": 2, "asbestos_shingle": 2, "aluminum": 1.5},
         "suburban": {"brick": 2.5, "aluminum": 2, "vinyl": 2, "board_and_batten": 0.8, "clapboard": 1},
         "late": {"vinyl": 5, "brick": 2, "fiber_cement": 1}, "current": {"fiber_cement": 3, "vinyl": 3, "board_and_batten": 1.5, "brick": 1}}
# a wall token -> house.py's walls value
WALL_GEN = {"clapboard": "clapboard", "drop_siding": "clapboard", "brick": "brick", "wood_shingle": "shingle", "stucco": "stucco",
            "asbestos_shingle": "shingle", "aluminum": "clapboard", "vinyl": "vinyl", "fiber_cement": "clapboard",
            "board_and_batten": "board_and_batten", "stone": "stone"}
PORCH = {"rail": {"front_full": 2, "front_partial": 3, "side": 2, "stoop": 2, "wrap": 0.8},
         "streetcar": {"front_full": 5, "front_partial": 2, "enclosed": 1.5, "wrap": 0.5, "stoop": 0.6},
         "interwar": {"front_full": 2, "front_partial": 2.5, "stoop": 3, "enclosed": 0.8},
         "postwar": {"stoop": 5, "recessed": 2, "front_partial": 1}, "suburban": {"stoop": 4, "recessed": 2, "front_partial": 1},
         "late": {"front_partial": 3, "stoop": 3, "front_full": 1}, "current": {"front_full": 2.5, "front_partial": 2, "stoop": 2}}
POSTS = {"rail": {"turned": 3, "square": 2, "columns": 1}, "streetcar": {"square": 2, "tapered_on_piers": 3, "columns": 2, "turned": 1},
         "interwar": {"tapered_on_piers": 2, "columns": 2, "square": 2}, "postwar": {"iron": 3, "square": 2},
         "suburban": {"square": 3, "iron": 1}, "late": {"columns": 3, "square": 2}, "current": {"square": 3, "columns": 1}}
GARAGE = {"rail": {"detached_1": 5, "detached_2": 1.5, "none": 3.5}, "streetcar": {"detached_1": 6, "detached_2": 1.5, "none": 2.5},
          "interwar": {"detached_1": 4, "detached_2": 2.5, "attached_1": 1, "none": 1.5}, "postwar": {"attached_1": 3.5, "carport": 1.5, "detached_1": 2, "none": 1},
          "suburban": {"attached_2": 6, "attached_1": 2, "carport": 0.5}, "late": {"attached_2": 8, "attached_1": 1},
          "current": {"attached_2": 8, "attached_1": 1}}
WINDOW = {"rail": {"2over2": 4, "6over6": 2, "1over1": 2}, "streetcar": {"1over1": 4, "3over1_craftsman": 3, "2over2": 1},
          "interwar": {"6over6": 3, "1over1": 2, "3over1_craftsman": 2, "casement": 1}, "postwar": {"1over1": 3, "picture": 3, "sliding": 1},
          "suburban": {"1over1": 2, "picture": 3, "sliding": 2}, "late": {"1over1": 4, "picture": 1}, "current": {"1over1": 3, "picture": 2, "casement": 1}}
# body / trim colours by wall material (the corpus's colour tokens as hues, jittered per house)
BODY = {"clapboard": ["#f2efe6", "#e8e2d4", "#d9cbb0", "#c9b48a", "#9fb3a0", "#8fa6b8", "#b8574a", "#e6d18f", "#7d8f7a", "#c6c0b4", "#f0e6c8", "#5d6b78"],
        "shingle": ["#8a7a68", "#a59a88", "#6d6458", "#c4b9a4", "#7a8a8a"],
        "brick": ["#8c4636", "#9a5a42", "#7e3d2e", "#b06a4c", "#a58a6a", "#c9b08a"],
        "stucco": ["#e9e1cf", "#d8c9a8", "#c9b79a", "#f0ead8"], "vinyl": ["#ece9e0", "#d8d6cc", "#c8c2b0", "#b9c2c4", "#d6cba8", "#a8b4a0", "#9aa5ab"],
        "board_and_batten": ["#f0eee8", "#3e4448", "#7a3b30", "#c8c2b0"], "stone": ["#a8a090", "#bdb4a0"]}
TRIM = ["#f4f1e8", "#f2efe6", "#ffffff", "#e9e2d2", "#3a3f44", "#2e3a4a", "#5a3a28", "#e8e0c8"]
ACCENT = ["#2e3a4a", "#4a5a48", "#7a2e28", "#3a2a1e", "#1f2a33", "#5b6b3a", "#6a4a2a", "#2b4f6b"]
ROOFC = ["#555350", "#4e5155", "#5a4a40", "#3e3e3c", "#6a5e52", "#4a4a48", "#5a5a58", "#2f3133"]


def jitter(hexc, r, amt=10):
    c = [int(hexc[i:i + 2], 16) for i in (1, 3, 5)]
    c = [max(0, min(255, v + r.randint(-amt, amt))) for v in c]
    return "#%02x%02x%02x" % tuple(c)


class Rules:
    def __init__(self, seed):
        self.seed = seed
        self.c = corpus()
        self.face = {}
        import canon_lineages as LI
        self.surnames = [l["surname"] for l in LI.LINEAGES if " " not in l["surname"]] or ["Smith"]

    def form_weights(self, band):
        """The band's prior blended with the corpus's measured forms (weight by how many samples there are)."""
        w = dict(PRIOR_FORM[band])
        meas = Counter()
        for tb in TOKEN_BAND[band]:
            meas.update(self.c.get(tb, {}).get("form", Counter()))
        n = sum(meas.values())
        if n:
            k = min(0.6, n / 120.0)                         # (trust the corpus up to 60 % where it has 70+ houses)
            tot = sum(w.values())
            w = {f: (1 - k) * v / tot for f, v in w.items()}
            for f, v in meas.items():
                if f in ARCH:
                    w[f] = w.get(f, 0.0) + k * v / n
        return w

    def condition(self, band, r):
        old = band in ("rail", "streetcar")
        return wpick(r, {"kept": 72, "worn": 20 if old else 12, "shabby": 7 if old else 3, "new": 0 if old else 3})

    def face_theme(self, face, band, r):
        """03_compatibility: a block face built by one builder in one decade shares a form and a storey count."""
        if face not in self.face:
            fr = rnd_for(self.seed, "face", face)
            f = wpick(fr, self.form_weights(band))
            self.face[face] = (f, fr.uniform(0.45, 0.75) if band in ("postwar", "suburban", "late", "current") else fr.uniform(0.3, 0.55))
        return self.face[face]

    def house(self, s, r):
        band = s["band"]
        f0, share = self.face_theme(s.get("face") or s["id"], band, r)
        form = f0 if r.random() < share else wpick(r, self.form_weights(band))
        use = s["use"]
        if use == "two_flat":
            form = "two_flat"
        elif use == "duplex":
            form = r.choice(["double_house", "gable_front", "foursquare"]) if band in ("rail", "streetcar") else "ranch"
        arch, st = ARCH.get(form, ("gable_front", 2))
        if form in ("bungalow", "cape_cod", "workers_cottage") and r.random() < 0.3:
            st = 1.5 if st != 1.5 else 1
        if form == "gable_front" and band in ("streetcar",) and r.random() < 0.35:
            st = 1.5
        lot_w = s["lot_w"]
        y0, y1 = BANDS_YEARS[band]
        year = r.randint(y0, y1)
        wall = wpick(r, WALLS[band])
        walls = WALL_GEN[wall]
        porch = wpick(r, PORCH[band])
        if form in ("ranch", "split_level", "minimal_traditional", "american_small_house") and porch in ("front_full", "wrap"):
            porch = "front_partial"
        garage = wpick(r, GARAGE[band])
        if s.get("alley") and garage.startswith("attached"):
            garage = "detached_1"
        side_gap = {"rail": 1.0, "streetcar": 0.9, "interwar": 1.5, "postwar": 2.4, "suburban": 4.0, "late": 2.6, "current": 2.2}[band]
        gar_w = {"attached_1": 3.6, "attached_2": 6.0, "carport": 3.2}.get(garage, 0.0)
        max_w = max(6.0, lot_w - 2 * side_gap - (gar_w + 0.8 if gar_w else 0.0))
        base_w = {"ranch": 52, "split_level": 44, "american_small_house": 30, "minimal_traditional": 34, "i_house": 38, "foursquare": 28,
                  "bungalow": 26, "cape_cod": 32, "workers_cottage": 20, "gable_front": 24, "upright_and_wing": 26, "queen_anne": 32,
                  "italianate": 32, "tudor_revival": 34, "dutch_colonial": 34, "prairie_box": 34, "side_gable_cottage": 30,
                  "a_frame": 26, "shotgun": 14}.get(arch, 28)
        w_ft = min(base_w * r.uniform(0.85, 1.12), max_w / FT)
        d_ft = {"ranch": 28, "split_level": 30, "gable_front": 36, "workers_cottage": 30, "foursquare": 30, "bungalow": 40,
                "shotgun": 50, "i_house": 22}.get(arch, 30) * r.uniform(0.88, 1.15)
        roof_type = {"foursquare": "hip", "prairie_box": "hip", "italianate": "hip", "queen_anne": "cross_gable",
                     "dutch_colonial": "gambrel", "tudor_revival": "cross_gable"}.get(arch, "gable")
        if arch in ("ranch", "split_level") and r.random() < 0.55:
            roof_type = "hip"
        if arch == "upright_and_wing" or (arch == "gable_front" and r.random() < 0.2):
            roof_type = "cross_gable" if arch == "upright_and_wing" else roof_type
        pitch = {"rail": (35, 48), "streetcar": (32, 45), "interwar": (28, 45), "postwar": (18, 30), "suburban": (18, 28),
                 "late": (25, 38), "current": (25, 40)}[band]
        rmat = "asphalt_shingle" if r.random() < 0.92 else ("metal" if band in ("current", "rail") else "slate")
        dormers = []
        if st == 1.5 and r.random() < 0.6:
            dormers = [{"type": r.choice(["gable", "shed", "gable"]), "side": "front"}] * r.choice([1, 2, 2])
        chim = {"rail": ["center"], "streetcar": ["center"], "interwar": [r.choice(["left_end", "right_end", "exterior_left"])],
                "postwar": [r.choice(["center", "exterior_right", "rear"])], "suburban": [r.choice(["exterior_left", "rear"])],
                "late": [] if r.random() < 0.6 else ["exterior_left"], "current": []}[band]
        body = jitter(r.choice(BODY.get(walls, BODY["clapboard"])), r, 9)
        fence = "none"
        if band in ("rail", "streetcar") and r.random() < 0.08:
            fence = r.choice(["picket", "iron", "picket", "hedge"])
        elif band in ("postwar",) and r.random() < 0.06:
            fence = "chainlink"
        # side and rear lines (LOTS §3): open fronts; the old grid's backs chain-link or open, postwar backs chain-link,
        # suburban backs tree belts, new subdivisions' backs privacy fences
        side = wpick(r, {"rail": {"none": 5, "chainlink": 2, "hedge": 1, "picket": 0.5}, "streetcar": {"none": 5, "chainlink": 2.5, "hedge": 0.8},
                         "interwar": {"none": 4, "hedge": 2, "chainlink": 1.5}, "postwar": {"chainlink": 4, "none": 3, "hedge": 1},
                         "suburban": {"none": 4, "hedge": 2, "privacy": 1}, "late": {"privacy": 4, "none": 3},
                         "current": {"privacy": 3, "none": 4}}[band])
        rear = wpick(r, {"rail": {"chainlink": 3, "none": 3}, "streetcar": {"chainlink": 3, "none": 3}, "interwar": {"hedge": 2, "chainlink": 2, "none": 2},
                         "postwar": {"chainlink": 5, "hedge": 1.5}, "suburban": {"tree_line": 4, "hedge": 2}, "late": {"privacy": 6, "tree_line": 1},
                         "current": {"privacy": 6, "none": 1}}[band])
        extras = [e for e, p in (("garden", 0.3 if band in ("rail", "streetcar", "interwar") else 0.12), ("shed", 0.35),
                                 ("clothesline", 0.25 if band in ("rail", "streetcar", "postwar") else 0.05), ("swing_set", 0.2)) if r.random() < p]
        cond = self.condition(band, r)
        tr = {"archetype": arch, "storeys": st, "main_w_ft": round(w_ft), "main_d_ft": round(d_ft),
              "roof": {"type": roof_type, "pitch_deg": r.randint(*pitch), "material": rmat}, "dormers": dormers,
              "porch": {"type": porch, "posts": wpick(r, POSTS[band]), "rail": r.choice(["spindle", "none", "solid"]) if porch != "stoop" else "none"},
              "walls": walls, "foundation": {"rail": "cut_stone", "streetcar": r.choice(["brick", "concrete_block"]), "interwar": "concrete_block",
                                             "postwar": "poured_concrete", "suburban": "poured_concrete", "late": "poured_concrete",
                                             "current": "poured_concrete"}[band],
              "colors": {"body": body, "trim": r.choice(TRIM), "accent": r.choice(ACCENT), "roof": r.choice(ROOFC)},
              "windows": {"type": wpick(r, WINDOW[band]), "shutters": r.random() < (0.35 if band in ("interwar", "suburban", "late") else 0.15)},
              "chimneys": chim, "garage": garage,
              "yard": {"fence": fence, "side": side, "rear": rear, "extras": extras},
              "condition": cond, "year_built": year, "band": band, "form_token": form}
        if use in ("duplex", "two_flat"):
            tr["units"] = 2
            if use == "two_flat":
                tr["porch"] = {"type": "stacked", "posts": "square", "rail": "spindle"}
        if band in ("rail", "streetcar") and r.random() < 0.18:
            tr["wing"] = {"side": "rear", "w_ft": r.randint(12, 16), "d_ft": r.randint(9, 12)}       # (a later kitchen addition)
        return tr


BANDS_YEARS = {"rail": (1868, 1899), "streetcar": (1895, 1929), "interwar": (1922, 1942), "postwar": (1947, 1964),
               "suburban": (1966, 1989), "late": (1991, 2009), "current": (2011, 2024)}

# ------------------------------------------------------------------ businesses
TRADE = {"grocery": "Market", "variety_store": "Variety", "hardware": "Hardware", "drug_store": "Drug", "diner": "Diner",
         "cafe": "Cafe", "bar": "Tavern", "bank": "Savings Bank", "barber": "Barber Shop", "beauty_salon": "Beauty Shop",
         "clothing": "Clothiers", "shoe_store": "Shoes", "jeweler": "Jewelers", "furniture": "Furniture", "bakery": "Bakery",
         "butcher": "Meats", "feed_seed": "Feed & Seed", "auto_parts": "Auto Parts", "insurance_office": "Insurance",
         "law_office": "Law Office", "doctor_office": "Family Medicine", "dentist": "Dental", "newspaper": "Courier",
         "movie_theater": "Theatre", "bookstore": "Books", "laundromat": "Laundry", "florist": "Flowers", "pizza": "Pizza",
         "sporting_goods": "Sporting Goods", "thrift_store": "Thrift", "gas_station": "Service", "auto_repair": "Garage",
         "funeral_home": "Funeral Home", "music_store": "Music", "print_shop": "Printing", "real_estate": "Realty",
         "pharmacy": "Pharmacy", "pet": "Pet Supply", "dollar": "Dollar Store", "nail_salon": "Nails", "tax_office": "Tax Service",
         "discount": "Discount", "restaurant": "Restaurant", "ice_cream": "Dairy Bar", "art_gallery": "Gallery", "brewpub": "Brewing",
         "appliance_repair": "Appliance", "dry_goods": "Dry Goods", "shoe_repair": "Shoe Repair", "pool_hall": "Billiards",
         "tavern_hotel": "Hotel", "vacant": ""}
DOWNTOWN_MIX = {"grocery": 1, "variety_store": 2, "hardware": 2, "drug_store": 2, "diner": 3, "cafe": 3, "bar": 3, "bank": 2,
                "barber": 2, "beauty_salon": 3, "clothing": 2, "shoe_store": 1, "jeweler": 1, "furniture": 1, "bakery": 2,
                "insurance_office": 2, "law_office": 2, "doctor_office": 1, "dentist": 1, "newspaper": 1, "movie_theater": 0.6,
                "bookstore": 1, "florist": 1, "pizza": 2, "sporting_goods": 1, "thrift_store": 1, "music_store": 0.6,
                "print_shop": 1, "real_estate": 1.5, "pharmacy": 1, "tax_office": 1, "art_gallery": 0.6, "brewpub": 0.8,
                "appliance_repair": 0.6, "shoe_repair": 0.5, "pool_hall": 0.6}      # (no vacancies: every building has a purpose, 2026-10-07)
TENANT_TYPE = {"supermarket": "grocery", "drugstore": "pharmacy", "hardware_store": "hardware", "discount_variety": "discount",
               "discount": "discount", "home_furnishings": "furniture", "pet_supply": "pet", "bank_branch": "bank",
               "hair_salon": "beauty_salon", "dentist": "dentist", "takeout_pizza": "pizza", "video_rental": "video_rental",
               "dry_cleaner": "laundromat", "nail_salon": "nail_salon", "fitness_studio": "sporting_goods", "optician": "doctor_office",
               "mail_and_ship": "print_shop", "family_restaurant": "diner", "liquor_party_store": "variety_store",
               "convenience_store": "grocery", "takeout_chinese": "restaurant", "tax_preparer": "tax_office", "phone_store": "variety_store",
               "laundromat": "laundromat", "insurance_agent": "insurance_office", "barber": "barber", "dollar_store": "dollar",
               "cards_and_gifts": "variety_store", "fabric_store": "dry_goods", "mobile_phone": "variety_store", "chinese_buffet": "restaurant",
               "rent_to_own": "furniture", "tanning_salon": "beauty_salon", "fast_food_drive_thru": "diner", "bank_drive_thru": "bank",
               "coffee_drive_thru": "cafe", "sit_down_chain_restaurant": "restaurant", "sporting_goods": "sporting_goods",
               "electronics": "variety_store", "shoe_store": "shoe_store", "clothing": "clothing", "craft_store": "variety_store",
               "auto_parts": "auto_parts", "farm_store": "feed_seed", "gas_station": "gas_station", "gas_convenience": "gas_station"}


def business(r, typ, surnames, town, place_words):
    if typ == "vacant":
        return {"business": "", "type": "vacant", "sign": "FOR LEASE"}
    word = TRADE.get(typ, typ.replace("_", " ").title())
    style = r.random()
    if style < 0.55:
        name = f"{r.choice(surnames)} {word}" if word else r.choice(surnames)
    elif style < 0.8:
        name = f"{r.choice(place_words)} {word}"
    else:
        name = f"{r.choice(surnames)} & {r.choice(surnames)} {word}"
    return {"business": name, "type": typ, "sign": name.upper(), "sign_style": r.choice(["projecting", "flat_board", "flat_board", "awning_lettering"]),
            "awning": r.random() < 0.45}


# ------------------------------------------------------------------ the record for one structure
CIVIC = {"city_hall": ("civic", "city_hall", 2, "romanesque", 1898), "police": ("civic", "police", 1, "modern", 1962),
         "fire_station": ("civic", "fire_station", 2, "commercial_style", 1915), "post_office": ("civic", "post_office", 1, "classical_revival", 1936),
         "library": ("civic", "library", 1, "classical_revival", 1908), "depot": ("civic", "depot", 1, "vernacular", 1884),
         "hospital": ("civic", "hospital", 3, "modern", 1958), "hospital_wing": ("civic", "hospital", 2, "modern", 1994),
         "clinic": ("civic", "clinic", 2, "modern", 2004), "elementary": ("school", "elementary", 1, "modern", 1956),
         "high_school": ("school", "high_school", 2, "modern", 1964), "high_school_wing": ("school", "high_school", 2, "modern", 1998),
         "fieldhouse": ("school", "gym", 1, "modern", 1971)}


def make_record(s, rules, town, seed):
    r = rnd_for(seed, s["id"])
    use = s["use"]
    lot = {"w": round(s["lot_w"], 1), "d": round(s["lot_d"], 1)}
    rec = {"id": s["id"], "settlement": town, "generated": "tools/settlegen (Calder, 2026-10-06)", "lot": lot}
    names = {}
    if use in ("house", "duplex", "two_flat"):
        rec["kind"] = "house"
        rec["traits"] = rules.house(s, r)
        names = {"family": r.choice(rules.surnames), "house_number": s.get("number")}
    elif use == "townhouse":
        rec["kind"] = "townhouse"
        band = s["band"]
        walls = wpick(r, {"vinyl": 3, "fiber_cement": 2, "brick": 1.5})
        rec["traits"] = {"units": int(s.get("units", 6)), "unit_w_ft": r.choice([20, 22, 22, 24]), "depth_ft": r.choice([34, 36, 38]),
                         "walls": WALL_GEN[walls], "colors": {"body": jitter(r.choice(BODY[WALL_GEN[walls]]), r), "trim": r.choice(TRIM),
                                                             "accent": r.choice(ACCENT), "roof": r.choice(ROOFC)},
                         "roof": {"pitch_deg": r.randint(24, 34)}, "year_built": r.randint(*BANDS_YEARS[band]), "condition": "kept"}
        names = {"name": s.get("label") or ""}
    elif use == "apartment":
        rec["kind"] = "condo"
        rec["traits"] = {"storeys": r.choice([2, 2, 3]), "form": "slab", "units": int(s.get("units", 12)),
                         "balconies": r.choice(["none", "front"]), "ground_floor": "apartments",
                         "walls": r.choice(["brick", "vinyl", "brick"]), "colors": {"body": jitter(r.choice(BODY["brick"] + BODY["vinyl"]), r)},
                         "year_built": r.randint(1968, 2016), "condition": "kept"}
        names = {"name": s.get("label") or ""}
    elif use == "store":
        rec["kind"] = "store"
        storeys = wpick(r, {1: 1.5, 2: 6, 3: 1.5})
        sf = [business(r, wpick(r, DOWNTOWN_MIX), rules.surnames, town, [town, "Main Street", "Infirmary", "Ring Line", "Southland", "Depot"])]
        rec["traits"] = {"storeys": storeys, "facade": wpick(r, {"brick": 8, "frame_false_front": 0.6, "cast_iron_front": 0.6}),
                         "cornice": wpick(r, {"bracketed_metal": 3, "corbelled_brick": 3, "parapet_flat": 2, "parapet_stepped": 1}),
                         "upper_use": ("apartments" if r.random() < 0.6 else "offices") if storeys > 1 else "none",
                         "storefronts": sf, "condition": wpick(r, {"kept": 6, "worn": 3, "shabby": 1}), "year_built": r.randint(1872, 1924),
                         "colors": {"body": jitter(r.choice(BODY["brick"]), r)}}
    elif use in ("gas_station", "fast_food", "bank", "auto_repair", "funeral_home", "diner", "farm_supply", "car_wash", "insurance",
                 "auto_parts", "tavern"):
        typ = {"fast_food": "diner", "farm_supply": "feed_seed", "car_wash": "auto_repair", "insurance": "insurance_office",
               "tavern": "bar"}.get(use, use)
        b_ = business(r, typ, rules.surnames, town, [town, "Ring Line", "Southland", "Westgate", "Highway"])
        if use == "gas_station":
            rec["kind"] = "strip"
            rec["traits"] = {"stores": [b_], "era": r.randint(1985, 2015)}
        else:
            rec["kind"] = "store"
            rec["traits"] = {"storeys": 1, "facade": "brick", "cornice": "parapet_flat", "upper_use": "none", "storefronts": [b_],
                             "condition": "kept", "year_built": r.randint(1955, 2008), "colors": {"body": jitter(r.choice(BODY["brick"]), r)}}
    elif use == "motel":
        rec["kind"] = "motel"
        rec["traits"] = {"rooms": 14, "storeys": 1, "year_built": 1958}
        names = {"name": f"{town} Motel", "sign": f"{town.upper()} MOTEL"}
    elif use == "works":
        rec["kind"] = "industrial"
        rec["traits"] = {"use": r.choice(["machine_shop", "lumber_yard", "warehouse", "feed_mill", "farm_equipment", "creamery"]),
                         "storeys": r.choice([1, 1, 2]), "walls": r.choice(["brick", "metal", "block"]), "year_built": r.randint(1890, 1975),
                         "components": [], "condition": wpick(r, {"kept": 5, "worn": 4, "boarded": 1})}
    elif use == "elevator":
        rec["kind"] = "industrial"
        rec["traits"] = {"use": "grain_elevator", "components": ["concrete bin", "headhouse"], "walls": "concrete", "year_built": 1924}
        names = {"name": "Southland Co-op Elevator", "sign": "SOUTHLAND CO-OP"}
    elif use == "water_tower":
        rec["kind"] = "tower"
        rec["traits"] = {"type": "multi_leg_tank", "year_built": 1938}
        names = {"name": f"{town} water tower", "sign": town.upper()}
    elif use == "church":
        rec["kind"] = "church"
        rec["traits"] = {"style": wpick(r, {"gothic_revival": 4, "romanesque": 2, "colonial_revival": 1.5, "modern": 1}),
                         "year_built": r.randint(1880, 1928), "walls": r.choice(["brick", "stone", "clapboard"]),
                         "plan": r.choice(["rect", "rect", "l_shape"])}
    elif use in CIVIC:
        kind, cu, st, style, yr = CIVIC[use]
        rec["kind"] = kind
        rec["traits"] = {"use": cu, "storeys": st, "style": style, "year_built": yr, "walls": "brick",
                         "colors": {"body": jitter(r.choice(BODY["brick"]), r, 6)}}
        names = {"name": s.get("label") or cu.replace("_", " ").title()}
    elif use in ("bigbox", "strip_row", "pad"):
        rec["kind"] = {"bigbox": "bigbox", "strip_row": "strip", "pad": "strip"}[use]
        rec["traits"] = {"stores": s["stores"], "era": s.get("era", 1986)}
        names = {"name": s.get("centre"), "sign": (s.get("centre") or "").upper()}
    else:
        raise ValueError(f"no record rule for use {use}")
    rec["names"] = names
    rec["brief"] = brief(rec, s)
    return rec


def brief(rec, s):
    tr = rec.get("traits", {})
    k = rec["kind"]
    if k == "house":
        return (f"{s['band']} band {tr.get('form_token', tr.get('archetype'))}: {tr.get('storeys')} storeys, {tr.get('walls')} walls, "
                f"{tr['porch']['type']} porch, garage {tr.get('garage')} (generated from the Great Lakes tokens).")
    return f"{k} ({s['use']}) generated for {rec['settlement']}."


def make_records(structs, seed, town):
    rules = Rules(seed)
    return [make_record(s, rules, town, seed) for s in structs]
