"""Columbia game bible: the world -- the ship, the voyage, the calendar, the land, the systems, the
institutions, and the settlements at full scale (250,000 people). Canon data; make_bible.py
validates it and writes godot_project/remake/bible/world.json and settlements.json.

Conventions used throughout the bible:
  years are AD (int) with vy = AD - 2252 (Voyage Year; VY 0 = launch, 21 April 2252);
  the present is VY 500 (2752); the game opens in late May 2752;
  ids are lower_snake; token fields hold enumerated strings (documented in schema.json);
  weights are relative (the engine normalises).
"""

LAUNCH_AD = 2252
PRESENT_AD = 2752
PRESENT_VY = PRESENT_AD - LAUNCH_AD

WORLD = {
    "ship": {
        "name": "Columbia", "formal_name": "Continental Habitat Vessel Columbia", "registry": "CHV-1",
        "builder": "North American Interstellar Compact (NAIC): the US, Canada and Mexico, the Great Lakes states and provinces, and a consortium of companies; European Space Agency engineers designed the drive and the rotation bearings",
        "built": [2214, 2251], "built_where": "high lunar orbit (Earth-Moon L2 yard), inside a metal-rich near-Earth asteroid (the Rock) towed there and hollowed out to take it; lunar material for the rest",
        "form": "a single rotating cylinder with end caps, turning inside the Rock on its bearings; land on the inner surface; the Spindle (a fixed central cylinder) along the axis, the Sunline on its skin",
        "rock": "the Rock: about 7.6 km across and 9.4 km long, 200-500 m of rock round the cavity; it does not turn; shield, quarry and mount for the Drive and the Port (bible industry: the_rock)",
        "spindle": "the Spindle: the central cylinder, 200 m across (radius 100 m), from cap to cap; it does not turn; the great factories inside, fed with ore through the end-cap hubs; closed to people since the Second Lockdown (VY 178) (bible industry: the_spindle)",
        "interior_radius_m": 3000, "interior_length_m": 8000, "circumference_m": 18850,
        "rotation_period_s": 110, "rotation_rpm": 0.546, "floor_gravity_g": 1.0,
        "gravity_rule": "gravity falls with height toward the axis (0 g at the axis); hills feel lighter at the top; thrown balls curve spinward/antispinward (Coriolis)",
        "floor_area_km2": 150.8, "land_km2": 113.1, "water_km2": 37.7,
        "sky": "the far side of the world is 6 km overhead, seen through haze by day; the Sunline hides it at noon",
        "sunline": "a light and heat source strung along the axis (the Sunline); it brightens at dawn and dims at dusk on a 24-hour cycle; its colour and warmth follow the seasons",
        "ends": {"north": "the bow cap: the North Sea against a cliff wall; the Port at the axis above it (closed to people since VY 92, the First Lockdown)",
                 "south": "the stern cap: the South Sea against a cliff wall; the Drive and the main reactors behind it (closed since VY 92)"},
        "undercroft": "three decks between the floor and the hull: water stores, air plants, hydroponic and vat farms, recycling, fabricators, power conduits, the tenders' galleries and the old archives. Its outer galleries closed to people since VY 178, the whole of it since VY 271 (the Third Lockdown), except the Chutes (distribution depots), the Drops and the Return halls",
        "hull": "about 12 m of regolith and water shielding outside the Undercroft; then the bearing gap; then the Rock",
        "mass_t": 48000000, "rock_mass_t": 230000000000,
        "propulsion": "fusion drive at the stern: boost VY 0-31, coast VY 31-1469, brake VY 1469-1500",
        "cruise_speed_kms": 869, "cruise_speed_c": 0.0029,
    },
    "voyage": {
        "from": "Earth (launched from the L2 yard)", "launch": "2252-04-21", "launch_vy": 0,
        "to": "Hesper, the second planet of Alpha Centauri A (Rigil Kentaurus)", "distance_ly": 4.34,
        "duration_years": 1500, "arrival_ad": 3752, "arrival_vy": 1500,
        "destination_facts": {"star": "Alpha Centauri A: G2V, 1.51 x the Sun's light; companion B (K1V) and far Proxima",
                              "planet": "Hesper: 0.92 Earth masses, 1.23 AU from A, a 1.6-Earth-year orbit, oceans and two continents, oxygen detected in 2181 (the Hesperus array); unconfirmed life",
                              "named": "by the Compact in 2198 for the evening star (Hesperus)"},
        "phases": [{"id": "boost", "vy": [0, 31]}, {"id": "coast", "vy": [31, 1469]}, {"id": "brake", "vy": [1469, 1500]},
                   {"id": "arrival", "vy": [1500, 1523]}, {"id": "settlement", "vy": [1523, 3000]}],
        "earth_distance_ly_at_present": 1.45, "message_lag_years_at_present": 1.45,
        "what_people_know_now": "most know the ship is 'going somewhere' and 'left Earth a long time ago'; few could name Hesper or Alpha Centauri; fewer know the voyage is a third done; the Steward's Launch Day 2752 Notice (VOYAGE ONE THIRD COMPLETE) is the talk of the spring",
    },
    "steward": {
        "name": "the Steward", "formal": "Habitat Autonomy System (HAS), node designation STEWARD",
        "does": ["air", "water", "power", "the Sunline and the weather", "the seasons", "Undercroft farming (vats and hydroponics)", "recycling",
                 "repairs by tenders (maintenance machines)", "fabrication of goods stock", "medical supplies", "the Chutes (distribution)", "the public boards",
                 "mining the Rock", "the Spindle's factories", "the Drops (raw materials and tools for people)", "the boards (vehicle platforms) and the Thirty-Two (processors)"],
        "tenders": "small maintenance machines that work mostly at night; people leave them be (it's bad luck to block one)",
        "speaks": "almost never: brief lines on the public boards (the Notices), one with each lockdown. It stopped speaking to people at the Fourth Lockdown (the Lockout, VY 350, after the Lantern); before VY 500 its last Notice was THE FLOOR IS SET. NOTHING MORE WILL BE TAKEN",
        "limits": "since the Fourth Lockdown it makes for people only what the Floor allows: materials, tools, boards, the Thirty-Two (32-bit processors of early-2000s power) and few screens: enough to live well, never enough to build a mind that could challenge it or to harm the ship (bible industry: TECH_LIMITS)",
        "duty": "the mission and the lives aboard. It is bound to prevent death, and every lockdown costs lives, so it locks down only as a last resort, when people's capacity for harm threatens the ship itself; never as punishment. It spaces them a generation or more apart, because two shocks in one lifetime would break the people",
        "lockdowns": [
            {"n": 1, "vy": 92, "event": "first_lockdown", "after": "port_incident", "what": "the Port and the Drive closed to people", "kind": "confinement"},
            {"n": 2, "vy": 178, "event": "second_lockdown", "after": "the_window", "what": "the hull galleries, the end-cap hubs and the Spindle closed: people confined to the habitat and the Undercroft's inner decks", "kind": "confinement"},
            {"n": 3, "vy": 271, "event": "third_lockdown", "after": "stern_breach", "what": "the Undercroft sealed; the Regression: goods back to the late 21st century (about 3,200 deaths in the decade after)", "kind": "regression"},
            {"n": 4, "vy": 350, "event": "the_lockout", "after": "the_lantern", "what": "the Steward falls silent and sets the Floor (the Thirty-Two): a level people can hold for the rest of the voyage, so no further regression is needed; phased over ten years", "kind": "floor"},
        ],
        "people_think_of_lockdowns": ["'the Steward locked the door because we were naughty' (children; wrong: none was a punishment)", "'it protects the ship from us' (the College)", "'each one is a generation's burden' (Waymakers)", "'it's waiting for us to grow up' (the Wardens' Library circle)"],
        "people_think": ["it's just the station, like weather", "a machine the founders left", "God's hand (some Waymakers)", "someone's running it from the Port (a rumour)", "it listens (children's lore)"],
    },
    "calendar": {
        "reckoning": "VY (Voyage Year) counted from launch; official since the VY 60 Charter revision; AD kept by the churches and by old families ('the year of Our Lord 2752')",
        "months": "the Gregorian months and weeks, kept from launch",
        "day": "24 hours by the Sunline: full light 06:00-18:00, dawn and dusk an hour or more",
        "seasons": {"spring": "Mar-May: warming, rain", "summer": "Jun-Aug: warm, long light", "autumn": "Sep-Nov: cooling, harvest, colour",
                    "winter": "Dec-Feb: cool, short light, frost some nights; no snow since VY 212 (the Last Snow)"},
        "present_date": "2752-05-24 (a Wednesday, VY 500); the game opens here",
    },
    "geography": {
        "directions": {"north": "toward the bow (the North Sea); the way the ship travels ('north is where we're going')",
                       "south": "toward the stern (the South Sea)", "spinward": "the way the land turns (the direction of rotation)",
                       "antispinward": "against it", "up": "toward the Sunline", "overhead / the Far Side": "the land across the axis, 6 km up"},
        "regions": [{"id": "north_shore", "name": "the North Shore", "what": "the coast of the North Sea: harbours, beaches, headlands"},
                    {"id": "northland", "name": "the Northland", "what": "farms and towns between the North Shore and the Kettle"},
                    {"id": "kettle_valley", "name": "the Kettle Valley", "what": "the Kettle River and Lake Tamsin, round the middle of the world"},
                    {"id": "southland", "name": "the Southland", "what": "farms and towns between the Kettle and the South Shore"},
                    {"id": "south_shore", "name": "the South Shore", "what": "the coast of the South Sea: resort cities and cannery towns"}],
        "waters": [{"id": "north_sea", "name": "the North Sea", "what": "1 km wide, round the whole bow end; cold, clear, fished"},
                   {"id": "south_sea", "name": "the South Sea", "what": "1 km wide, round the stern end; warmer, resort water"},
                   {"id": "kettle_river", "name": "the Kettle River", "what": "0.5 km wide, circling the world in a wide basin; ships, barges, the Falls at Harrow Falls"},
                   {"id": "lake_tamsin", "name": "Lake Tamsin", "what": "the widening of the Kettle: named for Tamsin Okafor-Reyes, the first child born aboard"},
                   {"id": "creeks", "names": ["Lost Creek", "Mill Creek", "Willow Run", "Tanner Creek", "Brush Creek", "Cole Creek", "Deer Creek", "Sauk Creek", "Heron Creek", "Linden Run", "Otter Run", "Fox Run", "Quarry Run", "Sedge Run", "Ash Run", "Birch Run", "Plum Run", "Cedar Run"]}],
        "roads": ["US 30 (the old road names were kept from the founders' Great Lakes)", "SR 14", "the Coast Highway", "Brannock Pike", "Carrow Pike", "Lakeshore Road", "Tamsin Road", "College Road", "Ocean Road"],
        "rail": "the Ring Line: one electric railway round the world with 146 level crossings",
        "wildlife": "birds (sparrows, robins, swallows, herons, gulls, terns, wrens, larks, starlings), fish (perch, walleye, whitefish, bass, cod and haddock in the North Sea, snapper in the South), bees, rabbits, squirrels, frogs, turtles; no deer, no predators larger than a fox (the foxes were a VY 190 mistake)",
        "livestock": "dairy cattle (small herds), pigs, chickens, sheep, goats; horses are few and prized",
    },
    "population": {
        "launch": 72000, "launch_crew": 1900, "balance": 250000, "balance_band": [245000, 255000], "balance_reached_vy": 118,
        "present_census_vy": 499, "present_census": 249612,
        "curve": [[0, 72000], [10, 81000], [25, 104000], [38, 121000], [50, 150000], [75, 205000], [100, 240000], [118, 250000],
                  [200, 250800], [262, 251900], [271, 248100], [300, 249000], [400, 250300], [461, 250100], [463, 246000], [470, 249200], [499, 249612]],
        "age_structure_2752": {"0-17": 0.20, "18-29": 0.14, "30-44": 0.19, "45-64": 0.27, "65-84": 0.18, "85+": 0.02},
        "life_expectancy_2752": 81.5, "births_per_year": 2950, "deaths_per_year": 2960,
    },
    "institutions": {
        "charter": {"name": "the Charter of Columbia", "signed": "2252-04-21, aboard, by the 72,000", "amended": [60, 96, 140, 280, 440, 488],
                    "clauses": ["the Balance (art. 3: the population shall be kept within the station's means)", "the Shares (art. 7)", "the Assembly (art. 11)",
                                "equal persons (art. 1)", "freedom of worship and speech (art. 2)", "surnames (art. 9)", "the Quiet Clause (art. 21, VY 280: no person or body shall seek to alter the course or purpose of the voyage)"]},
        "assembly": {"name": "the Assembly", "seat": "Kessler", "members": 101, "term_years": 5, "last_election_vy": 496,
                     "head": "the Moderator (chosen by the Assembly for five years)"},
        "registry": {"name": "the Registry Office", "seat": "Kessler, with a branch in every town", "keeps": ["births", "shares", "marriages", "deaths", "surnames", "the census"]},
        "shares": {"what": "every person holds one birth share at 18; a child needs two shares (usually the parents'); shares may be gifted, pooled or bequeathed, never sold (sale is a crime since VY 466)",
                   "effect": "about two children per couple; childless people often gift their share to a sibling or friend; big families are built from gifted shares",
                   "words": ["a share", "to gift a share", "share-kin (the children a gifted share made possible)", "an unspent share"]},
        "marshals": {"name": "the Marshals Service", "what": "station police and rescue; a Marshal-General in Kessler; town constables under it"},
        "courts": {"name": "the Station Court (Kessler) and town magistrates"},
        "commons_bank": {"name": "the Commons Bank", "currency": "the Columbia dollar (C$, 'the buck')", "what": "issues money; runs the Draw"},
        "draw": {"name": "the Draw", "what": "the monthly allotment: food credit, a home, air, water, power, clothing stock; nobody is homeless or hungry; money buys everything else"},
        "chutes": {"name": "the Chutes", "what": "distribution depots where the Steward's goods stock rises from the Undercroft; shops and works buy from them"},
        "drops": {"name": "the Drops", "what": "fenced yards over floor hatches where the Steward's machines leave raw materials (scrap, ingots, minerals such as sulfur and ores) and basic tools for people to work; the three Board Drops are the vehicle works' yards (bible industry: DROPS; to be detailed)"},
        "board_office": {"name": "the Board Office", "what": "the Assembly's office (VY 362) that counts the Steward's board allotments and audits the three works' yards"},
        "panel_board": {"name": "the Panel Board", "what": "the Assembly's board that rations the Steward's few LCD panels: hospitals first, cars never"},
        "return_halls": {"name": "the Return halls", "what": "where the dead are given back to the soil cycle; one per town"},
        "schools": {"what": "a school in every town; the Columbia College at Bellhaven (founded VY 150 as the Wardens' College)"},
        "wire": {"name": "the Wire", "what": "the station network: radio, the Wire screens, town papers, the Boards (public notice screens)"},
    },
    "faiths_2752": [
        {"id": "catholic", "name": "Catholic (the Columbian Rite since VY 163)", "share": 0.24, "seat": "St. Hedwig's Cathedral, Port Carrow"},
        {"id": "lakes_union", "name": "the Lakes Union Church (mainline Protestant union of VY 140)", "share": 0.14},
        {"id": "full_gospel", "name": "Full Gospel (evangelical and Pentecostal)", "share": 0.10},
        {"id": "freedom_baptist", "name": "the Freedom Baptist Convention (the Black church tradition)", "share": 0.06},
        {"id": "waymakers", "name": "the Waymakers (the voyage as pilgrimage; founded VY 455)", "share": 0.06},
        {"id": "muslim", "name": "Muslim (the Carrow Masjid and three others)", "share": 0.03},
        {"id": "latter_day", "name": "Latter-day Saints", "share": 0.02},
        {"id": "orthodox", "name": "Orthodox Christian", "share": 0.015},
        {"id": "dharmic", "name": "Hindu, Sikh and Buddhist", "share": 0.03},
        {"id": "jewish", "name": "Jewish (Temple Beth Columbia, Kessler)", "share": 0.01},
        {"id": "indigenous", "name": "Indigenous traditions (the Water Keepers' lodges)", "share": 0.015},
        {"id": "plain", "name": "the Plain churches (Amish and Mennonite descended; Tamarack and the Southland farms)", "share": 0.005},
    {"id": "none", "name": "no religion (unchurched, secular)", "share": 0.275},
    ],
    "languages_2752": [
        {"id": "columbian_english", "name": "Columbian English", "speakers": 1.0, "what": "descended from Inland Northern English (the Great Lakes) mixed with the refuge's Southern and Latino Englishes"},
        {"id": "lake_spanish", "name": "Lake Spanish", "home_speakers": 0.18, "where": "the South Shore (Playa Verde, Solana Point, Pelican Cove) and families everywhere"},
        {"id": "carrow_french", "name": "Carrow French", "home_speakers": 0.015, "where": "Port Carrow's Côte quarter; mostly songs, prayers and grandmothers"},
        {"id": "heritage_liturgical", "name": "heritage and liturgical tongues", "what": "Latin, Polish hymns, Arabic, Hebrew, Punjabi, Hindi, Vietnamese, Anishinaabemowin words: kept by faith and family, rarely spoken whole"},
    ],
    "knowledge_levels": {
        "_about": "How widely something is known in 2752 (per event: share of adults who know the gist / the detail)",
        "living": "within living memory (VY 420+): people remember it or their parents told them",
        "family": "family stories: known in the families concerned, patchy elsewhere",
        "schooled": "taught in school: names and dates, little feeling",
        "ritual": "kept by a holiday, a song or a church: known as a story, not as history",
        "place": "survives as a place name or a monument; few know why",
        "legend": "known, much distorted",
        "scholar": "known only to Bellhaven scholars and the Wardens' Library circle",
        "lost": "known to no one (the engine may reveal it)",
    },
    "memory_model": "The 'floating gap' of oral history (Vansina, Oral Tradition as History, 1985): people know their origins as legend and the last three generations (~80-100 years, Assmann's communicative memory) as lived; the middle centuries blur. Here: the founding (VY 0-40) is legend and ritual; VY 40-420 is thin (a few schooled names, place names); VY 420-500 is living memory.",
}

# ---------------------------------------------------------------------------------------------------------
# Settlements at full scale. test_town: the name in the engine's condensed test map (placement.json).
SETTLEMENTS = [
    dict(id="port_carrow", name="Port Carrow", test_town="Port Carrow", region="north_shore", pop=40000, founded_vy=0, charter_town=True,
         kind="harbour city", archetype="city", named_for="ada_carrow",
         character=["oldest harbour", "brick and cobbles", "proud", "Catholic and Polish-French old quarters", "trade", "the Mariners (spinball)"],
         economy=["harbour", "shipyard", "trade", "fishing", "tourism", "the Chute North"],
         districts=["the Wharves", "Old Town (Four Corners)", "the Côte (francophone quarter)", "Hedwig Hill (Polish quarter)", "King Street", "the Market Sheds", "Rainbow Row", "Fort Lamp"],
         heritage_lean={"polish": 2.0, "francophone": 3.0, "irish_scots": 1.5, "black_anglo": 1.2}, faith_lean={"catholic": 1.6, "muslim": 1.4},
         landmarks=["St. Hedwig's Cathedral", "the Carrow Lamp (harbour light)", "the Market Sheds", "the Charter Stone", "Carrow Masjid"],
         rivals=["solana_point"], allies=["tern_harbor", "haven_point"],
         reputation=["snobbish", "old money", "good bread", "wet"]),
    dict(id="solana_point", name="Solana Point", test_town="Solana Point", region="south_shore", pop=35000, founded_vy=34, charter_town=False,
         kind="beach city", archetype="city", named_for="south_shore_founders",
         character=["booming", "sunny", "bilingual", "loud", "new money", "the Suns (spinball)"],
         economy=["tourism", "trade", "fishing", "aerostat works", "the Chute South"],
         districts=["Pier Plaza", "Main Street", "the Headland", "Dana Harbour", "Pacific City (the mall)", "Los Arcos", "the Flats"],
         heritage_lean={"hispanic": 2.2, "se_asian": 1.4}, faith_lean={"catholic": 1.3, "full_gospel": 1.4},
         landmarks=["the Long Pier", "the Solana Light", "Pacific City", "the Sun Bowl (spinball ground)"],
         rivals=["port_carrow", "oceanview"], allies=["playa_verde", "pelican_cove"],
         reputation=["flashy", "friendly", "never sleeps", "good tacos"]),
    dict(id="kessler", name="Kessler", test_town="Kessler", region="southland", pop=24000, founded_vy=0, charter_town=True,
         kind="capital town", archetype="county_seat", named_for="ingrid_kessler",
         character=["seat of the Assembly", "lawyers and clerks", "courthouse square", "orderly", "gossip about politics"],
         economy=["government", "the Registry", "the Station Court", "the Commons Bank", "offices", "printing"],
         districts=["Courthouse Square", "the Registry Row", "Assembly Hill", "Old Kessler", "the Bank Blocks", "Mill Street"],
         heritage_lean={"german": 1.5}, faith_lean={"lakes_union": 1.4, "jewish": 3.0},
         landmarks=["the Assembly Hall (rebuilt VY 425)", "the Station Court", "the Registry", "Temple Beth Columbia", "the Launch Bell"],
         rivals=["harrow_falls"], allies=["bellhaven", "pruett"],
         reputation=["stuffy", "knows everyone's business", "boring", "fair"]),
    dict(id="harrow_falls", name="Harrow Falls", test_town="Harrow Falls", region="kettle_valley", pop=22000, founded_vy=0, charter_town=True,
         kind="lake and mill town", archetype="lake_resort", named_for="marcus_harrow",
         character=["the Falls", "mills", "lakefront", "pier and boardwalk", "aerostat racing", "hard-working and proud"],
         economy=["mills (declining)", "tourism", "aerostat racing", "lake fishing", "boatbuilding"],
         districts=["the Falls", "Mill Row", "the Riverfront Promenade", "the Pier", "Main Street", "the Heights"],
         heritage_lean={"german": 1.4, "hungarian": 3.0, "italian": 1.5}, faith_lean={"catholic": 1.2, "lakes_union": 1.2},
         landmarks=["the Falls", "the Falls Pier (opened VY 494)", "Harrow Mill No. 1", "the Aerodrome"],
         rivals=["kessler"], allies=["victory_bay", "port_tamsin"],
         reputation=["loud", "tough", "good fish fry", "racing-mad"]),
    dict(id="oceanview", name="Oceanview", test_town="Oceanview", region="south_shore", pop=18000, founded_vy=61, charter_town=False,
         kind="oceanfront resort", archetype="lake_resort", named_for="its view",
         character=["hotel wall", "concrete boardwalk", "retirees", "stage plaza", "holidaymakers"],
         economy=["hotels", "tourism", "retirement", "music"],
         districts=["the Oceanfront", "the Resort Avenue", "Condo Row", "the Stage Plaza", "Old Oceanview"],
         heritage_lean={}, faith_lean={"lakes_union": 1.3, "none": 1.2},
         landmarks=["the Stage Plaza", "the Fishing Pier", "the Grand Hotel"], rivals=["solana_point", "brightwater"], allies=[],
         reputation=["old people", "sunburn", "overpriced", "pleasant"]),
    dict(id="brightwater", name="Brightwater", test_town="Brightwater", region="north_shore", pop=14000, founded_vy=58, charter_town=False,
         kind="boardwalk town", archetype="lake_resort", named_for="its water",
         character=["boardwalk", "arcades", "amusement pier", "motels", "summer crowds", "young people"],
         economy=["amusements", "tourism", "arcades", "the convention hall"],
         districts=["the Boardwalk", "the Amusement Pier", "Motel Row", "the Cottage Blocks", "Resort Avenue"],
         heritage_lean={"italian": 1.6, "irish_scots": 1.3}, faith_lean={"catholic": 1.2},
         landmarks=["the Brightwater Boardwalk (rebuilt VY 492)", "the Wonder Pier", "Convention Hall"], rivals=["oceanview"], allies=["haven_point"],
         reputation=["tacky", "fun", "drunk in summer", "dead in winter"]),
    dict(id="playa_verde", name="Playa Verde", test_town="Playa Verde", region="south_shore", pop=12000, founded_vy=40, charter_town=False,
         kind="beach town", archetype="lake_resort", named_for="its green beach dunes",
         character=["Spanish spoken first", "plazas", "fiestas", "bungalows", "fishing pier"],
         economy=["fishing", "tourism", "bakeries", "boatbuilding"],
         districts=["the Plaza", "the Pier", "Bungalow Blocks", "El Malecón", "the Dunes"],
         heritage_lean={"hispanic": 3.0}, faith_lean={"catholic": 1.8},
         landmarks=["Nuestra Señora del Viaje (church)", "the Malecón", "the Pier"], rivals=[], allies=["solana_point", "pelican_cove"],
         reputation=["warm", "the best bread", "loud weddings", "proud of its Spanish"]),
    dict(id="marlowe", name="Marlowe", test_town="Marlowe", region="northland", pop=11000, founded_vy=0, charter_town=True,
         kind="farm trade town", archetype="stable_town", named_for="theo_marlowe",
         character=["grain elevator", "farm families", "county fair", "Lutheran-and-Catholic", "slow-spoken"],
         economy=["farming", "the grain elevator", "the flour mill", "feed and seed", "the Northland Fair"],
         districts=["Main Street", "the Elevator", "Fairgrounds", "Church Hill"],
         heritage_lean={"german": 1.8, "scandinavian": 2.0, "dutch": 1.8}, faith_lean={"lakes_union": 1.6, "catholic": 1.1},
         landmarks=["the Marlowe Elevator", "the Northland Fairgrounds", "the Marlowe Mill"], rivals=["fenwick"], allies=["loomis_grove", "dunmore_crossing"],
         reputation=["dull", "honest", "good pie", "stubborn"]),
    dict(id="bellhaven", name="Bellhaven", test_town="Bellhaven", region="southland", pop=10000, founded_vy=0, charter_town=True,
         kind="college town", archetype="college_town", named_for="the Launch Bell's first home",
         character=["Columbia College", "students", "the Wardens' Library", "cafés", "arguments", "the curious"],
         economy=["the College", "cafés", "bookshops", "printing", "the Wardens' Library"],
         districts=["the College Green", "Library Row", "Student Town", "Old Bellhaven"],
         heritage_lean={"south_asian": 1.6, "east_asian": 1.6}, faith_lean={"none": 1.6, "waymakers": 1.3},
         landmarks=["Columbia College (founded VY 150)", "the Wardens' Library", "the Bell Tower"], rivals=[], allies=["kessler"],
         reputation=["know-it-alls", "stay up late", "radicals", "good coffee"]),
    dict(id="tern_harbor", name="Tern Harbor", test_town="Tern Harbor", region="north_shore", pop=7000, founded_vy=12, charter_town=False,
         kind="fishing village", archetype="rust_belt", named_for="the terns of its breakwater",
         character=["fish houses", "the closed cannery (VY 470)", "boatyard", "hard times", "fierce loyalty"],
         economy=["fishing", "boatyard", "the ice house", "the closed cannery"],
         districts=["the Wharves", "Cannery Point", "Net Loft Row", "the Hill"],
         heritage_lean={"irish_scots": 1.6, "francophone": 1.5, "slavic": 1.6}, faith_lean={"catholic": 1.4, "full_gospel": 1.3},
         landmarks=["the Tern Harbor Cannery (closed)", "the Breakwater", "the Auction Shed", "the Coast Guard station"], rivals=["pelican_cove"], allies=["port_carrow"],
         reputation=["hard luck", "fish-smelling", "brave", "drink too much"]),
    dict(id="pelican_cove", name="Pelican Cove", test_town="Pelican Cove", region="south_shore", pop=7000, founded_vy=44, charter_town=False,
         kind="cannery row", archetype="rust_belt", named_for="the pelicans brought aboard in VY 44 (they died out by VY 90)",
         character=["two canneries (one burned VY 478)", "warehouses", "union town", "tough", "Spanish and Vietnamese"],
         economy=["canning", "fishing", "warehousing"],
         districts=["Cannery Row", "the Wharves", "the Village", "Little Saigon Row"],
         heritage_lean={"hispanic": 1.8, "se_asian": 2.5}, faith_lean={"catholic": 1.4, "dharmic": 1.5},
         landmarks=["Pacific Cannery", "the burned Delmar Cannery (VY 478)", "the Union Hall"], rivals=["tern_harbor"], allies=["solana_point", "playa_verde"],
         reputation=["union", "rough", "good soup", "stick together"]),
    dict(id="fenwick", name="Fenwick", test_town="Fenwick", region="northland", pop=6000, founded_vy=0, charter_town=True,
         kind="small town", archetype="stable_town", named_for="the Fenwick fens",
         character=["quiet", "churches", "old families", "machine works", "high school spinball"],
         economy=["machine works", "farming", "shops"],
         districts=["Main Street", "the Works", "Fen Road"],
         heritage_lean={"polish": 1.6, "slavic": 1.5, "black_anglo": 1.4}, faith_lean={"freedom_baptist": 1.8, "catholic": 1.3},
         landmarks=["Fenwick Machine Works", "Mount Zion Freedom Baptist", "St. Casimir's"], rivals=["marlowe"], allies=["haskins_corner"],
         reputation=["churchy", "gossipy", "loyal", "good at spinball"]),
    dict(id="port_tamsin", name="Port Tamsin", test_town="Port Tamsin", region="kettle_valley", pop=6000, founded_vy=88, charter_town=False,
         kind="lake town", archetype="lake_resort", named_for="lake_tamsin",
         character=["marina", "dunes", "resort hotel", "bluff cottages", "sailing"],
         economy=["marina", "tourism", "fishing"], districts=["the Marina", "the Bluff", "Dune Beach", "Downtown"],
         heritage_lean={"dutch": 2.0, "scandinavian": 1.4}, faith_lean={"lakes_union": 1.4},
         landmarks=["the Tamsin Light", "the Marina", "the Bluff Hotel"], rivals=[], allies=["harrow_falls"],
         reputation=["sailors", "summer people", "quiet", "pretty"]),
    dict(id="haven_point", name="Haven Point", test_town="Haven Point", region="north_shore", pop=5000, founded_vy=71, charter_town=False,
         kind="harbour town", archetype="stable_town", named_for="its sheltered point",
         character=["twin piers", "lighthouse and catwalk", "Coast Guard", "riverwalk", "bluff cottages"],
         economy=["Coast Guard", "marina", "tourism", "fishing"], districts=["the Channel", "the Riverwalk", "the Bluff", "Downtown"],
         heritage_lean={"dutch": 1.6, "scandinavian": 1.4}, faith_lean={"lakes_union": 1.3},
         landmarks=["the Haven Light and catwalk", "Coast Guard Station Haven"], rivals=[], allies=["port_carrow", "brightwater"],
         reputation=["neat", "nautical", "a bit smug"]),
    dict(id="victory_bay", name="Victory Bay", test_town="Victory Bay", region="kettle_valley", pop=5000, founded_vy=26, charter_town=False,
         kind="river town", archetype="stable_town", named_for="the end of the Burn Fever (VY 25)",
         character=["river bay", "memorial park", "old people", "boat club"],
         economy=["boatbuilding", "farming", "shops"], districts=["the Bay", "Memorial Park", "Main Street"],
         heritage_lean={"black_anglo": 1.5, "german": 1.2}, faith_lean={"lakes_union": 1.3, "freedom_baptist": 1.3},
         landmarks=["the Fever Memorial", "the Boat Club"], rivals=[], allies=["harrow_falls"],
         reputation=["sleepy", "respectable", "long-lived"]),
    dict(id="tamarack", name="Tamarack", test_town="Tamarack", region="southland", pop=5000, founded_vy=52, charter_town=False,
         kind="farm town", archetype="stable_town", named_for="the tamarack trees planted by its founders",
         character=["dairy farms", "cheese", "Amish-descended Plain families", "quiet"],
         economy=["dairy", "cheese", "farming", "furniture making"], districts=["Main Street", "the Creamery", "Plain Road"],
         heritage_lean={"german": 2.0}, faith_lean={"lakes_union": 1.2, "plain": 3.0},
         landmarks=["the Tamarack Creamery", "the Plain Meetinghouse"], rivals=[], allies=["kessler"],
         reputation=["cheese", "early to bed", "plain", "honest"]),
    dict(id="haskins_corner", name="Haskins Corner", test_town="Haskins Corner", region="northland", pop=4000, founded_vy=79, charter_town=False,
         kind="crossroads town", archetype="stable_town", named_for="the Haskins family's crossroads store",
         character=["crossroads", "diner", "trucking", "fair-weather friends"],
         economy=["trucking", "the diner", "farming"], districts=["the Corner", "Depot Road"],
         heritage_lean={"black_anglo": 1.3, "anglo": 1.2}, faith_lean={"full_gospel": 1.5},
         landmarks=["the Corner Diner", "the Haskins Store"], rivals=[], allies=["fenwick"],
         reputation=["friendly", "nosy", "good pie", "on the way to somewhere"]),
    dict(id="cedar_ford", name="Cedar Ford", test_town="Cedar Ford", region="kettle_valley", pop=2500, founded_vy=95, charter_town=False,
         kind="river village", archetype="stable_town", named_for="the cedar ford of the Kettle",
         character=["flood town (VY 447)", "boardwalk", "canoes", "artists"],
         economy=["tourism", "canoe rental", "crafts"], districts=["the Ford", "the Boardwalk"], heritage_lean={}, faith_lean={"none": 1.4},
         landmarks=["the Flood Line (painted VY 447)", "the Cedar Ford Boardwalk"], rivals=[], allies=["dunmore_crossing"],
         reputation=["arty", "flood-scarred", "hippies"]),
    dict(id="loomis_grove", name="Loomis Grove", test_town="Loomis Grove", region="northland", pop=2000, founded_vy=103, charter_town=False,
         kind="orchard village", archetype="stable_town", named_for="the Loomis orchards",
         character=["apples and cherries", "cider", "harvest festival"], economy=["orchards", "cider"], districts=["the Grove"],
         heritage_lean={"anglo": 1.3}, faith_lean={"lakes_union": 1.5}, landmarks=["the Cider Mill", "the Old Orchard"], rivals=[], allies=["marlowe"],
         reputation=["cider", "sleepy", "pretty in autumn"]),
    dict(id="calder", name="Calder", test_town="Calder", region="southland", pop=7000, founded_vy=186, charter_town=False,
         kind="hospital and farm town", archetype="stable_town", named_for="Ines Calder, the southland's first district physician",
         character=["Calder Memorial Hospital", "the Southland High School Gators", "Main Street on US 30", "the Ring Line depot",
                    "churchgoing", "Friday-night football", "practical"],
         economy=["the hospital", "the schools", "farm trade", "the Southland Co-op Elevator", "shops on US 30", "rail works"],
         districts=["Main Street", "Infirmary Square", "the Old Grid", "the South Side", "Southview", "Bluff Drive"],
         heritage_lean={"german": 1.2, "irish_scots": 1.2}, faith_lean={"lakes_union": 1.3, "catholic": 1.1},
         landmarks=["Calder Memorial Hospital", "Infirmary Square and City Hall", "the Southland Co-op Elevator", "the Calder water tower",
                    "Calder Commons"],
         rivals=["bellhaven"], allies=["pruett", "kessler"],
         reputation=["where you go when you're sick", "solid", "football-mad", "good diners"],
         note="Grew round Ines Calder's infirmary (VY 186) where the Ring Line crossed the section road between Bellhaven and Pruett; "
              "the southland's hospital town ever since. Laid out by the settlement engine (tools/settlegen, 2026-10-06)."),
    dict(id="pruett", name="Pruett", test_town="Pruett", region="southland", pop=1500, founded_vy=110, charter_town=False,
         kind="hamlet", archetype="stable_town", named_for="Hollis Pruett, the surveyor",
         character=["hamlet", "one store", "fields"], economy=["farming"], districts=["Pruett"], heritage_lean={}, faith_lean={},
         landmarks=["Pruett Store"], rivals=[], allies=["kessler"], reputation=["nowhere", "quiet"]),
    dict(id="dunmore_crossing", name="Dunmore Crossing", test_town="Dunmore Crossing", region="northland", pop=1500, founded_vy=90, charter_town=False,
         kind="rail crossing village", archetype="stable_town", named_for="the Dunmore family and the Ring Line crossing",
         character=["the crossing", "the depot", "flood-hit (VY 447)"], economy=["the depot", "farming"], districts=["the Depot"],
         heritage_lean={"irish_scots": 1.4}, faith_lean={"catholic": 1.3}, landmarks=["Dunmore Depot"], rivals=[], allies=["marlowe", "cedar_ford"],
         reputation=["trains", "quiet", "gossip at the depot"]),
    dict(id="countryside", name="the countryside", test_town=None, region="northland", pop=11500, founded_vy=0, charter_town=False,
         kind="farmsteads and roadside", archetype="stable_town", named_for="",
         character=["farmsteads", "section roads", "self-reliant", "the Grange"], economy=["farming", "dairy", "orchards"], districts=[],
         heritage_lean={"german": 1.3, "dutch": 1.3, "scandinavian": 1.3}, faith_lean={"lakes_union": 1.2, "plain": 1.5},
         landmarks=["the Grange halls"], rivals=[], allies=[], reputation=["country", "plain-spoken", "early risers"]),
]
