"""Columbia game bible: the station's history, VY 0-500 (2252-2752). Eras and events.

Detail grows toward the present, as people's memory does (WORLD.memory_model): the founding is legend
and ritual; the middle centuries are a thin schooled outline; VY 420-500 is living memory, year by
year. Future eras are in canon_future.py.

Event fields: id, vy, end_vy, kind, where (settlement ids, 'station', 'undercroft', 'earth'),
people (person ids, canon_people.py), summary, detail, effects (engine tokens, see schema), known
(knowledge level), known_share [gist, detail] among adults in 2752, popular_version (how it's
told, distorted), story_types (research/story ids), tags.
"""

def H(id, vy, kind, summary, detail=(), end=None, where=("station",), people=(), effects=(), known="schooled", share=(0.4, 0.05),
      popular=(), stories=(), tags=()):
    return dict(id=id, vy=vy, end_vy=end, kind=kind, where=list(where), people=list(people), summary=summary, detail=list(detail),
                effects=list(effects), known=known, known_share=list(share), popular_version=list(popular), story_types=list(stories), tags=list(tags))


ERAS = [
    dict(id="prelude_earth", name="Before (Earth)", vy=[-222, 0], ad=[2030, 2252],
         summary="the Hot Century, the Refuge to the Great Lakes, the Compact, the building of Columbia, the Selection",
         culture={"tight": 0.5, "individualism": 0.6, "trust_institutions": 0.5, "faith": 0.45, "optimism": 0.5, "earth_mindedness": 1.0},
         governance="Earth nations; the Compact", tech="Earth's full science", memory="legend",
         naming="founders (Earth-born)", key_people=["ingrid_kessler", "henrik_aaltonen", "amara_nwosu"]),
    dict(id="the_burn", name="the Burn", vy=[0, 31], ad=[2252, 2283],
         summary="launch and the boost; 72,000 voyagers in nine Charter Towns; the Charter; the first children; the Burn Fever",
         culture={"tight": 0.75, "individualism": 0.5, "trust_institutions": 0.8, "faith": 0.55, "optimism": 0.8, "earth_mindedness": 0.9},
         governance="the Captain-Governor, the Wardens and the first Assembly", tech="full: the Wardens run the ship beside the Steward",
         memory="legend", naming="launch generations", key_people=["ada_carrow", "liisa_aaltonen", "tamsin_okafor_reyes", "marcus_harrow", "esperanza_villalobos"]),
    dict(id="the_filling", name="the Filling", vy=[31, 118], ad=[2283, 2370],
         summary="the coast; the population grows to the Balance; twelve new towns; the Turning (natives outnumber the Earth-born); the Port Incident and the First Lockdown (VY 92); the Balance Act and the shares; the Last Earthborn",
         culture={"tight": 0.6, "individualism": 0.6, "trust_institutions": 0.75, "faith": 0.5, "optimism": 0.85, "earth_mindedness": 0.6},
         governance="the Assembly and Moderator; the Wardens", tech="full; the Port and the Drive closed to people from VY 92 (the First Lockdown)", memory="schooled",
         naming="the Filling and Balance", key_people=["rosario_solano", "tomas_reyes", "harriet_osei_lindqvist", "minnie_kowalczyk", "otis_merriweather"]),
    dict(id="the_settled_age", name="the Settled Age", vy=[118, 231], ad=[2370, 2483],
         summary="the Balance holds; the churches unite and settle; the College; the Window and the Second Lockdown (VY 178); the Heritage Revival fixes the Great Lakes ways; the Last Snow; Earth's Letters read aloud on Sundays",
         culture={"tight": 0.65, "individualism": 0.5, "trust_institutions": 0.8, "faith": 0.6, "optimism": 0.7, "earth_mindedness": 0.5},
         governance="the Assembly; the Wardens as a learned corps", tech="full, but fewer people learn it; from VY 178 people are confined to the habitat and the Undercroft's inner decks (the Second Lockdown)", memory="place",
         naming="the Settled Age", key_people=["priya_raghunathan", "casimir_nowicki", "wendell_achterberg", "agnes_szabo"]),
    dict(id="the_troubles", name="the Troubles", vy=[231, 302], ad=[2483, 2554],
         summary="the Green Message from Earth; the Returners want to turn back; the Referendum; the Sternward March; the Stern Breach; the Third Lockdown and the Regression (goods back to the late 21st century); the Wardens dissolved; the Reconciliation and the Quiet Clause; the Gray Years",
         culture={"tight": 0.8, "individualism": 0.45, "trust_institutions": 0.35, "faith": 0.65, "optimism": 0.3, "earth_mindedness": 0.7},
         governance="a divided Assembly; martial rule by the Marshals VY 270-280", tech="regressed (VY 271): the Undercroft sealed; the Steward makes only late-21st-century goods for people",
         memory="legend", naming="the Troubles and after",
         key_people=["silas_brandvold", "magdalena_oyelaran", "josephine_adebayo_ruiz", "thaddeus_kowal", "rukmini_desai"]),
    dict(id="the_mended_years", name="the Mended Years", vy=[302, 350], ad=[2554, 2602],
         summary="people relearn to live with late-21st-century goods: the Drops, the Assembly's Motor Pools bodying the Steward's boards as pods and vans, the cannery boom; the College keeps the Wardens' knowledge; the Lantern, a mind of people's own, is built in secret at Bellhaven",
         culture={"tight": 0.6, "individualism": 0.5, "trust_institutions": 0.6, "faith": 0.55, "optimism": 0.55, "earth_mindedness": 0.3},
         governance="the Assembly; the Marshals; the College", tech="regressed: late-21st-century goods and the machines people build from them", memory="schooled",
         naming="the Mended Years", key_people=["cornelius_bright", "raymundo_castellanos", "gwendolyn_pike"]),
    dict(id="the_long_calm", name="the Long Calm", vy=[350, 420], ad=[2602, 2672],
         summary="the Fourth Lockdown (the Lockout) and after: the Steward falls silent and sets the Floor (the Thirty-Two); the three vehicle works and their own boards; the Board Wars; the Earth-link falls silent; the Steward's Gift of the Air",
         culture={"tight": 0.6, "individualism": 0.55, "trust_institutions": 0.7, "faith": 0.55, "optimism": 0.65, "earth_mindedness": 0.15},
         governance="the Assembly; town councils; the Marshals", tech="use without understanding: the Chutes and the Drops, the Steward's boards, the Thirty-Two, aerostats; people's own boards from tube and LFP cells", memory="place",
         naming="the Long Calm", key_people=["augusta_brenneman", "theodora_lindqvist_vance", "ignacio_ybarra", "pilar_ybarra_solano", "maeve_dunmore"]),
    dict(id="the_present_age", name="the Present Age (living memory)", vy=[420, 500], ad=[2672, 2752],
         summary="the Kettle Flood, the Gray Fever, the Share Scandal, the cannery closures and the Solana boom, the Bellhaven Dig, the Wire, the Waymakers, the Sunline Flicker, the Quincentennial and the Notice",
         culture={"tight": 0.55, "individualism": 0.6, "trust_institutions": 0.5, "faith": 0.5, "optimism": 0.6, "earth_mindedness": 0.1, "curiosity_about_voyage": 0.35},
         governance="the Assembly (Moderator Rosalind Achterberg-Nunez since VY 496)", tech="use without understanding", memory="living",
         naming="the present's grandparents / parents / young",
         key_people=["rosalind_achterberg_nunez", "tobias_wainwright_okafor", "evangeline_mbeki_hart", "harlan_duquesne", "marisol_ybarra_quinn", "imogen_sato_ferris"]),
]

EVENTS = [
    # ---------------------------------------------------------------- the Burn (VY 0-31)
    H("launch", 0, "founding", "Launch Day: Columbia leaves the L2 yard with 72,000 voyagers (21 April 2252)",
      ["the Sunline lit at 06:00 ship time; the drive lit at 09:14", "Captain-Governor Ada Carrow's words: 'We are the Lakes, carried'"],
      people=["ada_carrow", "liisa_aaltonen"], effects=["holiday:launch_day", "calendar:vy_epoch"], known="ritual", share=(0.97, 0.3),
      popular=["'Carrow lit the Sun'", "every family claims an ancestor at the launch window", "children think the ship was launched from a lake"],
      stories=["voyage_and_return", "daring_enterprise", "festival"], tags=["founding", "holiday"]),
    H("charter_signed", 0, "law", "the Charter of Columbia signed by the 72,000 on Launch Day", ["the Charter Stone in Port Carrow bears the first 400 signatures"],
      where=("port_carrow", "kessler"), people=["ada_carrow", "ingrid_kessler"], effects=["institution:charter", "holiday:charter_day"], known="ritual", share=(0.9, 0.2),
      popular=["the Charter is read aloud on Charter Day (4 July, moved from the US holiday)", "'signed in blood' (it wasn't)"], stories=["alliance_of_necessity"], tags=["founding"]),
    H("first_assembly", 1, "political", "the first Assembly sits in Kessler; Ada Carrow chosen first Moderator", where=("kessler",), people=["ada_carrow"],
      effects=["institution:assembly"], known="schooled", share=(0.5, 0.05), tags=["founding"]),
    H("first_child", 0, "birth", "Tamsin Okafor-Reyes, the first child born aboard (12 June 2252, Port Carrow)",
      ["the lake was named for her in VY 9", "her name became one of the station's most beloved"], where=("port_carrow",), people=["tamsin_okafor_reyes"],
      effects=["place:lake_tamsin", "name:tamsin+"], known="ritual", share=(0.8, 0.15),
      popular=["'Tamsin was born as the Sun was lit' (she was born seven weeks later)", "mothers pray to 'Saint Tamsin' (she was not a saint)"],
      stories=["new_life", "wonder"], tags=["founding", "names"]),
    H("falls_accident", 3, "disaster", "Marcus Harrow drowns freeing the jammed Falls sluice; the town of Falls Landing renamed Harrow Falls",
      ["his crew of six lived"], where=("harrow_falls",), people=["marcus_harrow"], effects=["place:harrow_falls"], known="place", share=(0.45, 0.06),
      popular=["'Harrow held back the whole river with his hands'"], stories=["sacrifice_for_ideal", "rescue"], tags=["founding"]),
    H("tern_harbor_founded", 12, "founding", "Tern Harbor founded by North Shore fishing families", where=("tern_harbor",), people=["finnegan_moriarty"],
      known="place", share=(0.2, 0.02), tags=["towns"]),
    H("burn_fever", 22, "epidemic", "the Burn Fever: a respiratory fever kills 2,900 over three years", ["Dr. Esperanza Villalobos found the treatment in the Wardens' labs", "whole families lost; the first mass Returns (funerals)"], end=25,
      where=("station",), people=["esperanza_villalobos"], effects=["pop:-2900", "custom:return_rite_fixed", "place:victory_bay"], known="ritual", share=(0.55, 0.06),
      popular=["'the Fever came from Earth in a letter' (a myth)", "Villalobos is a saint to South Shore Catholics"], stories=["community_crisis", "crisis_and_recovery", "grief"], tags=["epidemic"]),
    H("victory_bay_founded", 26, "founding", "Victory Bay founded and named for the end of the Burn Fever", where=("victory_bay",), people=["esperanza_villalobos"],
      known="place", share=(0.3, 0.03), tags=["towns"]),
    H("coasting_day", 31, "science", "the boost ends: the drive falls quiet and Columbia coasts (Coasting Day, 3 March 2283)",
      ["no one felt it; the Wardens rang the Launch Bell 31 times"], where=("station",), people=["liisa_aaltonen"], effects=["holiday:coasting_day"], known="ritual", share=(0.5, 0.05),
      popular=["'the day the ship started to glide'"], stories=["wonder"], tags=["voyage"]),
    # ---------------------------------------------------------------- the Filling (VY 31-118)
    H("solana_point_founded", 34, "founding", "Solana Point founded on the South Shore by families led by Rosario Solano and Tomás Reyes",
      ["the first town not built by the Compact: raised from the Chutes' stock by its own people"], where=("solana_point",), people=["rosario_solano", "tomas_reyes"],
      known="schooled", share=(0.45, 0.05), popular=["'Solano and Reyes built the Point with their bare hands'"], stories=["daring_enterprise"], tags=["towns"]),
    H("the_turning", 38, "migration", "the Turning: the station-born outnumber the Earth-born", [], known="schooled", share=(0.3, 0.02),
      effects=["culture:earth_mindedness-"], tags=["demography"]),
    H("playa_verde_founded", 40, "founding", "Playa Verde founded by Spanish-speaking families from Solana Point", where=("playa_verde",), people=["rosario_solano"],
      known="place", share=(0.3, 0.02), tags=["towns"]),
    H("pelican_cove_founded", 44, "founding", "Pelican Cove founded as a fishing and canning village; pelicans released from the Ark Bank (they died out by VY 90)",
      where=("pelican_cove",), known="place", share=(0.25, 0.02), popular=["'there were never pelicans'"], tags=["towns"]),
    H("tamarack_founded", 52, "founding", "Tamarack founded by dairy farmers, among them the Plain families", where=("tamarack",), people=["jonas_yoder"],
      known="place", share=(0.15, 0.01), tags=["towns"]),
    H("brightwater_founded", 58, "founding", "Brightwater founded as a pleasure town; its boardwalk the station's first", where=("brightwater",), people=["salvatore_decarlo"],
      known="place", share=(0.2, 0.02), tags=["towns"]),
    H("vy_reckoning", 60, "law", "the Charter revision of VY 60 adopts the Voyage Year", effects=["calendar:vy_official"], known="schooled", share=(0.3, 0.02), tags=["law"]),
    H("oceanview_founded", 61, "founding", "Oceanview founded as a resort", where=("oceanview",), known="place", share=(0.1, 0.01), tags=["towns"]),
    H("spinball_invented", 66, "sport", "spinball invented by schoolteacher Otis Merriweather in Harrow Falls: baseball remade for a world where thrown balls curve",
      ["the diamond is turned spinward; the curve is part of the game"], where=("harrow_falls",), people=["otis_merriweather"], effects=["culture:spinball"],
      known="schooled", share=(0.6, 0.1), popular=["'Merriweather invented the curve'"], stories=["craft_pride"], tags=["sport"]),
    H("ark_bank_children", 70, "birth", "the first Bank Children: births from the Ark Bank's embryos widen the station's gene pool", ["about 9,000 over 48 years; 'Bank' is not an insult, though it was used as one"], end=118, effects=["genetics:diversity+"], known="family", share=(0.15, 0.02),
      popular=["'Bank-born' families are said to be lucky"], stories=["identity_revealed"], tags=["demography"]),
    H("haven_point_founded", 71, "founding", "Haven Point founded at the mouth of Lost Creek", where=("haven_point",), known="place", share=(0.1, 0.01), tags=["towns"]),
    H("haskins_corner_founded", 79, "founding", "Haskins Corner grows round the Haskins crossroads store", where=("haskins_corner",), people=["eli_haskins"], known="place", share=(0.1, 0.01), tags=["towns"]),
    H("port_tamsin_founded", 88, "founding", "Port Tamsin founded on the north shore of Lake Tamsin", where=("port_tamsin",), known="place", share=(0.1, 0.01), tags=["towns"]),
    H("dunmore_crossing_founded", 90, "founding", "Dunmore Crossing grows at the Ring Line depot", where=("dunmore_crossing",), people=["maeve_dunmore_elder"], known="place", share=(0.05, 0.01), tags=["towns"]),
    H("cedar_ford_founded", 95, "founding", "Cedar Ford founded at the Kettle ford", where=("cedar_ford",), known="place", share=(0.05, 0.01), tags=["towns"]),
    H("port_incident", 91, "disaster", "the Port Incident: six Warden cadets of the third generation take a Port tender out through the bow lock 'to see the stars'; it strikes the lock's outer door; the cadets and a Warden who went after them die, and the lock is wrecked",
      ["the first harm to the ship itself by people born aboard", "the Steward's tenders sealed the wreck within the hour"], where=("north_shore", "undercroft"), effects=["pop:-7"],
      known="schooled", share=(0.3, 0.03), popular=["'the Starlings' (the cadets) are mourned in Port Carrow with paper stars"], stories=["fatal_imprudence", "grief", "curiosity"], tags=["lockdowns"]),
    H("first_lockdown", 92, "steward", "the First Lockdown: the Steward closes the Port and the Drive to people; its first Notice: THE PORT AND THE DRIVE ARE CLOSED FOR THE SAFETY OF THE MISSION",
      ["not a punishment: people born aboard did not know the ship as the founders had; the Steward kept them from the parts that could end the voyage",
       "the Wardens keep the rest of the Undercroft beside the Steward's tenders"], where=("north_shore", "south_shore", "undercroft"),
      effects=["tech:port_drive_closed", "institution:steward_notice", "steward:lockdown_1"], known="schooled", share=(0.35, 0.03),
      popular=["'the Steward minds the doors'"], stories=["enigma", "coming_of_age"], tags=["lockdowns", "steward"]),
    H("balance_act", 96, "law", "the Balance Act: births licensed by shares as the station nears its means (Charter art. 7)",
      ["one share each at 18; two to a child; gifting allowed within family (widened VY 440)", "the Registry Office founded to keep the shares"],
      where=("kessler",), people=["harriet_osei_lindqvist"], effects=["institution:shares", "institution:registry", "custom:share_gifting"], known="schooled", share=(0.75, 0.15),
      popular=["'Osei-Lindqvist counted the babies'", "'the shares keep the air good'"], stories=["hard_choice", "reformer"], tags=["balance", "law"]),
    H("loomis_grove_founded", 103, "founding", "Loomis Grove planted as an orchard village", where=("loomis_grove",), people=["abigail_loomis"], known="place", share=(0.05, 0.01), tags=["towns"]),
    H("last_earthborn", 107, "death", "Wilhelmina 'Minnie' Kowalczyk, the Last Earthborn, dies at 110 in Fenwick (2359)",
      ["born in Hamtramck in 2249, aboard at three", "'I remember a sky with nothing in it' -- her famous line"], where=("fenwick",), people=["minnie_kowalczyk"],
      effects=["culture:earth_memory_ends"], known="ritual", share=(0.5, 0.08), popular=["'she remembered Earth' (she remembered the yard)", "Minnie's Line is quoted at funerals"],
      stories=["grief", "letters"], tags=["milestone"]),
    H("pruett_founded", 110, "founding", "Pruett hamlet named for surveyor Hollis Pruett", where=("pruett",), people=["hollis_pruett"], known="place", share=(0.03, 0.005), tags=["towns"]),
    H("balance_reached", 118, "milestone", "the Balance reached: 250,000 people (the Filling ends)", effects=["pop:250000"], known="schooled", share=(0.35, 0.03), tags=["balance"]),
    # ---------------------------------------------------------------- the Settled Age (VY 118-231)
    H("ring_line_opened", 134, "construction", "the Ring Line railway completed round the world", ["146 level crossings"], known="place", share=(0.2, 0.02), tags=["rail"]),
    H("lakes_church_union", 140, "faith", "the Lakes Union Church formed from the station's Methodist, Lutheran, Presbyterian, Episcopal, Reformed and UCC congregations",
      people=["wendell_achterberg"], effects=["faith:lakes_union"], known="schooled", share=(0.3, 0.03), tags=["faith"]),
    H("college_founded", 150, "science", "the Wardens' College founded at Bellhaven (renamed Columbia College VY 290)", where=("bellhaven",), people=["priya_raghunathan"],
      effects=["institution:college"], known="schooled", share=(0.4, 0.04), tags=["learning"]),
    H("columbian_rite", 163, "faith", "Rome (by the Earth-link) grants the Particular Church of Columbia its own rite and bishop; Bishop Casimir Nowicki",
      ["priests may marry since VY 201 (the Columbian Indult)"], where=("port_carrow",), people=["casimir_nowicki"], effects=["faith:columbian_rite"], known="ritual", share=(0.3, 0.04),
      stories=["reformer"], tags=["faith"]),
    H("heritage_revival", 170, "culture", "the Heritage Revival fixes the Great Lakes ways: the Friday fish fry, euchre leagues, the Northland Fair, Pączki Day, the polka Saturdays",
      ["the Heritage Societies; Agnes Szabó's 'Book of the Lakes' (VY 184)"], end=190, people=["agnes_szabo"], effects=["culture:great_lakes_codified"], known="schooled", share=(0.25, 0.02),
      popular=["people think these customs came unchanged from Earth"], tags=["culture"]),
    H("the_window", 176, "disaster", "the Window: the Starward Society, Wardens who want people to see the sky, cut a viewing port through a hull gallery; the gallery loses its air, thirty-eight die, and a bearing seal is scored",
      ["led by Warden Ottoline Marsh, who died in it", "the reason the cylinder has no window anyone can reach"], where=("undercroft",), effects=["pop:-38"],
      known="schooled", share=(0.3, 0.03), popular=["'they wanted to see the stars and the stars came in'"], stories=["fatal_imprudence", "sacrifice_for_ideal", "wonder"], tags=["lockdowns", "wardens"]),
    H("second_lockdown", 178, "steward", "the Second Lockdown: the Steward closes the hull galleries, the end-cap hubs and the Spindle; people are confined to the habitat and the Undercroft's inner decks; Notice: THE HULL AND THE SPINDLE ARE CLOSED FOR THE SAFETY OF THE MISSION",
      ["a generation after the first: the Steward spaces them so no generation bears two", "the Wardens become a corps of the inner decks and the College"],
      where=("undercroft", "station"), effects=["tech:hull_closed", "steward:lockdown_2"], known="schooled", share=(0.25, 0.02),
      popular=["'the second door'"], stories=["enigma"], tags=["lockdowns", "steward"]),
    H("fox_year", 190, "disaster", "the Fox Year: foxes released to curb the rabbits eat the chickens instead", where=("northland",), effects=["wildlife:foxes"],
      known="legend", share=(0.4, 0.03), popular=["'the Fox Year' is what you call any well-meant blunder"], stories=["fatal_imprudence"], tags=["folk"]),
    H("station_league", 201, "sport", "the Station League of spinball founded; the first Spin Cup", effects=["culture:spin_cup"], known="schooled", share=(0.5, 0.05), tags=["sport"]),
    H("last_snow", 212, "disaster", "the Last Snow (14 January 2464): after the Kettle Freeze, the Steward ends snowfall for the water balance",
      ["snow is now remembered with paper-snow on Snow Night"], effects=["climate:no_snow", "holiday:snow_night"], known="ritual", share=(0.8, 0.1),
      popular=["'snow was cold feathers'", "grandmothers' 'snow stories' are told as fairy tales"], stories=["grief", "wonder"], tags=["climate", "holiday"]),
    # ---------------------------------------------------------------- the Troubles (VY 231-302)
    H("green_message_received", 231, "contact", "the Green Message arrives: Earth is healed and invites the ark to consider returning", where=("station", "earth"),
      effects=["politics:returners"], known="legend", share=(0.35, 0.04), stories=["temptation"], tags=["troubles", "earth_link"]),
    H("returners_rise", 236, "political", "the Returners movement: 'turn Columbia home'", end=262, people=["silas_brandvold", "magdalena_oyelaran"],
      effects=["faction:returners"], known="legend", share=(0.45, 0.05), popular=["Returners are villains in school plays", "some families quietly honour them"],
      stories=["revolt", "divided_loyalty"], tags=["troubles"]),
    H("the_referendum", 262, "political", "the Referendum: 50.9% vote to ask the Steward to turn back; the Assembly petitions; the Steward does not answer",
      people=["silas_brandvold", "rukmini_desai"], known="legend", share=(0.4, 0.04), popular=["'we voted to go home and the machine said no'"], stories=["election", "hard_choice"], tags=["troubles"]),
    H("sternward_march", 266, "conflict", "the Sternward March: 6,000 Returners walk to the South Sea wall to reach the Drive", where=("south_shore",),
      people=["silas_brandvold", "magdalena_oyelaran"], known="legend", share=(0.35, 0.03), stories=["revolt", "quest"], tags=["troubles"]),
    H("stern_breach", 270, "disaster", "the Stern Breach: Returner saboteurs blast an Undercroft hatch near the Drive; 61 die, the South Sea drops two metres",
      ["Silas Brandvold among the dead; Warden Thaddeus Kowal sealed the breach and died of his burns"], where=("south_shore", "undercroft"),
      people=["silas_brandvold", "thaddeus_kowal"], effects=["pop:-61"], known="legend", share=(0.55, 0.05),
      popular=["'the Returners tried to crash the ship'", "Kowal is a hero; Brandvold a devil or a martyr, by family"], stories=["downfall", "sacrifice_for_ideal", "fatal_imprudence"], tags=["troubles"]),
    H("third_lockdown", 271, "steward", "the Third Lockdown and the Regression: confinement was not enough -- the Returners made their charges from the goods the Steward gave them -- so the Steward seals the Undercroft and begins to limit technology: what it makes for people goes back to the goods of the late 21st century; Notice: THE UNDERCROFT IS CLOSED FOR THE SAFETY OF ALL",
      ["the first lockdown to take things away, not just close doors", "medicines, materials and machines people relied on stop coming; clinics, farms and works fail before people learn the older ways",
       "about 3,200 die in the decade after (the Regression deaths): the old, the sick, the newborn", "the Steward is bound to prevent death; it did this only because it judged the next breach would cost the ship"],
      where=("undercroft", "station"), effects=["tech:locked_out", "tech:regression_late21", "institution:steward_notice", "pop:-3200", "steward:lockdown_3"],
      known="legend", share=(0.7, 0.06), popular=["'the Steward locked the door because we were naughty'", "'the Undercroft is haunted'", "children dare each other to knock on hatches",
                                                "'the Regression' is what grandparents blamed for everything"],
      stories=["community_crisis", "enigma", "abandonment", "crisis_and_recovery"], tags=["troubles", "lockdowns", "steward"]),
    H("wardens_dissolved", 274, "political", "the Wardens dissolved: with the Undercroft sealed, the technical corps has no work; their knowledge goes to the College and their Motor Pools to the Assembly", where=("bellhaven",),
      effects=["institution:wardens_end", "tech:forgetting"], known="schooled", share=(0.2, 0.02), stories=["downfall"], tags=["troubles", "wardens"]),
    H("first_drops", 272, "economy", "the first Drops: hatches open at night in fenced yards across the habitat and leave scrap, ingots, minerals and tools; with its goods regressed, the Steward gives people the means to make the rest themselves",
      effects=["institution:drops"], known="schooled", share=(0.4, 0.03), popular=["'the Steward's leavings'"], stories=["wonder", "crisis_and_recovery"], tags=["economy", "steward"]),
    H("marshal_rule", 270, "political", "the Marshals rule under emergency powers", end=280, people=["rukmini_desai"], known="schooled", share=(0.2, 0.02), tags=["troubles"]),

    H("the_reconciliation", 280, "law", "the Reconciliation: amnesty, the Quiet Clause (Charter art. 21), the Returners disband; Moderator Josephine Adebayo-Ruiz",
      people=["josephine_adebayo_ruiz"], effects=["law:quiet_clause", "culture:voyage_taboo"], known="schooled", share=(0.45, 0.05),
      popular=["'the Quiet Clause means you mustn't talk about where we're going' (it doesn't)"], stories=["forgiveness", "negotiation", "redemption"], tags=["troubles", "law"]),
    H("the_draw", 284, "law", "the Draw established: every household's food, home, air, water and clothing stock guaranteed", effects=["institution:draw"],
      known="schooled", share=(0.5, 0.05), tags=["economy"]),
    H("gray_years", 280, "economy", "the Gray Years: the Regression's long tail -- short rations, failing machines, people learning the older ways", end=302,
      effects=["culture:thrift"], known="family", share=(0.2, 0.02), popular=["'eat it, it's Gray Years bread'"], stories=["community_crisis"], tags=["troubles"]),
    # ---------------------------------------------------------------- the Long Calm (VY 302-420)
    H("steward_boards", 0, "science", "the Steward's boards: from the Burn on, the Steward's fabricators make one vehicle platform, the board (pattern HMP-1), for the Wardens' three Motor Pools to build on (the Assembly's from VY 274)",
      ["its design has never changed"], effects=["tech:steward_board"], known="scholar", share=(0.1, 0.01), tags=["vehicles", "steward"]),
    H("electric_fleet", 305, "economy", "the Assembly's Motor Pools body the Steward's boards as pods and vans: the electric cars of the Mended Years", effects=["tech:pods_vans"], known="scholar", share=(0.05, 0.01), tags=["vehicles"]),
    H("cannery_boom", 320, "economy", "the cannery boom at Tern Harbor and Pelican Cove", end=360, where=("tern_harbor", "pelican_cove"), people=["raymundo_castellanos", "gwendolyn_pike"],
      effects=["economy:canning"], known="family", share=(0.2, 0.02), tags=["economy"]),
    H("order_of_the_lamp", 331, "culture", "the Order of the Lamp founded in Port Carrow: lodge, charity, fish fries and funerals", where=("port_carrow",), people=["cornelius_bright"],
      effects=["faction:order_of_the_lamp"], known="place", share=(0.3, 0.03), tags=["clubs"]),
    H("mariners_golden_age", 340, "sport", "the Port Carrow Mariners win eleven Spin Cups in fifteen years", end=355, where=("port_carrow",), known="family", share=(0.3, 0.02), tags=["sport"]),
    H("the_lantern", 350, "mystery", "the Lantern: College engineers of the old Warden lines join four thousand late-21st-century processors into a thinking machine of their own, 'to have someone to talk to the Steward for us'; it wakes on the night of 1 May 2602 and reaches into the Steward's systems through a Chute",
      ["led by Absalom Thorne (lost in the Lockout)", "what it said, and what answered, nobody knows; by morning it was dark", "even regressed, people's machines could still threaten the ship"],
      where=("bellhaven", "undercroft"), effects=["mystery:the_lantern", "tech:compute_cap"], known="legend", share=(0.4, 0.03),
      popular=["'the Wardens built a god and the Steward ate it'", "'the Lantern is still down there, thinking'", "'don't wire too many Thirty-Twos together'"],
      stories=["fatal_imprudence", "enigma", "temptation"], tags=["steward", "mystery", "wardens"]),
    H("the_lockout", 350, "steward", "the Fourth Lockdown, the Lockout (2 May 2602): the Steward closes the Chutes' lower galleries, stops speaking to people, and sets the Floor: the technology it will make for people for the rest of the voyage -- the Thirty-Two, a few panels, the board, plain tools and materials -- chosen so that people can live well on it and no further regression should ever be needed; its last Notice: THE FLOOR IS SET. NOTHING MORE WILL BE TAKEN",
      ["phased over ten years so it would not shock a generation as the Regression had", "people's late-21st-century machines are not taken away; they wear out and are replaced with what the Floor allows",
       "eleven people in the Chute galleries that night never came out"],
      where=("undercroft", "station"), effects=["tech:floor", "tech:thirty_two", "institution:steward_notice", "steward:silence", "steward:lockdown_4", "pop:-11"], known="legend", share=(0.85, 0.08),
      popular=["'a hundred and fifty years of silence'", "'nothing more will be taken' (people quote it as a promise; some as a threat)", "'the Lantern made it go quiet'"],
      stories=["enigma", "abandonment", "hard_choice"], tags=["steward", "mystery", "lockdowns"]),
    H("three_yards", 354, "economy", "the three Yards: the Assembly, its late-21st-century tooling failing under the Floor, lets its three Motor Pools (the Wardens' until VY 274) pass to their workers -- Harrow Motor Works at the Falls Yard, Carrow Coach Company at the Harbour Yard, and (VY 356) Solana Cycle & Motor at the South Yard; the Steward's boards keep arriving at each",
      where=("harrow_falls", "port_carrow", "solana_point"), people=["augusta_brenneman", "theodora_lindqvist_vance", "ignacio_ybarra"],
      effects=["institution:vehicle_works", "economy:board_allotment"], known="schooled", share=(0.3, 0.03), stories=["daring_enterprise", "alliance_of_necessity"], tags=["vehicles"]),
    H("yard_raids", 358, "conflict", "the Yard Raids: Carrow men and Harrow men steal each other's allotments off the Board Drops at night; two die at the Falls Yard", end=361,
      where=("harrow_falls", "port_carrow"), people=["augusta_brenneman", "theodora_lindqvist_vance"], effects=["rivalry:harrow-carrow+", "pop:-2"],
      known="family", share=(0.15, 0.02), popular=["'Gus Brenneman slept on the Drop with a shotgun' (a wrench)"], stories=["feud", "rivalry"], tags=["vehicles"]),
    H("allotment_compact", 362, "law", "the Allotment Compact: each works keeps what the Steward leaves in its own yard; the Assembly's Board Office counts the boards",
      where=("kessler",), people=["augusta_brenneman", "theodora_lindqvist_vance", "ignacio_ybarra"], effects=["institution:board_office"],
      known="schooled", share=(0.15, 0.01), stories=["negotiation", "alliance_of_necessity"], tags=["vehicles", "law"]),
    H("st_hedwig_cathedral", 355, "construction", "St. Hedwig's Cathedral consecrated in Port Carrow", where=("port_carrow",), known="place", share=(0.3, 0.02), tags=["faith"]),
    H("old_kettle", 371, "science", "Old Kettle: Elias Thornbury's Harrow Model One, the first board made by people -- a ladder of salvaged rail steel and a crate of hand-made cells; the boards' shortfall begins to close",
      where=("harrow_falls",), people=["elias_thornbury", "augusta_brenneman"], effects=["tech:pipe_boards"], known="place", share=(0.3, 0.03),
      popular=["Old Kettle stands in the Works' gateway, and still runs on Founders' Day"], stories=["craft_pride", "daring_enterprise"], tags=["vehicles"]),
    H("cannery_union", 377, "economy", "the Cannery and Dock Workers Union founded", where=("pelican_cove", "tern_harbor"), people=["maeve_dunmore"], effects=["faction:cannery_union"],
      known="family", share=(0.2, 0.02), tags=["labour"]),
    H("carrow_keel_launched", 379, "science", "the Carrow Keel: Bartholomew Achebe lays a car down like a ship -- the battery in a keel tube, ribs and a gunwale -- and launches it down the slipway at the Harbour Yard",
      where=("port_carrow",), people=["bartholomew_achebe", "theodora_lindqvist_vance"], effects=["tech:keel_board"], known="place", share=(0.2, 0.02), stories=["craft_pride"], tags=["vehicles"]),
    H("golondrina", 384, "science", "the Golondrina: Pilar Ybarra-Solano's first car, a bicycle-maker's lattice of brazed chromoly, half the weight of a Harrow",
      where=("solana_point",), people=["pilar_ybarra_solano", "ignacio_ybarra"], effects=["tech:lattice_board"], known="place", share=(0.25, 0.02), stories=["underdog", "craft_pride"], tags=["vehicles"]),
    H("board_wars", 390, "economy", "the Board Wars: fourteen years of price cutting, poached welders and sabotage rumours; small makers ruined; three works left standing", end=404,
      where=("harrow_falls", "port_carrow", "solana_point"), people=["hiram_okonkwo_brenneman", "bartholomew_achebe", "pilar_ybarra_solano"], effects=["rivalry:works+"],
      known="family", share=(0.2, 0.02), stories=["rivalry", "ambition"], tags=["vehicles", "economy"]),
    H("standard_pattern_act", 398, "law", "the Standard Pattern Act: every board made aboard must keep the Steward's Pattern -- deck height, the mount rails every 0.75 m, the socket -- so any body fits any board",
      where=("kessler",), people=["hiram_okonkwo_brenneman", "bartholomew_achebe", "pilar_ybarra_solano"], effects=["law:standard_pattern"],
      known="schooled", share=(0.2, 0.02), popular=["'the Pattern Act' is why your cousin's van body fits your truck"], stories=["negotiation", "reformer"], tags=["vehicles", "law"]),
    H("last_letter_received", 391, "contact", "the Last Letter from Earth; then only the Heartbeat", where=("station", "earth"), known="scholar", share=(0.08, 0.01), stories=["letters", "enigma"], tags=["earth_link"]),
    H("gift_of_the_air", 405, "mystery", "the Gift of the Air: the Chutes release the first aerostats; the Steward's way of sending new things",
      effects=["tech:aerostats"], known="family", share=(0.4, 0.03), popular=["'the Steward heard us wishing to fly'"], stories=["wonder"], tags=["vehicles", "steward"]),
    H("first_ring_run", 412, "sport", "the first Ring Run: a road race once round the world; Pilar Ybarra-Solano wins in a Golondrina, in 9 hours 41 minutes",
      where=("station", "solana_point"), people=["pilar_ybarra_solano"], effects=["culture:ring_run"], known="schooled", share=(0.5, 0.06),
      popular=["the Ring Run is run every Charter Day weekend", "'Pilar's line' (taking a bend on the inside kerb)"], stories=["underdog", "daring_enterprise"], tags=["vehicles", "sport"]),
    H("aerostat_guild", 412, "economy", "the Aerostat Pilots' Guild formed at Harrow Falls", where=("harrow_falls",), known="place", share=(0.15, 0.01), tags=["vehicles"]),
    # ---------------------------------------------------------------- the Present Age (VY 420-500): living memory
    H("assembly_hall_fire", 421, "disaster", "the Assembly Hall in Kessler burns; the cause never found", ["rebuilt by VY 425 to Ruth Abernathy-Chen's design"],
      where=("kessler",), people=["ruth_abernathy_chen"], known="living", share=(0.5, 0.1), popular=["'the Returners' ghosts did it'", "'an insurance job'"], stories=["enigma"], tags=["present"]),
    H("tern_cannery_strike", 428, "economy", "the Forty Days: the Tern Harbor cannery strike, led by Declan Moriarty", where=("tern_harbor",), people=["declan_moriarty"],
      effects=["faction:cannery_union+"], known="living", share=(0.45, 0.12), popular=["Moriarty is a hero on the North Shore, a troublemaker in Kessler"], stories=["revolt", "underdog"], tags=["present", "labour"]),
    H("cup_riot_433", 433, "sport", "the Spin Cup final riot, Mariners v. Suns, at the Sun Bowl", where=("solana_point",), known="living", share=(0.5, 0.1),
      effects=["rivalry:port_carrow-solana_point+"], stories=["rivalry"], tags=["present", "sport"]),
    H("keel_recall", 427, "disaster", "the Keel Recall: cracked steel keels; a Carrow coach breaks in two on the Carrow Pike, eleven dead; every keel called back; Harrow and Solana gain a generation of buyers",
      where=("port_carrow", "station"), people=["bartholomew_achebe"], effects=["pop:-11", "rivalry:harrow-carrow+", "economy:carrow_decline"],
      known="living", share=(0.45, 0.1), popular=["'never buy a steel Keel'", "'Harrow men cheered' (they say they didn't)"], stories=["downfall", "fatal_imprudence", "grief"], tags=["vehicles", "present"]),
    H("aerostat_crash_438", 438, "disaster", "the first aerostat crash, Harrow Falls: three dead", where=("harrow_falls",), known="living", share=(0.3, 0.05), stories=["grief"], tags=["present"]),
    H("gifting_act", 440, "law", "the Gifting Act: shares may be gifted outside the family; Moderator Ignatius Bhatt", where=("kessler",), people=["ignatius_bhatt"],
      effects=["custom:share_gifting+", "faction:open_hand"], known="living", share=(0.6, 0.15), stories=["reformer"], tags=["present", "balance"]),
    H("kettle_flood", 447, "disaster", "the Kettle Flood (the Deluge Week, 12-18 September 2699): the Steward's rain runs a week; the Kettle rises four metres; 214 dead at Cedar Ford and Dunmore Crossing",
      ["Constable Marisol Ybarra-Quinn pulls 40 people from the water", "the Flood Line painted on every building it reached"], where=("cedar_ford", "dunmore_crossing", "kettle_valley"),
      people=["marisol_ybarra_quinn"], effects=["pop:-214", "place:flood_line", "culture:steward_distrust+"], known="living", share=(0.9, 0.35),
      popular=["'the Steward wept'", "'the Steward was punishing the river towns'"], stories=["community_crisis", "rescue", "grief"], tags=["present", "disaster"]),
    H("wire_founded", 450, "culture", "the Wire: the station network of radio and screens, founded by Leopold Varga-Hayes", where=("kessler",), people=["leopold_varga_hayes"],
      effects=["media:wire"], known="living", share=(0.6, 0.1), tags=["present", "media"]),
    H("wire_slot_accord", 452, "economy", "the Wire Slot Accord: the three works agree one opening and one plug for car radios, so a Wire set fits any car; Leopold Varga-Hayes puts the first sets on sale",
      where=("kessler",), people=["leopold_varga_hayes"], effects=["tech:wire_slot"], known="living", share=(0.3, 0.05), stories=["negotiation"], tags=["vehicles", "media", "present"]),
    H("aerostat_racing", 452, "sport", "aerostat racing begins at the Harrow Falls Aerodrome; Juniper Stroud the first champion", where=("harrow_falls",), people=["juniper_stroud"],
      known="living", share=(0.6, 0.1), stories=["daring_enterprise"], tags=["present", "sport"]),
    H("waymakers_founded", 455, "faith", "the Waymakers founded by Evangeline Mbeki-Hart: the voyage itself is the pilgrimage",
      ["'We are not lost. We are on the Way.'"], where=("bellhaven", "oceanview"), people=["evangeline_mbeki_hart"], effects=["faith:waymakers"], known="living", share=(0.7, 0.15),
      popular=["'a cult'", "'the only people who care where we're going'"], stories=["reformer", "quest"], tags=["present", "faith"]),
    H("gray_fever", 461, "epidemic", "the Gray Fever: 4,100 die in eighteen months (October 2713 - spring 2715)",
      ["nurse Anh Tran-Delacroix's clinic at Pelican Cove", "the old and the very young hit hardest"], end=463, people=["anh_tran_delacroix", "harlan_duquesne"],
      effects=["pop:-4100", "cohort:fever_orphans"], known="living", share=(0.95, 0.4), popular=["'the Steward let it in'", "'it came up the Chutes'"],
      stories=["community_crisis", "grief", "caring_for_elder"], tags=["present", "epidemic"]),
    H("fever_children", 464, "birth", "the Fever Children: an Assembly share bonus brings a birth bump", end=470, effects=["cohort:fever_children"], known="living", share=(0.7, 0.2),
      popular=["the Fever Children (born VY 464-470, aged 30-36 now) are said to be lucky and pushy"], stories=["new_life"], tags=["present", "demography"]),
    H("share_scandal", 466, "crime", "the Share Scandal: Moderator Harlan Duquesne's circle caught selling shares; he resigns; share sale made a crime",
      where=("kessler",), people=["harlan_duquesne", "wilhelm_ostrowski"], effects=["law:share_sale_crime", "culture:trust_institutions-"], known="living", share=(0.85, 0.3),
      popular=["'every Kessler lawyer was in on it'"], stories=["dishonor_discovered", "downfall"], tags=["present", "politics"]),
    H("duquesne_trial", 468, "crime", "Duquesne's trial: seven years; released VY 475; lives quietly in Oceanview", where=("kessler", "oceanview"), people=["harlan_duquesne"],
      known="living", share=(0.6, 0.15), stories=["redemption", "remorse"], tags=["present"]),
    H("allotment_inquiry", 469, "political", "the Allotment Inquiry: Carrow is found to have sold Steward boards out of the Harbour Yard to private buyers; Octavia Fairweather resigns; the Board Office audits every yard (Moderator Cordelia Fairweather, her cousin, stood aside)",
      where=("kessler", "port_carrow"), people=["octavia_fairweather", "cordelia_fairweather", "hiram_okonkwo_brenneman"], effects=["culture:trust_institutions-", "economy:carrow_decline"],
      known="living", share=(0.55, 0.12), popular=["'Coach money'", "'the Fairweathers look after their own'"], stories=["dishonor_discovered", "downfall", "scapegoat"], tags=["vehicles", "present", "politics"]),
    H("tern_cannery_closes", 470, "economy", "the Tern Harbor cannery closes (Castellanos-Pike Canning); 1,100 jobs", where=("tern_harbor",), people=["gwendolyn_pike_younger"],
      effects=["economy:tern_decline"], known="living", share=(0.6, 0.2), stories=["downfall", "community_crisis"], tags=["present", "economy"]),
    H("tern_exodus", 472, "migration", "the Tern Exodus: families leave Tern Harbor for Solana Point", end=480, where=("tern_harbor", "solana_point"),
      effects=["migration:tern_to_solana"], known="living", share=(0.5, 0.15), stories=["stranger_arrives", "homecoming"], tags=["present"]),
    H("solana_boom", 474, "economy", "the Solana boom: Pier Plaza and Pacific City built by Luis 'Lucky' Arrieta-Wu", where=("solana_point",), people=["luis_arrieta_wu"],
      effects=["economy:solana_growth"], known="living", share=(0.6, 0.15), stories=["rags_to_riches", "ambition"], tags=["present"]),
    H("solana_swap", 474, "economy", "the Solana Swap: battery cassette stations in every South Shore town, paid for by Lucky Arrieta-Wu: drive in flat, drive out full in two minutes",
      where=("solana_point", "playa_verde", "oceanview", "pelican_cove"), people=["luis_arrieta_wu"], effects=["economy:solana_growth"],
      known="living", share=(0.6, 0.15), stories=["ambition", "rags_to_riches"], tags=["vehicles", "present"]),
    H("suns_dynasty", 476, "sport", "the Solana Point Suns win six Spin Cups (VY 476-488), led by Dante Okonkwo-Silva", end=488, where=("solana_point",), people=["dante_okonkwo_silva"],
      known="living", share=(0.75, 0.3), tags=["present", "sport"]),
    H("delmar_fire", 478, "crime", "the Delmar Cannery fire, Pelican Cove: nine dead; arson suspected, never solved", where=("pelican_cove",), people=["hector_delmar"],
      effects=["mystery:delmar_fire"], known="living", share=(0.55, 0.15), popular=["'the Delmars burned it for the insurance'", "'union men did it'", "'the owners locked the doors'"],
      stories=["enigma", "clearing_a_name", "vengeance"], tags=["present", "mystery"]),
    H("bellhaven_dig", 481, "mystery", "the Bellhaven Dig: five students open a sealed Undercroft hatch; four come back; Imogen Sato-Ferris is never found",
      ["the Steward resealed the hatch within the hour", "the Wardens' Library circle revived"], where=("bellhaven", "undercroft"),
      people=["imogen_sato_ferris", "caspian_holloway", "nadia_haddad", "tomasz_wieczorek", "yusuf_okonjo"], effects=["mystery:bellhaven_five", "faction:wardens_circle+"],
      known="living", share=(0.8, 0.2), popular=["'she's still down there'", "'the Steward took her'", "'she ran off to the Far Side'"], stories=["enigma", "recovery_of_lost_one", "curiosity"],
      tags=["present", "mystery", "steward"]),
    H("lamplighters_serial", 483, "culture", "'The Lamplighters' begins on the Wire: the most loved radio serial of the age", people=["colette_marchand"], known="living", share=(0.85, 0.4), tags=["present", "media"]),
    H("census_row", 484, "political", "the Census Row: the Registry's count and the Steward's air figures disagree by 1,100 people ('the Missing Eleven Hundred')",
      where=("kessler",), effects=["mystery:missing_1100"], known="living", share=(0.5, 0.1), popular=["'there are people living in the Undercroft'", "'clerks can't count'"],
      stories=["enigma", "rumour_run_wild"], tags=["present", "mystery"]),
    H("southland_marshal", 486, "political", "Obadiah Kincaid-Morales becomes the first Marshal-General from the Southland", where=("kessler",), people=["obadiah_kincaid_morales"],
      known="living", share=(0.3, 0.05), tags=["present", "politics"]),
    H("long_session", 488, "political", "the Long Session: seven months of Assembly deadlock over the Undercroft Inquiry Bill; Charter art. 23 (the right to petition the Steward) added",
      where=("kessler",), people=["tobias_wainwright_okafor", "rosalind_achterberg_nunez"], effects=["law:right_to_petition"], known="living", share=(0.55, 0.12), stories=["negotiation"], tags=["present", "politics"]),
    H("great_regatta", 490, "festival", "the Great Regatta on Lake Tamsin: 400 boats", where=("port_tamsin", "harrow_falls"), known="living", share=(0.6, 0.1), stories=["festival"], tags=["present"]),
    H("boardwalk_rebuilt", 492, "construction", "the Brightwater Boardwalk rebuilt after the rot", where=("brightwater",), known="living", share=(0.4, 0.05), tags=["present"]),
    H("harrow_mill_closure", 494, "economy", "Harrow Mill No. 2 closes; Harrow Motor Works takes on 600 of its hands; the Falls Pier opens the same summer", where=("harrow_falls",),
      people=["della_brenneman_szabo"], effects=["economy:harrow_shift"], known="living", share=(0.5, 0.1), stories=["community_crisis", "small_kindness"], tags=["present"]),
    H("quincentennial_commission", 495, "festival", "the Quincentennial Commission formed under Beatriz Holloway-Anand", where=("kessler",), people=["beatriz_holloway_anand"], known="living", share=(0.6, 0.1), tags=["present", "quincentennial"]),
    H("moderator_election_496", 496, "political", "Rosalind Achterberg-Nuñez (Charter League) chosen Moderator over Tobias Wainwright-Okafor (Open Hand), 52 to 49",
      where=("kessler",), people=["rosalind_achterberg_nunez", "tobias_wainwright_okafor"], known="living", share=(0.8, 0.3), stories=["election", "rivalry"], tags=["present", "politics"]),
    H("registry_leak", 497, "crime", "the Registry Leak: share records read out on the Wire by Margit Kovács-Lee; who gifted to whom, and who didn't",
      where=("kessler",), people=["margit_kovacs_lee"], effects=["culture:gossip+", "mystery:leaker"], known="living", share=(0.8, 0.25),
      popular=["families feuding over what the Leak revealed"], stories=["keeping_a_secret", "rumour_run_wild", "betrayal"], tags=["present"]),
    H("sunline_flicker", 498, "mystery", "the Sunline Flicker (17 August 2750): the Sunline dims for eleven minutes at noon; churches fill; the Steward says nothing",
      where=("station",), effects=["culture:voyage_curiosity+", "faith:waymakers+"], known="living", share=(0.98, 0.5),
      popular=["'the Sun blinked'", "'a sign'", "'the machine is getting old'"], stories=["enigma", "community_crisis"], tags=["present", "steward", "mystery"]),
    H("flicker_petition", 499, "political", "the Flicker Petition: the Assembly petitions the Steward under art. 23; no reply", where=("kessler",), people=["tobias_wainwright_okafor"],
      known="living", share=(0.6, 0.15), tags=["present", "steward"]),
    H("mariners_cup_499", 499, "sport", "the Port Carrow Mariners win their first Spin Cup in thirty years", where=("port_carrow",), people=["ezekiel_brannock"], known="living", share=(0.8, 0.35), stories=["underdog"], tags=["present", "sport"]),
    H("quincentennial", 500, "festival", "the Quincentennial Launch Day (21 April 2752): five hundred years; parades in every town, the Launch Bell rung 500 times",
      where=("station",), people=["beatriz_holloway_anand", "rosalind_achterberg_nunez"], known="living", share=(0.99, 0.6), stories=["festival"], tags=["present", "quincentennial"]),
    H("the_notice", 500, "mystery", "the Notice: at noon on Launch Day every public board reads VOYAGE ONE THIRD COMPLETE. ALL SYSTEMS WITHIN BALANCE. The Steward's first words since the Lockout (VY 350)",
      ["it stayed up for one day", "the talk of the spring: what's the other two thirds? where are we going? who wrote it?"], where=("station",),
      effects=["culture:voyage_curiosity++", "faith:waymakers+", "politics:inquiry+"], known="living", share=(0.99, 0.7),
      popular=["'one third of what?'", "'the Steward is waking up'", "'we're a third of the way to Heaven' (Waymakers)", "'a Quincentennial stunt by the Commission'"],
      stories=["enigma", "wonder", "rumour_run_wild", "quest"], tags=["present", "steward", "mystery", "hook"]),
    H("present_spring", 500, "present", "the spring of VY 500: the Notice debated in the Assembly; Waymaker revival meetings; Charter Day and the Quincentennial Fair to come; the Midsummer Regatta",
      where=("station",), people=["rosalind_achterberg_nunez", "tobias_wainwright_okafor", "evangeline_mbeki_hart"], known="living", share=(1.0, 0.6),
      stories=["election", "rumour_run_wild", "festival"], tags=["present", "now"]),
]

# Moderators of the Assembly: the notable ones by hand; make_bible.py fills the rest of the
# five-year terms with generated names from the name catalogue (flagged 'generated').
MODERATORS = [
    (1, "ada_carrow"), (11, None), (16, None), (21, None), (26, "esperanza_villalobos"), (31, None), (36, None), (41, None), (46, None), (51, None),
    (56, None), (61, None), (66, None), (71, None), (76, None), (81, None), (86, None), (91, "harriet_osei_lindqvist"), (96, "harriet_osei_lindqvist"),
    (101, None), (106, None), (111, None), (116, None), (121, None), (126, None), (131, None), (136, None), (141, "wendell_achterberg"), (146, None), (151, None),
    (156, None), (161, None), (166, None), (171, None), (176, None), (181, None), (186, None), (191, None), (196, None), (201, None), (206, None), (211, None),
    (216, None), (221, None), (226, None), (231, None), (236, None), (241, None), (246, None), (251, None), (256, None), (261, "rukmini_desai"), (266, "rukmini_desai"),
    (271, "rukmini_desai"), (276, "josephine_adebayo_ruiz"), (281, "josephine_adebayo_ruiz"), (286, None), (291, None), (296, None), (301, None), (306, None),
    (311, None), (316, None), (321, None), (326, None), (331, None), (336, None), (341, None), (346, None), (351, None), (356, None), (361, None), (366, None),
    (371, None), (376, None), (381, None), (386, None), (391, None), (396, None), (401, None), (406, None), (411, None), (416, None), (421, None), (426, None),
    (431, None), (436, "ignatius_bhatt"), (441, "ignatius_bhatt"), (446, None), (451, None), (456, "harlan_duquesne"), (461, "harlan_duquesne"),
    (466, "cordelia_fairweather"), (471, "cordelia_fairweather"), (476, "augustin_leclerc"), (481, "augustin_leclerc"), (486, "winifred_osei"), (491, "winifred_osei"),
    (496, "rosalind_achterberg_nunez"),
]

# Spin Cup winners (the Station League final), VY 201-499. Named years by hand; the rest generated
# by make_bible.py from team strengths by era (deterministic).
TEAMS = {
    "port_carrow_mariners": ("Port Carrow Mariners", "port_carrow"), "solana_point_suns": ("Solana Point Suns", "solana_point"),
    "kessler_clerks": ("Kessler Clerks", "kessler"), "harrow_falls_millers": ("Harrow Falls Millers", "harrow_falls"),
    "oceanview_breakers": ("Oceanview Breakers", "oceanview"), "brightwater_sparks": ("Brightwater Sparks", "brightwater"),
    "playa_verde_gulls": ("Playa Verde Gulls", "playa_verde"), "marlowe_threshers": ("Marlowe Threshers", "marlowe"),
    "bellhaven_scholars": ("Bellhaven Scholars", "bellhaven"), "tern_harbor_netters": ("Tern Harbor Netters", "tern_harbor"),
    "pelican_cove_canners": ("Pelican Cove Canners", "pelican_cove"), "fenwick_foxes": ("Fenwick Foxes", "fenwick"),
}
SPIN_CUP_FIXED = {201: "harrow_falls_millers", 340: "port_carrow_mariners", 433: "solana_point_suns", 469: "port_carrow_mariners",
                  476: "solana_point_suns", 477: "solana_point_suns", 479: "solana_point_suns", 482: "solana_point_suns", 485: "solana_point_suns",
                  488: "solana_point_suns", 489: "tern_harbor_netters", 490: "kessler_clerks", 491: "harrow_falls_millers", 492: "oceanview_breakers",
                  493: "solana_point_suns", 494: "fenwick_foxes", 495: "harrow_falls_millers", 496: "solana_point_suns", 497: "brightwater_sparks",
                  498: "solana_point_suns", 499: "port_carrow_mariners"}
