"""Columbia game bible: culture in VY 500. The founders' Great Lakes ways (and the continent's, carried
by the refuge families), and what 500 years aboard did to them. Every entry names where it came from
and how it changed, so dialogue can use both.

Sections: HOLIDAYS, FOODS, RITES (life-cycle), CUSTOMS (everyday), LEXICON, SAYINGS, BELIEFS (about
the voyage, the Steward, Earth), SUPERSTITIONS, ETIQUETTE, TABOOS, PASTIMES (sports, games), ARTS
(music, radio, reading), DIALECT, CHANGES (origin -> station form), SCHOOLING.

Sources for the Great Lakes origins: research/demographics (Great Lakes community profiles),
research/coastal_communities/great_lakes_and_fishing.md, research/roles/02_middle_america.md,
and general knowledge of Ohio/Michigan/Illinois/Indiana/Wisconsin/western NY and Pennsylvania life
(Inland North English: 'pop', 'party store', Dyngus Day, Pączki Day, the Friday fish fry,
euchre, Sweetest Day, the Coney, Cincinnati chili, the parish festival). Marked 'station' where
invented for Columbia.
"""

# (id, name, date or rule, origin, since_vy, observed_by, share_observing, activities, places, foods, notes)
HOLIDAYS = [
    ("new_year", "New Year's Day", "01-01", "earth", 0, "all", 0.95, ["late party", "resolutions", "the Sunline brightened at midnight for one minute (a Steward custom)"], ["bar", "community_hall"], ["pork and sauerkraut (for luck)", "black-eyed peas"], "the Steward's midnight brightening is the only light-show it gives"),
    ("snow_night", "Snow Night", "12-21", "station", 213, "all", 0.85, ["paper snow thrown from windows", "grandmothers' snow stories", "children cut paper snowflakes", "cocoa"], ["park_pavilion", "school"], ["cocoa", "cut-out cookies"], "remembering the Last Snow (VY 212); the longest night"),
    ("christmas", "Christmas", "12-25", "earth", 0, "christian+secular", 0.8, ["Midnight Mass", "Wigilia (Polish Christmas Eve)", "tamales (Mexican families)", "tourtière (the Côte)", "lights on porches", "the Szabó Christmas in Harrow Falls"], ["church", "residence"], ["tamales", "pierogi", "tourtière", "kolaczki", "ham", "cookies"], ""),
    ("paczki_day", "Pączki Day", "Fat Tuesday (the day before Ash Wednesday)", "earth:polish_detroit", 170, "all", 0.7, ["lines at bakeries from dawn", "eating a dozen"], ["bakery"], ["pączki (jelly doughnuts)"], "a Hamtramck custom, now everyone's"),
    ("lent_fridays", "Lenten Fridays (the fish fry season)", "Fridays of Lent", "earth", 0, "all (Catholic origin)", 0.75, ["the Friday fish fry at every tavern, church and lodge"], ["bar", "church", "community_hall"], ["perch", "walleye", "cod", "fries", "coleslaw", "rye bread"], "the fish fry runs every Friday all year now; Lent is its high season"),
    ("easter", "Easter", "Western Easter (computus kept)", "earth", 0, "christian", 0.6, ["sunrise services at the Sunline's dawn", "egg hunts", "the blessing of the baskets (święconka)"], ["church", "park_pavilion"], ["ham", "kielbasa", "butter lambs", "hot cross buns"], ""),
    ("dyngus_day", "Dyngus Day", "Easter Monday", "earth:polish_buffalo", 170, "Hedwig Hill, Fenwick, the young", 0.25, ["water fights", "pussy-willow tapping", "polka in the street"], ["bar", "park_pavilion"], ["kielbasa", "beer"], "Port Carrow's Hedwig Hill throws the station's biggest"),
    ("launch_day", "Launch Day", "04-21", "station", 1, "all", 0.99, ["the Launch Bell rung (once per voyage-year at Kessler; 500 times in VY 500)", "family dinners with an empty chair for those left on Earth", "the toast 'To Ada'", "parades", "the Launch Day fish boil"], ["community_hall", "park_pavilion", "church", "residence"], ["the Launch Day fish boil", "sheet cake"], "the station's great civic holiday"),
    ("coasting_day", "Coasting Day", "03-03", "station", 32, "schoolchildren, the College", 0.3, ["children 'glide' in their socks on school floors", "kite flying"], ["school"], ["pancakes"], "for the day the drive went quiet"),
    ("return_day", "Return Day", "last Monday of May", "earth:memorial_day+station", 26, "all", 0.85, ["visits to the memorial groves", "the Fever and Breach memorials", "the first swim of summer", "the summer opens"], ["park_pavilion", "church"], ["cookouts", "potato salad"], "Memorial Day merged with the Burn Fever remembrance; the dead of the voyage"),
    ("tamsins_day", "Tamsin's Day", "06-12", "station", 92, "Port Tamsin, mothers, girls named Tamsin", 0.35, ["blessings of babies at the lake", "flower crowns"], ["park_pavilion", "church"], ["strawberries"], "the first child aboard"),
    ("charter_day", "Charter Day", "07-04", "earth:us_independence_day+station", 1, "all", 0.95, ["the Charter read aloud on every town square", "fireworks (light-shows: the Steward dims the Sunline an hour early)", "parades", "picnics"], ["park_pavilion", "town_hall"], ["hot dogs", "sweet corn", "cherry pie", "pop"], "the US holiday kept, its meaning moved to the Charter; the Steward's early dusk is taken as its blessing"),
    ("midsummer_regatta", "the Midsummer Regatta", "the Saturday nearest 07-20", "station", 140, "lake and shore towns", 0.4, ["sailboat and rowing races on Lake Tamsin and the seas", "boat parades"], ["harbormaster", "park_pavilion"], ["fish boil", "cherry pie"], ""),
    ("fiesta_de_rosario", "the Fiesta de Rosario", "the second weekend of August", "station", 80, "the South Shore", 0.45, ["mariachi and cumbia", "the Solano procession", "dancing on the Malecón"], ["park_pavilion", "church"], ["tamales", "elote", "churros", "horchata"], "for Rosario Solano"),
    ("northland_fair", "the Northland Fair", "the last week of August, Marlowe", "earth:county_fair", 30, "farm towns, children", 0.6, ["4-H-style livestock shows (the Young Growers)", "pie contests", "the midway", "tractor pulls (electric)"], ["amusement", "park_pavilion"], ["elephant ears", "corn dogs", "lemonade shake-ups", "pie"], ""),
    ("labor_day", "Labor Day (the Union Parade)", "first Monday of September", "earth", 0, "all", 0.7, ["the Cannery and Dock Workers' parade", "the end of summer", "the Tern Harbor 'Forty Days' march (since VY 429)"], ["park_pavilion"], ["cookout"], ""),
    ("reconciliation_day", "Reconciliation Day", "first Sunday of October", "station", 281, "all", 0.5, ["families mend quarrels", "the Troubles remembered", "a shared meal with someone you've wronged"], ["church", "residence"], ["bread broken together"], "for Josephine Adebayo-Ruiz"),
    ("sweetest_day", "Sweetest Day", "third Saturday of October", "earth:cleveland", 0, "couples", 0.4, ["candy and flowers to sweethearts"], ["florist", "variety_store"], ["candy"], "a Cleveland custom kept"),
    ("halloween", "Halloween", "10-31", "earth", 0, "children, the young", 0.8, ["trick-or-treat", "costumes", "'haunted' Undercroft hatch dares"], ["residence"], ["candy", "cider"], "knocking on a sealed hatch at midnight is the great dare"),
    ("return_night", "Return Night (Día de los Muertos)", "11-01 to 11-02", "earth:mexico+station", 30, "all", 0.6, ["ofrendas for the Returned (the dead)", "marigolds at the memorial groves", "stories of the dead"], ["church", "residence", "park_pavilion"], ["pan de muerto", "sugar skulls", "tamales"], "Día de Muertos and All Souls merged with the Return rites"),
    ("deer_opener", "the Opener", "the Monday after Thanksgiving", "earth:michigan_deer_season", 0, "Northland men, the countryside", 0.2, ["the men go to 'camp' (a cabin by a creek) to fish and play euchre; schools close in the Northland", "nobody hunts: there are no deer"], ["residence"], ["venison-style sausage (pork)", "beer"], "Michigan's deer opener with no deer: the name and the cabin week survive"),
    ("thanksgiving", "Thanksgiving", "fourth Thursday of November", "earth", 0, "all", 0.95, ["family dinner", "the Thanksgiving spinball games", "parades"], ["residence"], ["turkey (from Tamarack farms)", "stuffing", "cranberries", "pumpkin pie", "tamales in some families"], "the station's family holiday"),
    ("balance_day", "Balance Day (the census)", "the 1st of June every 5th year (VY 500 next)", "station", 100, "all", 0.7, ["the census count", "share gifting suppers"], ["town_hall"], [], "the Registry counts everyone; VY 500's count begins 1 June 2752"),
    ("eid", "Eid al-Fitr and Eid al-Adha", "lunar", "earth:muslim", 0, "muslim", 0.03, ["prayers at the masjid", "feasts", "gifts"], ["church"], ["ma'amoul", "lamb"], ""),
    ("diwali", "Diwali", "lunar", "earth:hindu", 0, "dharmic", 0.03, ["lamps", "sweets"], ["residence"], ["sweets"], ""),
    ("hanukkah", "Hanukkah", "lunar", "earth:jewish", 0, "jewish", 0.01, ["candles"], ["residence", "church"], ["latkes"], ""),
    ("lunar_new_year", "Lunar New Year (Tết)", "lunar", "earth:asian", 0, "Little Saigon Row, East Asian families", 0.04, ["the Nguyen feast", "red envelopes"], ["residence", "restaurant"], ["bánh chưng", "dumplings"], ""),
    ("saint_jean", "Saint-Jean-Baptiste Day", "06-24", "earth:quebec", 0, "the Côte", 0.02, ["bonfires on the beach", "Carrow French songs"], ["park_pavilion"], ["tourtière", "sugar pie"], ""),
    ("juneteenth", "Juneteenth (Freedom Day)", "06-19", "earth:us", 0, "Freedom Baptist, Fenwick, Victory Bay", 0.25, ["freedom services", "picnics", "red food"], ["church", "park_pavilion"], ["red pop", "barbecue"], ""),
    ("waymakers_vigil", "the Waymakers' Vigil", "the eve of Launch Day", "station", 456, "waymakers", 0.06, ["an all-night vigil facing north ('toward where we're going')"], ["church", "park_pavilion"], [], ""),
]

# (id, name, kind, origin heritage, when, where (place types), station note)
FOODS = [
    ("fish_fry", "the Friday fish fry", "meal", "great_lakes", "every Friday", ["bar", "church", "community_hall", "diner"], "Lake Tamsin perch and walleye, North Sea cod; beer batter; rye bread and coleslaw"),
    ("perch", "lake perch", "dish", "great_lakes", "any", ["restaurant", "diner", "fish_market"], "the station's favourite fish"),
    ("walleye", "walleye", "dish", "great_lakes", "any", ["restaurant", "fish_market"], ""),
    ("fish_boil", "the fish boil", "meal", "great_lakes:door_county", "Launch Day, the Regatta", ["park_pavilion"], "a kettle boil with the boil-over flare"),
    ("pierogi", "pierogi", "dish", "polish", "Christmas, church festivals, any", ["restaurant", "church"], "potato and cheese, sauerkraut, sweet cheese"),
    ("kielbasa", "kielbasa", "dish", "polish", "Easter, Dyngus Day", ["butcher"], ""),
    ("paczki", "pączki", "sweet", "polish", "Pączki Day", ["bakery"], ""),
    ("coney", "the Coney (chili dog)", "dish", "greek_detroit", "any", ["diner"], "the Corner Diner's is famous"),
    ("kessler_chili", "Kessler chili (three-way, four-way, five-way)", "dish", "cincinnati", "any", ["diner"], "Cincinnati chili on spaghetti, renamed for the capital"),
    ("paprikash", "chicken paprikash", "dish", "hungarian", "Sundays", ["residence"], "Harrow Falls"),
    ("stuffed_cabbage", "stuffed cabbage (gołąbki, töltött káposzta)", "dish", "polish+hungarian", "holidays", ["residence", "church"], ""),
    ("tamales", "tamales", "dish", "mexican", "Christmas, Return Night, weddings", ["residence", "bakery"], "the tamalada (tamale-making party) is a family rite"),
    ("tacos", "tacos", "dish", "mexican", "any", ["restaurant", "food_stand"], "Solana Point's night stands"),
    ("elote", "elote", "dish", "mexican", "summer, fiestas", ["food_stand"], ""),
    ("conchas", "conchas and pan dulce", "sweet", "mexican", "mornings", ["bakery"], "La Estrella, Playa Verde"),
    ("pupusas", "pupusas", "dish", "salvadoran", "any", ["restaurant"], ""),
    ("mofongo", "mofongo", "dish", "puerto_rican", "any", ["restaurant"], ""),
    ("jerk_chicken", "jerk chicken", "dish", "jamaican", "cookouts", ["restaurant", "food_stand"], ""),
    ("soul_food", "Sunday soul food (fried chicken, greens, mac and cheese, cornbread)", "meal", "african_american", "Sundays, church suppers", ["residence", "church"], "Booker women's suppers"),
    ("barbecue", "barbecue", "dish", "southern", "cookouts, Juneteenth", ["restaurant", "park_pavilion"], "the refuge families brought it north"),
    ("gumbo", "gumbo", "dish", "louisiana", "any", ["restaurant"], ""),
    ("tourtiere", "tourtière", "dish", "quebecois", "Christmas, Saint-Jean", ["bakery", "residence"], "the Côte"),
    ("poutine", "poutine", "dish", "quebecois", "late night", ["diner", "bar"], "Port Carrow bar food"),
    ("sugar_pie", "sugar pie (tarte au sucre)", "sweet", "quebecois", "holidays", ["bakery"], ""),
    ("shawarma", "shawarma", "dish", "lebanese", "any", ["restaurant", "food_stand"], "King Street, Port Carrow"),
    ("manakish", "manakish", "dish", "lebanese", "mornings", ["bakery"], "the Haddad bakery"),
    ("pho", "phở", "dish", "vietnamese", "any", ["restaurant"], "Little Saigon Row, Pelican Cove"),
    ("banh_mi", "bánh mì", "dish", "vietnamese", "lunch", ["restaurant", "food_stand"], ""),
    ("curry", "curry and dal", "dish", "south_asian", "any", ["restaurant", "residence"], "Bellhaven"),
    ("samosa", "samosas", "dish", "south_asian", "any", ["bakery", "food_stand"], ""),
    ("dumplings", "dumplings", "dish", "chinese+korean", "any, Lunar New Year", ["restaurant"], ""),
    ("jollof", "jollof rice", "dish", "west_african", "parties", ["residence"], "Okafor and Okonkwo weddings"),
    ("tamarack_blue", "Tamarack Blue (cheese)", "food", "station", "any", ["grocery"], "the Yoders' blue cheese"),
    ("cheese_curds", "fried cheese curds", "dish", "wisconsin", "the fair, bars", ["bar", "amusement"], ""),
    ("sweet_corn", "sweet corn", "food", "midwest", "August", ["grocery", "food_stand"], "farm stands"),
    ("cherries", "cherries and cherry pie", "sweet", "michigan", "July", ["bakery", "food_stand"], "the Loomis Grove cherries"),
    ("cider", "cider and cider doughnuts", "drink", "midwest", "autumn", ["food_stand", "bakery"], "Loomis Grove Cider Mill"),
    ("buckeyes", "buckeyes (peanut-butter chocolate)", "sweet", "ohio", "Christmas, spinball days", ["residence"], ""),
    ("pop", "pop (soft drinks)", "drink", "great_lakes", "any", ["variety_store", "charge_stop", "diner"], "never 'soda'; 'Kettle Ginger' ginger pop is the station's own"),
    ("kettle_ginger", "Kettle Ginger", "drink", "station:detroit_vernors", "any", ["variety_store", "diner"], "a sharp ginger pop 'for upset stomachs', after Detroit's Vernors"),
    ("beer", "beer (lager, the 'Falls Pale')", "drink", "great_lakes", "any", ["bar"], "Harrow Falls brewing"),
    ("coffee", "coffee", "drink", "universal", "all day", ["cafe", "diner"], "grown in the Undercroft; people don't know where it comes from"),
    ("hotdish", "the casserole (hotdish)", "dish", "midwest", "funerals, new babies, potlucks", ["residence", "church"], "you bring one when someone is born, sick or Returned"),
    ("sheet_cake", "sheet cake", "sweet", "midwest", "every celebration", ["bakery"], ""),
    ("jello_salad", "Jell-O salad (the 'salad' that is not a salad)", "dish", "midwest", "potlucks", ["church"], "a joke and a sacrament"),
    ("vat_bread", "Draw bread", "food", "station", "every day", ["grocery"], "the plain loaf from the Draw; 'Gray Years bread' when stale"),
]

# life-cycle rites
RITES = [
    ("registering", "the Registering", "birth", "the baby is entered at the Registry with both parents' shares; the family brings a casserole to the Registrar (a joke that became a custom)", "station", ["town_hall"]),
    ("baptism_naming", "baptism / naming / aqiqah / bris", "birth", "by faith; the unchurched have a 'naming supper'", "earth", ["church", "residence"]),
    ("first_swim", "the First Swim", "childhood", "a child's first swim in the lake or sea at Return Day; Harrows swim the Falls pool at 18", "station", ["park_pavilion"]),
    ("share_day", "Share Day", "18th birthday", "the Registry letter arrives: 'You hold one share.' Families throw a party; some young people tear the letter in half for luck", "station", ["residence", "town_hall"]),
    ("courtship", "courting", "youth", "walking out on the boardwalk or the lakeshore; the fish fry date; the Sweetest Day box of candy", "earth", ["bar", "cafe", "park_pavilion"]),
    ("the_sharing", "the Sharing (a wedding)", "marriage", "the couple's two share letters are pinned together at the altar or the town hall; guests pin money to the bride's and groom's clothes (the money dance, from Polish and Mexican weddings); the dollar dance; a polka or cumbia; a fish boil for the reception in shore towns", "earth+station", ["church", "community_hall"]),
    ("gift_supper", "the Gift Supper", "adult", "when someone gifts their share, the receiving family gives a supper in their honour; the child made possible is 'share-kin' to the giver and calls them 'Aunt' or 'Uncle'", "station", ["residence"]),
    ("tamalada", "the tamalada", "family", "a day of tamale-making before Christmas: the women's gossip rite", "mexican", ["residence"]),
    ("the_return", "the Return (a funeral)", "death", "a wake with food; a service by faith; the body given to the Return hall for the soil cycle; a tree or a stone in the memorial grove; 'Minnie's Line' read ('I remember a sky with nothing in it'); a hotdish for the family", "station", ["funeral_home", "church", "park_pavilion"]),
    ("anniversary_grove", "the grove visit", "memory", "each Return Day families sit by their trees in the memorial grove", "station", ["park_pavilion"]),
    ("retirement_boat", "the retirement boat", "work", "fishers and canners retiring get a rowboat ride round the harbour", "station", ["harbormaster"]),
]

# everyday customs
CUSTOMS = [
    ("midwest_goodbye", "the long goodbye", "leaving takes half an hour: goodbyes in the kitchen, at the door, on the porch and at the car"),
    ("porch_sitting", "porch sitting", "summer evenings on the porch, waving at walkers"),
    ("euchre_night", "euchre night", "the card game of the Great Lakes; leagues in taverns and lodges; bragging rights ('going alone')"),
    ("potluck", "the potluck", "everyone brings a dish; the church basement supper"),
    ("casserole_duty", "casserole duty", "a dish to any family with a birth, an illness or a Return"),
    ("parish_festival", "the parish festival", "summer weekend: rides, beer tent, raffles, polka"),
    ("fish_fry_friday", "Friday is fish", "most families eat fish on Friday; taverns full"),
    ("lake_days", "lake days", "summer Sundays at the beach or the lake"),
    ("steward_nod", "the Steward nod", "a small nod to a passing tender (maintenance machine); older people touch a hatch for luck"),
    ("sunline_hush", "the dusk hush", "at the Sunline's dimming, some older people stop talking for a moment"),
    ("north_facing", "facing north", "beds and pews are often set to face north ('the way we're going') -- Waymakers insist, others just do"),
    ("share_talk", "not asking about shares", "asking a childless adult 'why no kids?' is rude; people say 'they gifted' and leave it"),
    ("pop_not_soda", "pop, not soda", "calling it 'soda' marks you as 'Carrow French' or a snob"),
    ("tailgate", "the tailgate", "spinball game days: cookouts from the backs of vans"),
    ("rummage_sale", "the rummage sale", "spring and autumn: whole streets sell their old things"),
    ("garage_workshop", "the garage", "men and women alike keep a workshop or a bar in the garage"),
    ("church_supper", "the church supper", "Wednesday or Sunday evening"),
    ("union_hall", "the union hall dance", "Saturday nights in Pelican Cove and Tern Harbor"),
    ("lodge_night", "lodge night", "the Order of the Lamp meets Tuesdays"),
    ("wire_evening", "the Wire evening", "families gather for 'The Lamplighters' at 19:30 on Thursdays"),
    ("draw_day", "Draw Day", "the first of the month: the Draw's credits land; grocery lines; small indulgences"),
    ("bank_child_luck", "Bank luck", "people from Bank-born families are thought lucky: touch their sleeve before a game"),
]

# Columbian English words and phrases: (term, meaning, origin, register/who, example)
LEXICON = [
    ("pop", "a soft drink", "great_lakes", "everyone", "'Grab me a pop from the party store.'"),
    ("party store", "a corner shop that sells drinks", "michigan", "everyone", "'The party store on Mill Street stays open late.'"),
    ("ope", "a small apology or surprise", "midwest", "everyone", "'Ope, sorry, let me squeeze past.'"),
    ("you guys / youse / y'all / you-all", "second person plural", "great_lakes+southern", "by region: 'youse' in Port Carrow, 'y'all' in Haskins Corner, 'you guys' elsewhere", ""),
    ("the Sunline", "the light along the axis", "station", "everyone", "'The Sunline's coming up.'"),
    ("the Far Side / overhead", "the land 6 km above, across the axis", "station", "everyone", "'On a clear day you can see Oceanview on the Far Side.'"),
    ("spinward / antispin", "the way the land turns / against it", "station", "everyone; directions are given this way", "'Two blocks spinward, then north.'"),
    ("north", "toward the bow; 'where we're going'", "station", "everyone", "'Face north for luck.'"),
    ("sternside", "southward; also old-fashioned or backward-looking", "station", "slang", "'That's a real sternside idea.'"),
    ("the Steward", "the station's automation", "station", "everyone", "'The Steward'll fix it.'"),
    ("tender", "a maintenance machine", "station", "everyone", "'There's a tender on the roof.'"),
    ("the Undercroft / downstairs", "the sealed decks below the floor", "station", "everyone", "'Don't knock on that hatch; you'll wake downstairs.'"),
    ("the Chutes", "the Steward's goods depots", "station", "everyone", "'The Chutes are short on cloth this month.'"),
    ("the Draw", "the monthly allotment", "station", "everyone", "'We're on the Draw till payday.'"),
    ("a share", "a birth share", "station", "everyone", "'She gifted her share to her sister.'"),
    ("share-kin", "a child made possible by someone's gifted share; the giver is their share-aunt or share-uncle", "station", "everyone", "'He's my share-kin -- I gifted to his mom.'"),
    ("unspent", "(of a person) still holding their share; (of a thing) unused, kept for later", "station", "everyone", "'She's thirty and still unspent.'"),
    ("to Return / the Returned", "to die / the dead (given back to the soil cycle)", "station", "polite", "'Grandpa Returned last spring.'"),
    ("Earthy", "quaint, old-fashioned, sentimental", "station", "young people", "'That's so Earthy, Grandma.'"),
    ("Earthsick", "homesick for a place you've never been; melancholy", "station", "everyone", "'He gets Earthsick in winter.'"),
    ("a Foxworth", "a well-meaning blunder or blunderer", "station:fox_year", "everyone", "'Don't pull a Foxworth.'"),
    ("Gray Years bread", "stale bread; anything grim and plain", "station:gray_years", "older people", "'Eat it, it's Gray Years bread.'"),
    ("the Balance", "the station's limits; also: fairness, enough", "station", "everyone", "'That's not in the Balance' = 'that's too much'."),
    ("balance keep you", "a farewell", "station", "older, formal", "'Balance keep you, dear.'"),
    ("on the Way", "a Waymaker greeting; mocked by others", "station:waymakers", "Waymakers", "'On the Way, brother.'"),
    ("a third of the way", "halfway through something without an end in sight (since the Notice)", "station:notice", "new slang, VY 500", "'This meeting's a third of the way.'"),
    ("Carrow-proud", "snobbish", "station", "South Shore people", "'Don't get Carrow-proud with me.'"),
    ("Pointer", "a person from Solana Point (loud, flashy)", "station", "North Shore people", ""),
    ("netter", "a Tern Harbor person", "station", "everyone", ""),
    ("Plain", "the Amish-descended families", "earth:amish", "everyone", ""),
    ("pod / van", "the two kinds of car", "station", "everyone", "'Take the pod.'"),
    ("stat", "an aerostat", "station", "everyone", "'We took a stat to Harrow Falls.'"),
    ("the Wire", "the station network (radio, screens)", "station", "everyone", "'Did you hear it on the Wire?'"),
    ("the Boards", "the public notice screens", "station", "everyone", "'It was on the Boards.'"),
    ("the Notice", "the Steward's message of Launch Day VY 500", "station", "everyone", "'What do you make of the Notice?'"),
    ("goin' alone", "euchre: playing without your partner; doing something bold alone", "great_lakes", "everyone", ""),
    ("jagoff", "a jerk", "pittsburgh", "Port Carrow, Tern Harbor", ""),
    ("sweeper", "a vacuum cleaner", "great_lakes", "older people", ""),
    ("doorwall", "a sliding glass door", "detroit", "everyone", ""),
    ("gapers' block", "a jam of people staring at something", "chicago", "everyone", "'There was a gapers' block at the Flicker.'"),
    ("bubbler", "a drinking fountain", "wisconsin", "Marlowe, the Northland", ""),
    ("mija / mijo", "my dear (to a child or younger person)", "spanish", "everyone on the South Shore", ""),
    ("ándale", "hurry up / come on", "spanish", "everyone", ""),
    ("Dios te guarde", "farewell ('God keep you')", "spanish", "Playa Verde", ""),
    ("tabarnak", "a curse (Carrow French)", "quebecois", "the Côte (mild now)", ""),
    ("habibi / habibti", "dear", "arabic", "King Street, everyone", ""),
    ("the Fever Children", "those born VY 464-470", "station", "everyone", ""),
    ("Bank-born", "descended from the Ark Bank's embryos", "station", "everyone", ""),
    ("the Troubles", "VY 231-302", "station", "everyone", ""),
    ("a Returner", "someone who wants to go back; an old insult for a malcontent", "station", "everyone", "'Don't be such a Returner.'"),
    ("the Lockout", "the Fourth Lockdown (VY 350), when the Steward fell silent; also: being shut out of anything", "station", "everyone", "'I'm on Lockout from my own kitchen.'"),
    ("the Lockdowns", "the Steward's four closings (VY 92, 178, 271, 350), each a generation apart", "station", "everyone", "'Every generation gets a lockdown, my gran said. We're overdue.'"),
    ("the Regression", "the Third Lockdown's taking-back of goods (VY 271) and the hard years after", "station", "the old, the schooled", "'That's a Regression recipe: no sugar, no salt.'"),
    ("the Floor", "what the Steward still makes for people since VY 350; also: the least you'll accept", "station", "everyone", "'That's my floor -- nothing more will be taken.'"),
    ("a true board", "a Steward board (the station's own vehicle platform); also: anything well made that you couldn't make yourself", "vehicles", "everyone", "'That's a true board under that tram.'"),
    ("a pipe board", "a board made by people (tube frame): a Harrow, a Carrow or a Solana", "vehicles", "everyone", "'It's only a pipe board, but it's paid for.'"),
    ("a Harrow / a Carrow / a Solana", "a car by its works (also 'a Coach', 'a Sunny')", "vehicles", "everyone", "'She drives a Carrow, so she thinks she's Kessler.'"),
    ("a Thirty-Two", "the Steward's processor board; any computer", "station", "everyone", "'Get a Thirty-Two to count it.'"),
    ("the Drops / a Drop night", "the Steward's raw-material yards / the nights a Drop opens", "station", "everyone", "'Scrappers were at the fence by nine on Drop night.'"),
    ("to pull your set", "take the Wire set out of your car's dash before you leave it", "vehicles", "everyone", "'Pull your set, this is Solana Point.'"),
    ("the Pattern", "the Steward's board interface; also: the way things have to be done", "vehicles", "everyone", "'Body's on the Pattern, it'll fit.'"),
    ("Old Kettle", "the first people-made board (VY 371); any old thing that still works", "harrow_falls", "the Kettle Valley", "'My dad's an Old Kettle.'"),
    ("Deluge Week", "the Kettle Flood of VY 447", "station", "everyone", ""),
    ("the Flicker", "the Sunline's dimming of VY 498", "station", "everyone", ""),
]

SAYINGS = [
    ("'We are the Lakes, carried.'", "Ada Carrow at the launch; said at weddings and Returns"),
    ("'I remember a sky with nothing in it.' (Minnie's Line)", "the Last Earthborn; read at Returns"),
    ("'Every child a choice, every choice a share.'", "the Balance Act; now a school motto and a sour joke"),
    ("'North is where we're going.'", "comfort; a parent's answer to 'where are we going?'"),
    ("'The Steward'll sort it.'", "don't worry / nothing can be done"),
    ("'It's in the Balance.'", "it's fair / it's allowed"),
    ("'Leave the hatch be.'", "let sleeping dogs lie"),
    ("'Friday's fish.'", "some things don't change"),
    ("'Don't pull a Foxworth.'", "don't make things worse by helping"),
    ("'A Reyes finishes what a Reyes starts.'", "South Shore; about any job"),
    ("'Share and spare.'", "be generous; the Gift Supper toast"),
    ("'Earth's a long way back.'", "it's too late to change it"),
    ("'Third of the way.'", "since the Notice: it's going to take a while"),
    ("'The Sunline doesn't blink.' (before VY 498) / 'The Sunline blinked once.' (after)", "certainty / the end of certainty"),
    ("'Carrow-proud and Point-loud.'", "the north-south jibe"),
    ("'Every Friday a fry, every Sunday a pew.'", "the old Great Lakes week"),
    ("'Whatever you do, don't knock downstairs.'", "a children's rhyme"),
    ("'Bank luck and Balance keep you.'", "a wedding blessing"),
    ("'Go alone.'", "euchre: take the risk"),
    ("'Ope -- the Kettle's up.'", "trouble coming (since the Flood)"),
]

# what people believe about the voyage, the Steward and Earth (share of adults who hold it)
BELIEFS = [
    ("going_somewhere", "we're going to another world, a long way off", 0.72, "school, church, the Notice", "most people"),
    ("hesper_named", "the place is called Hesper (or 'the Far Shore')", 0.22, "school, Waymakers", "the schooled, Waymakers, the old"),
    ("alpha_centauri", "it's at a star called Alpha Centauri", 0.08, "the College, the Wardens' Library", "scholars"),
    ("third_done", "we're a third of the way there (the Notice)", 0.6, "the Notice", "since Launch Day VY 500"),
    ("voyage_is_home", "there is no destination; the ship is the world and always will be", 0.18, "unchurched cynicism, 'the Steward's just a machine'", "the young, the unchurched"),
    ("heaven_ship", "the Far Shore is Heaven and the voyage is the soul's road", 0.08, "Waymakers, some Full Gospel", "the faithful"),
    ("earth_gone", "Earth is gone (burned, drowned, or dead)", 0.35, "the Last Letter, the Heartbeat misunderstood", "many"),
    ("earth_fine", "Earth is still there and fine", 0.25, "the Heartbeat", "the schooled"),
    ("earth_calling", "Earth wants us back (the Green Message was true)", 0.04, "Homeward", "the Homeward"),
    ("steward_machine", "the Steward is a machine the founders built", 0.55, "school", "most"),
    ("steward_mind", "the Steward thinks and watches us", 0.3, "the Notice, children's lore", "rising since VY 500"),
    ("steward_god", "the Steward is God's hand", 0.05, "some Waymakers and Full Gospel", ""),
    ("someone_at_the_port", "people are living at the Port or in the Undercroft, running things", 0.12, "the Missing Eleven Hundred, Captain Blythe", "rumour"),
    ("imogen_alive", "Imogen Sato-Ferris is alive downstairs", 0.2, "the Bellhaven Dig", "the young, Bellhaven"),
    ("flicker_warning", "the Flicker was a warning that the ship is getting old", 0.3, "the Flicker", "the anxious"),
    ("notice_stunt", "the Notice was a stunt by the Quincentennial Commission", 0.1, "cynics", "Kessler cynics"),
    ("founders_chosen", "the founders were chosen as the best of Earth", 0.5, "the Launch Day story", "most"),
    ("buildings_from_earth", "the old buildings were brought from Earth", 0.4, "the pattern buildings misunderstood", "many"),
    ("snow_real", "snow was real and fell from the sky", 0.7, "grandmothers' stories", ""),
    ("snow_myth", "snow is a story, like dragons", 0.1, "children", "children under 10"),
]

SUPERSTITIONS = [
    ("tender_block", "never block a tender's path: bad luck for a year"),
    ("hatch_knock", "knocking on a sealed hatch wakes 'downstairs'; on Halloween it's a dare"),
    ("north_bed", "sleep with your head to the north for good dreams"),
    ("flicker_candle", "since VY 498 some keep a candle by the bed 'in case the Sunline blinks'"),
    ("share_letter_torn", "tear your Share Day letter's corner for luck; keep the corner in your wallet"),
    ("bank_sleeve", "touch a Bank-born person's sleeve before a game"),
    ("fish_on_friday", "no meat on Friday or the nets come up empty (fishing towns)"),
    ("launch_chair", "the empty chair at Launch Day dinner must not be sat in"),
    ("falls_coin", "throw a coin in the Falls pool for a safe year"),
    ("kettle_line", "don't build below the Flood Line"),
    ("dusk_hush", "don't whistle at the Sunline's dimming"),
    ("minnie_line", "say Minnie's Line when you pass a Return hall"),
]

ETIQUETTE = [
    ("bring_a_dish", "never arrive empty-handed; bring a dish or a six-pack of pop"),
    ("offer_three_times", "offer food three times; refuse twice before accepting (Midwest and Mexican manners agree)"),
    ("shoes_off", "shoes off indoors in most homes"),
    ("wave_to_drivers", "wave to drivers on the country roads (the one-finger wave)"),
    ("no_share_questions", "never ask why someone is childless"),
    ("thank_the_cook", "thank the cook by name at the fish fry"),
    ("church_clothes", "dress up for church and Returns"),
    ("steward_polite", "people say 'thank you' to the Boards, half joking"),
    ("goodbye_at_car", "walk your guests to their pod"),
    ("host_seconds", "the host eats last"),
]

TABOOS = [
    ("quiet_clause_talk", "arguing to turn the ship back (Charter art. 21): not illegal to say, but social suicide", 0.9),
    ("share_sale", "selling a share (a crime since VY 466)", 1.0),
    ("hatch_breaking", "breaking into the Undercroft (the Bellhaven Five are half heroes, half criminals)", 0.8),
    ("brandvold_praise", "praising Silas Brandvold in public", 0.7),
    ("wasting_water", "wasting water ('the Balance') -- running taps are scolded", 0.6),
    ("flood_joke", "joking about the Kettle Flood in Cedar Ford or Dunmore Crossing", 0.8),
    ("fever_joke", "joking about the Gray Fever near the old", 0.7),
    ("pike_in_tern", "a Pike in Tern Harbor", 0.9),
    ("soda", "saying 'soda' in Harrow Falls (a light taboo)", 0.1),
]

PASTIMES = [
    ("spinball", "spinball", "sport", "baseball adapted to the spin (VY 66): the diamond turned spinward, the curve part of the game; the Station League and the Spin Cup (since VY 201); every town has a team; high school spinball on Friday nights", 0.75),
    ("gridiron", "football (gridiron)", "sport", "high school football survives in the Northland; the long pass curves", 0.3),
    ("soccer", "soccer (fútbol)", "sport", "South Shore leagues", 0.35),
    ("hockey", "hockey", "sport", "indoor rinks in Port Carrow and Harrow Falls; no outdoor ice since the Last Snow", 0.15),
    ("bowling", "bowling", "sport", "leagues in every town; the lanes are social halls", 0.4),
    ("aerostat_racing", "aerostat racing", "sport", "Harrow Falls Aerodrome, the Kettle Cup", 0.3),
    ("sailing", "sailing and rowing", "sport", "the Regatta, the yacht clubs", 0.15),
    ("fishing", "fishing", "pastime", "from piers, boats and creek banks; derbies", 0.5),
    ("euchre", "euchre", "game", "the card game of the Great Lakes; leagues; the Station Euchre Championship", 0.55),
    ("cornhole", "cornhole", "game", "at every cookout", 0.45),
    ("bingo", "bingo", "game", "church halls, lodges", 0.3),
    ("dominoes", "dominoes", "game", "Freedom Baptist and Latino families", 0.2),
    ("lottery", "the Balance Lottery", "game", "a weekly draw run by the Commons Bank; charge stops and party stores", 0.35),
    ("arcades", "arcades", "game", "Brightwater's boardwalk", 0.25),
    ("gardening", "gardening", "pastime", "tomatoes and flowers; the best-kept yard prize", 0.45),
    ("fairs", "the fair and the midway", "pastime", "the Northland Fair, parish festivals", 0.6),
    ("radio_serials", "the Wire serials", "pastime", "'The Lamplighters', 'Morning with Uncle Barnaby', the spinball broadcasts", 0.8),
    ("polka", "polka and cumbia dancing", "pastime", "Saturday dances", 0.3),
    ("choirs", "church choirs and gospel", "pastime", "", 0.25),
    ("stargazing", "stargazing (the Bow Window)", "pastime", "impossible: there are no stars to see; the phrase means daydreaming", 0.0),
]

ARTS = [
    ("polka", "polka", "music", "Hedwig Hill, weddings, festivals: 'Minnie's Polka', 'The Launch Day Polka'"),
    ("cumbia", "cumbia and norteño", "music", "the South Shore; the Fiesta de Rosario"),
    ("gospel", "gospel", "music", "Freedom Baptist choirs; the Fenwick Mass Choir"),
    ("motown_revival", "'Detroit' sound", "music", "the founders' old records, still played; soul and doo-wop"),
    ("folk_ballads", "voyage ballads", "music", "'Carrow's Lamp', 'The Kettle Rising', 'Minnie's Sky', 'Third of the Way' (Estrella Vance-Nakamura, VY 500)"),
    ("hymns", "hymns", "music", "the Lakes Union Hymnal; 'Lead Us North' (a VY 150 hymn)"),
    ("radio_drama", "radio drama", "media", "'The Lamplighters' (Thursdays 19:30): a Port Carrow lighthouse family across the generations"),
    ("town_papers", "town papers", "media", "the Kessler Courier, the Carrow Lamp, the Solana Sun, the Falls Ledger, the Tern Tide"),
    ("book_of_the_lakes", "The Book of the Lakes", "book", "Agnes Szabó's VY 184 book of customs and recipes: every household has one"),
    ("charter_book", "the Charter", "book", "read aloud on Charter Day"),
    ("murals", "murals", "art", "the Moriarty mural, the Fever mural in Victory Bay, the Flood Line paintings"),
    ("quilts", "memory quilts", "craft", "made from the clothes of the Returned"),
]

DIALECT = {
    "base": "Inland Northern American English (the Great Lakes), levelled with the refuge's Southern American, African American and Latino Englishes over 500 years",
    "phonology": ["the Northern Cities Vowel Shift half-kept: 'bag' like 'beg-ag', 'lot' fronted", "Port Carrow and Tern Harbor: stronger shift, dropped /r/ in old speakers",
                  "South Shore: Spanish-influenced rhythm and vowels ('Point English')", "Haskins Corner and the countryside: Southern-flavoured drawl, 'y'all'",
                  "the young everywhere: a levelled 'Wire accent' from the radio"],
    "grammar": ["'needs washed' (Pittsburgh/Ohio)", "'anymore' meaning 'nowadays' in positive sentences ('Anymore everyone takes a stat')", "'come with' ('Do you want to come with?')",
                "'you guys' / 'youse' / 'y'all' plural", "Spanish tags on the South Shore ('¿verdad?', 'pues')"],
    "register": ["Kessler: formal, lawyerly", "Bellhaven: academic slang", "Port Carrow: clipped and proud", "Solana Point: loud, bilingual, fast"],
}

# what changed from the founders' Great Lakes ways, and why
CHANGES = [
    ("independence_day", "US Independence Day", "Charter Day (same date, the Charter read aloud)", "the US means nothing aboard; the date and the fireworks stayed"),
    ("memorial_day", "Memorial Day", "Return Day (all the voyage's dead; the summer opener)", "no wars; the Burn Fever gave it a new meaning"),
    ("dia_de_muertos", "Día de Muertos / All Souls", "Return Night, kept by everyone", "the Return rites and the refuge's Mexican families merged it"),
    ("deer_season", "the deer opener", "the Opener: a cabin week with no deer", "no deer aboard; the camp week survived"),
    ("snow", "winter snow, sledding, snow days", "Snow Night (paper snow), snow stories", "the Last Snow VY 212"),
    ("burial", "burial and cemeteries", "the Return: bodies to the soil cycle; memorial groves", "the Balance: no ground to spare; only Bishop Nowicki has a tomb"),
    ("baseball", "baseball", "spinball", "thrown balls curve in a spinning world"),
    ("stars", "stargazing, the night sky", "no stars; 'stargazing' means daydreaming; the Far Side overhead", "the cylinder has no windows people can reach"),
    ("family_size", "any number of children", "shares: about two per couple; gifted shares for big families", "the Balance Act VY 96"),
    ("car_culture", "gasoline cars, gas stations", "boards and bodies: Harrows, Carrows and Solanas on people's tube boards, trams and trucks on the Steward's; charge stops, cassette swaps, works loyalty like a team's", "everything is electric: the Steward's boards and people's LFP-cell boards"),
    ("dashboards", "screens and touch panels", "gauges and a Wire set in the slot", "the Steward makes few panels (the Panel Board rations them) and only the Thirty-Two"),
    ("hunting", "hunting", "fishing only", "no game animals"),
    ("lake_freighters", "Great Lakes freighters", "Kettle barges and the Ring Line", ""),
    ("national_identity", "American / Canadian / Mexican", "Columbian; town and family first", "five centuries aboard"),
    ("earth_news", "the news from everywhere", "the Wire: local news only; the Earth-link forgotten", "the Last Letter VY 391"),
    ("religion_denominations", "dozens of Protestant denominations", "the Lakes Union Church, Full Gospel, Freedom Baptist", "the VY 140 union"),
    ("catholic_rome", "Roman Catholic under Rome", "the Columbian Rite; married priests since VY 201", "too far to be ruled from Rome"),
    ("soda_pop", "regional words for soft drinks", "'pop' everywhere", "the Great Lakes word won"),
    ("money", "wages and rent, homelessness", "wages above the Draw; nobody homeless or hungry", "the Draw VY 284"),
    ("state_rivalries", "Ohio v. Michigan", "Port Carrow v. Solana Point; Mariners v. Suns", "the old rivalry's shape, new names"),
    ("fish_fry", "Lenten fish fry", "the fish fry every Friday all year", "fish is the station's plenty"),
    ("thanksgiving", "Thanksgiving", "kept almost unchanged", "the founders' first Thanksgiving aboard (VY 0) is its story"),
    ("euchre", "euchre", "kept, and bigger", "the game of the Lakes; nothing to replace it"),
    ("polka_cumbia", "separate ethnic musics", "polka and cumbia bands share stages; 'polkumbia' at weddings", "five centuries of intermarriage"),
    ("surnames", "father's surname", "either parent's surname; joined names common", "Charter art. 9"),
    ("north", "north is a compass direction", "north is the bow: 'where we're going'", "the ship has no poles"),
]

SCHOOLING = {
    "structure": "school from 5 to 18 in every town; Columbia College at Bellhaven for about one in six",
    "history_taught": ["Launch Day and Ada Carrow", "the Charter", "Tamsin, the first child", "the Burn Fever", "the Balance Act", "the Last Earthborn", "the Troubles and the Reconciliation",
                       "the Kettle Flood", "the Gray Fever"],
    "history_skipped": ["the Earth-link after VY 300", "how the station works", "where exactly the ship is going (taught as 'the Far Shore', a paragraph)", "the Returners' arguments"],
    "science": "biology, farming, fishing, chemistry of the kitchen, basic electricity; 'station science' (what the Steward does) as a list, not an explanation",
    "civics": "the Charter, the Assembly, the shares",
}
