"""Columbia game bible: the great families (lineages), the factions of VY 500, and the affinity
priors between them -- where two strangers' feelings start before they've met.

A lineage is a surname line and the family lore that travels with it. The engine gives a person
their lineage from their surname (NpcHouseholds pins it per household), and the lineage colours
them: family trades, faith, temperament tilts (small shifts on the Big Five means), what the
family is known for, what they won't forget. Minor lineages (every other surname a notable person
carries) are derived by make_bible.py from the people; every other surname aboard gets a small
generated lore from its heritage.

Affinity priors (-1..1): how members of one group feel about another's by default. The psychology
framework's opinion tokens start from these and move with events; see research/bible/09_affinity.md.
"""

def L(id, surname, founder, origin, heritage, strongholds, trades, faith, tilt, known_for, lore, members=(), feuds=(), allies=(), status="thriving",
      reputation="respected"):
    return dict(id=id, surname=surname, founder=founder, origin=origin, heritage=heritage, strongholds=strongholds, trades=list(trades), faith=faith,
                tilt=tilt, known_for=list(known_for), lore=list(lore), members=list(members), feuds=list(feuds), allies=list(allies), status=status,
                reputation=reputation)


LINEAGES = [
    L("carrow", "Carrow", "ada_carrow", "earth:cleveland", "anglo", {"port_carrow": 3, "haven_point": 1}, ["harbour pilot", "lawyer", "clerk"], "catholic",
      {"conscientiousness": 0.05, "extraversion": 0.03}, ["the first family", "harbour pilots", "the Carrow Lamp"],
      ["every Carrow child is toasted on Launch Day", "Carrows marry late and argue in public"], ["ada_carrow", "joseph_carrow"], allies=["okafor"], reputation="revered"),
    L("okafor", "Okafor", "chinedu_okafor", "earth:detroit", "african", {"port_carrow": 3, "port_tamsin": 2, "bellhaven": 1}, ["teacher", "dock worker", "spinball"], "catholic",
      {"warmth": 0.05, "openness": 0.03}, ["Tamsin's family", "teachers", "the Okafor twins"], ["an Okafor always has a story about Tamsin", "they name a daughter Tamsin once a generation"],
      ["chinedu_okafor", "tamsin_okafor_reyes", "ifeoma_okafor", "chidi_okafor", "tobias_wainwright_okafor"], allies=["reyes", "carrow"], reputation="beloved"),
    L("reyes", "Reyes", "tomas_reyes", "earth:toledo", "hispanic", {"solana_point": 3, "playa_verde": 2, "port_carrow": 1}, ["builder", "nurse", "boatbuilder"], "catholic",
      {"conscientiousness": 0.04, "extraversion": 0.04}, ["builders of the Point", "Tamsin's mother's people"], ["'a Reyes finishes what a Reyes starts'"],
      ["lucia_reyes", "tomas_reyes"], allies=["okafor", "solano"], reputation="respected"),
    L("solano", "Solano", "rosario_solano", "port_carrow", "hispanic", {"solana_point": 2, "playa_verde": 3}, ["teacher", "baker", "civic leader"], "catholic",
      {"extraversion": 0.06, "warmth": 0.04}, ["founders of the South Shore", "fiestas", "Plaza Solano"], ["the South Shore's first family; they host the Fiesta de Rosario every August"],
      ["rosario_solano", "itzel_solano_garza"], feuds=[("carrow", -0.1, "north v. south pride")], allies=["reyes", "arrieta"], reputation="revered"),
    L("harrow", "Harrow", "marcus_harrow", "earth:buffalo", "black_anglo", {"harrow_falls": 3}, ["engineer", "mill hand", "lock keeper"], "freedom_baptist",
      {"courage": 0.06}, ["the Falls", "the drowned hero"], ["a Harrow swims the Falls pool on their eighteenth birthday"], ["marcus_harrow"], reputation="hero"),
    L("marlowe", "Marlowe", "theo_marlowe", "earth:toledo", "anglo", {"marlowe": 3, "countryside": 2}, ["farmer", "elevator operator"], "lakes_union",
      {"agreeableness": 0.04, "openness": -0.04}, ["Northland farmers", "the Elevator"], ["Marlowes don't sell land"], ["theo_marlowe"], allies=["loomis", "lindqvist"]),
    L("villalobos", "Villalobos", "esperanza_villalobos", "earth:chicago", "hispanic", {"victory_bay": 2, "port_carrow": 1, "playa_verde": 1}, ["doctor", "nurse", "pharmacist"], "catholic",
      {"conscientiousness": 0.06, "warmth": 0.04}, ["healers", "the Fever saint's family (her sister's line)"], ["every Villalobos generation sends one child into medicine"],
      ["esperanza_villalobos"], reputation="revered"),
    L("moriarty", "Moriarty", "finnegan_moriarty", "earth:erie", "irish_scots", {"tern_harbor": 3, "pelican_cove": 1}, ["fisher", "dock worker", "union organiser"], "catholic",
      {"extraversion": 0.05, "agreeableness": -0.05, "courage": 0.05}, ["Tern Harbor's fighters", "the Forty Days"], ["'a Moriarty never crosses a picket line, even a wrong one'"],
      ["finnegan_moriarty", "declan_moriarty", "siobhan_moriarty"], feuds=[("castellanos", -0.6, "the strike and the closure"), ("pike", -0.6, "the closure")],
      allies=["dunmore", "pham"], reputation="hero"),
    L("kowalczyk", "Kowalczyk", "minnie_kowalczyk", "earth:hamtramck", "polish", {"fenwick": 3, "port_carrow": 1}, ["seamstress", "machinist", "pastor"], "catholic",
      {"humour": 0.06, "warmth": 0.04}, ["the Last Earthborn's family", "900 descendants"], ["every Kowalczyk wedding plays 'Minnie's Polka'"],
      ["minnie_kowalczyk", "clarence_kowalczyk_booker"], allies=["booker"], reputation="beloved"),
    L("yoder", "Yoder", "jonas_yoder", "marlowe", "german", {"tamarack": 4, "countryside": 2}, ["farmer", "cheesemaker", "furniture maker"], "plain",
      {"conscientiousness": 0.06, "extraversion": -0.05, "openness": -0.05}, ["the Plain families", "Tamarack Blue cheese", "big families (gifted shares)"],
      ["they don't ride pods; they walk or use a pony cart", "cousins gift shares so the Yoders stay many"], ["jonas_yoder", "amos_yoder_stoltz", "ezra_yoder"], reputation="respected"),
    L("decarlo", "DeCarlo", "salvatore_decarlo", "harrow_falls", "italian", {"brightwater": 3}, ["arcade owner", "shopkeeper", "showman"], "catholic",
      {"extraversion": 0.07, "conscientiousness": -0.04}, ["the Boardwalk", "DeCarlo's Arcade"], ["'a DeCarlo can sell sand on the beach'"], ["salvatore_decarlo", "vinnie_decarlo"]),
    L("merriweather", "Merriweather", "otis_merriweather", "harrow_falls", "black_anglo", {"harrow_falls": 2}, ["teacher", "coach"], "freedom_baptist",
      {"humour": 0.05}, ["spinball's inventors"], ["the Merriweather Trophy is presented by a Merriweather"], ["otis_merriweather"], reputation="beloved"),
    L("osei", "Osei", "harriet_osei_lindqvist", "kessler", "african", {"kessler": 2, "port_carrow": 1}, ["lawyer", "clerk", "politician"], "lakes_union",
      {"conscientiousness": 0.05}, ["the Balance Act", "Moderators"], ["'the family that counted the babies'"], ["harriet_osei_lindqvist", "winifred_osei"], reputation="contested"),
    L("achterberg", "Achterberg", "wendell_achterberg", "marlowe", "dutch", {"kessler": 3, "marlowe": 1}, ["pastor", "lawyer", "politician"], "lakes_union",
      {"conscientiousness": 0.05, "openness": -0.03}, ["Lakes Union pastors", "the Moderator's family"], ["Achterbergs go into the Church or the Assembly"],
      ["wendell_achterberg", "rosalind_achterberg_nunez", "margaret_achterberg_voss"], feuds=[("wainwright", -0.3, "politics")]),
    L("raghunathan", "Raghunathan", "priya_raghunathan", "bellhaven", "south_asian", {"bellhaven": 3}, ["teacher", "scholar", "doctor"], "dharmic",
      {"openness": 0.07, "curiosity": 0.07}, ["the College's founders", "scholars"], ["a Raghunathan always has a question"], ["priya_raghunathan", "anjali_raghunathan_cole"], allies=["holloway"]),
    L("nowicki", "Nowicki", "casimir_nowicki", "port_carrow", "polish", {"port_carrow": 2, "fenwick": 1}, ["priest", "organist", "teacher"], "catholic",
      {"conscientiousness": 0.04, "openness": -0.03}, ["bishops", "the Cathedral"], ["two bishops in five centuries"], ["casimir_nowicki", "teodoro_nowicki_ramos"], reputation="revered"),
    L("szabo", "Szabo", "agnes_szabo", "harrow_falls", "hungarian", {"harrow_falls": 2}, ["librarian", "teacher", "baker"], "catholic",
      {"openness": 0.04}, ["'The Book of the Lakes'", "paprikash"], ["the Szabó Christmas is the Harrow Falls Christmas"], ["agnes_szabo"]),
    L("foxworth", "Foxworth", "gerald_foxworth", "marlowe", "anglo", {"marlowe": 2}, ["farmer"], "lakes_union", {"conscientiousness": -0.03},
      ["the Fox Year"], ["every Foxworth has heard every fox joke", "they are, in fact, careful people"], ["gerald_foxworth"], reputation="notorious"),
    L("brandvold", "Brandvold", "silas_brandvold", "marlowe", "scandinavian", {"marlowe": 1, "countryside": 1}, ["farmer"], "lakes_union",
      {"agreeableness": -0.04}, ["the Returners' leader"], ["few Brandvolds are left by name; most took other names after VY 270", "some Northland families keep his picture turned to the wall, some face out"],
      ["silas_brandvold"], feuds=[("kowal", -0.5, "the Stern Breach")], status="dwindled", reputation="villain"),
    L("kowal", "Kowal", "thaddeus_kowal", "fenwick", "polish", {"fenwick": 2, "kessler": 1}, ["mechanic", "machinist", "marshal"], "catholic",
      {"courage": 0.06, "conscientiousness": 0.04}, ["the Breach hero", "the Kowal Medal"], ["a Kowal presents the Kowal Medal each year"], ["thaddeus_kowal"],
      feuds=[("brandvold", -0.5, "the Stern Breach")], reputation="hero"),
    L("desai", "Desai", "rukmini_desai", "kessler", "south_asian", {"kessler": 2}, ["marshal", "lawyer"], "dharmic", {"conscientiousness": 0.05, "warmth": -0.03},
      ["the Marshal-General of the Troubles"], ["Desais still serve in the Marshals"], ["rukmini_desai"], reputation="contested"),
    L("adebayo", "Adebayo", "josephine_adebayo_ruiz", "solana_point", "african", {"solana_point": 1, "kessler": 2}, ["lawyer", "mediator", "clergy"], "catholic",
      {"agreeableness": 0.06, "warmth": 0.05}, ["the Reconciler"], ["peacemakers: families call an Adebayo to settle a feud"], ["josephine_adebayo_ruiz"], reputation="revered"),
    L("castellanos", "Castellanos", "raymundo_castellanos", "pelican_cove", "hispanic", {"pelican_cove": 2, "port_carrow": 1}, ["cannery owner", "shipper", "banker"], "catholic",
      {"conscientiousness": 0.04, "agreeableness": -0.04}, ["Castellanos-Pike Canning", "money"], ["'share-rich' since Raymundo"], ["raymundo_castellanos", "gwendolyn_pike_younger", "thanh_nguyen_castellanos"],
      feuds=[("moriarty", -0.6, "the strike and the closure"), ("pham", -0.3, "the union")], allies=["pike"], reputation="contested"),
    L("pike", "Pike", "gwendolyn_pike", "tern_harbor", "anglo", {"pelican_cove": 1, "port_carrow": 1, "tern_harbor": 1}, ["cannery owner", "accountant"], "lakes_union",
      {"conscientiousness": 0.06, "warmth": -0.04}, ["the closure of Tern Harbor"], ["no Pike has lived in Tern Harbor since VY 471"], ["gwendolyn_pike", "gwendolyn_pike_younger"],
      feuds=[("moriarty", -0.6, "the closure")], allies=["castellanos"], reputation="villain"),
    L("dunmore", "Dunmore", "maeve_dunmore_elder", "marlowe", "irish_scots", {"dunmore_crossing": 3, "pelican_cove": 1}, ["depot master", "driver", "union organiser"], "catholic",
      {"agreeableness": 0.03}, ["the Crossing", "the Union's founder"], ["a Dunmore keeps the depot clock"], ["maeve_dunmore_elder", "maeve_dunmore", "fergus_dunmore"], allies=["moriarty"]),
    L("delmar", "Delmar", "hector_delmar", "pelican_cove", "hispanic", {"pelican_cove": 2}, ["cannery owner", "fisher"], "catholic", {"neuroticism": 0.04},
      ["the Delmar fire"], ["the family eats Christmas dinner with the doors locked"], ["hector_delmar"], feuds=[("pham", -0.5, "the fire and the union")], reputation="contested"),
    L("pham", "Pham", "maeve_dunmore", "pelican_cove", "se_asian", {"pelican_cove": 3, "solana_point": 1}, ["dock worker", "union organiser", "cook"], "catholic",
      {"conscientiousness": 0.04, "courage": 0.04}, ["the Union", "pho on Cannery Row"], ["Maeve Dunmore married Sean Pham: the Union has had a Pham in it since"],
      ["rosa_pham_moriarty"], feuds=[("delmar", -0.5, "the fire"), ("castellanos", -0.3, "the union")], allies=["moriarty", "dunmore"]),
    L("mbeki", "Mbeki", "dot_mbeki", "victory_bay", "african", {"victory_bay": 2, "oceanview": 1}, ["nurse", "teacher", "preacher"], "freedom_baptist",
      {"extraversion": 0.04, "warmth": 0.04}, ["Dot, the oldest", "the Waymakers' founder"], ["long lives: four centenarians"], ["dot_mbeki", "evangeline_mbeki_hart"]),
    L("wainwright", "Wainwright", "tobias_wainwright_okafor", "bellhaven", "anglo", {"bellhaven": 2}, ["lawyer", "teacher"], "lakes_union", {"openness": 0.05},
      ["the Open Hand"], ["argue at dinner as sport"], ["tobias_wainwright_okafor"], feuds=[("achterberg", -0.3, "politics")]),
    L("duquesne", "Duquesne", "harlan_duquesne", "kessler", "francophone", {"kessler": 1, "oceanview": 1}, ["lawyer", "politician"], "lakes_union",
      {"agreeableness": -0.03}, ["the Share Scandal"], ["the younger Duquesnes go by their mothers' names"], ["harlan_duquesne"],
      feuds=[("ostrowski", -0.4, "the exposure")], status="dwindled", reputation="notorious"),
    L("ostrowski", "Ostrowski", "wilhelm_ostrowski", "fenwick", "polish", {"kessler": 1, "fenwick": 1}, ["editor", "printer"], "catholic", {"conscientiousness": 0.04},
      ["the Kessler Courier"], ["newspaper people for four generations"], ["wilhelm_ostrowski"], feuds=[("duquesne", -0.4, "the exposure")]),
    L("stroud", "Stroud", "juniper_stroud", "harrow_falls", "anglo", {"harrow_falls": 2}, ["aerostat pilot", "mechanic"], "none", {"courage": 0.07},
      ["aerostat racers"], ["three generations of champions"], ["juniper_stroud", "linnet_okoye_stroud"]),
    L("arrieta", "Arrieta", "consuelo_arrieta", "playa_verde", "hispanic", {"playa_verde": 2, "solana_point": 2}, ["baker", "developer", "shopkeeper"], "catholic",
      {"extraversion": 0.05}, ["La Estrella bakery", "Lucky Luis"], ["Mamá Chelo's conchas at every Arrieta wedding"], ["consuelo_arrieta", "luis_arrieta_wu"], allies=["solano"]),
    L("holloway", "Holloway", "beatriz_holloway_anand", "port_carrow", "anglo", {"port_carrow": 1, "kessler": 1, "bellhaven": 1}, ["clerk", "librarian", "organiser"], "catholic",
      {"openness": 0.04}, ["the Quincentennial", "the Bellhaven Five"], ["Holloways end up running things"], ["beatriz_holloway_anand", "caspian_holloway"], allies=["raghunathan"]),
    L("haskins", "Haskins", "eli_haskins", "fenwick", "black_anglo", {"haskins_corner": 3}, ["shopkeeper", "cook", "driver"], "full_gospel", {"extraversion": 0.04},
      ["the Corner", "the Corner Diner"], ["the Haskins pie recipe is a family secret"], ["eli_haskins", "lamar_haskins"]),
    L("loomis", "Loomis", "abigail_loomis", "marlowe", "anglo", {"loomis_grove": 3}, ["orchardist", "cider maker"], "lakes_union", {"agreeableness": 0.04},
      ["the orchards", "cider"], ["the first cider of the year goes to the Return hall"], ["abigail_loomis", "harold_loomis_petrie"], allies=["marlowe"]),
    L("pruett", "Pruett", "hollis_pruett", "kessler", "anglo", {"pruett": 3}, ["surveyor", "shopkeeper", "farmer"], "lakes_union", {"extraversion": -0.04},
      ["Pruett"], ["'we're all Amos's'"], ["hollis_pruett", "ruth_ann_pruett_doyle"]),
    L("booker", "Booker", "jerome_booker", "fenwick", "black_anglo", {"fenwick": 3}, ["pastor", "teacher", "machinist"], "freedom_baptist", {"extraversion": 0.04, "warmth": 0.03},
      ["Mount Zion", "the Freedom Baptist Convention"], ["Booker women run the church suppers"], ["jerome_booker", "clarence_kowalczyk_booker"], allies=["kowalczyk"]),
    L("tomczak", "Tomczak", "walt_tomczak", "harrow_falls", "polish", {"harrow_falls": 2}, ["bartender", "cook"], "catholic", {"humour": 0.04},
      ["Tomczak's Tavern fish fry"], ["the batter recipe is never written down"], ["walt_tomczak"]),
    L("wisniewski", "Wisniewski", "frankie_wisniewski", "port_carrow", "polish", {"port_carrow": 2}, ["musician", "bartender"], "catholic", {"extraversion": 0.05},
      ["Hedwig Hill polka"], ["a Wiśniewski plays at every Hedwig Hill wedding"], ["frankie_wisniewski"]),
    L("okonkwo", "Okonkwo", "dante_okonkwo_silva", "solana_point", "african", {"solana_point": 2}, ["spinball", "teacher"], "catholic", {"extraversion": 0.04},
      ["Dante"], ["spinball family"], ["dante_okonkwo_silva"]),
    L("brannock", "Brannock", "ezekiel_brannock", "port_carrow", "irish_scots", {"port_carrow": 2}, ["dock worker", "spinball"], "catholic", {"courage": 0.04},
      ["the Mariners' captain", "Brannock Pike (named for an ancestor surveyor)"], ["the Pike's name is theirs, they say"], ["ezekiel_brannock"]),
    L("haddad", "Haddad", "nadia_haddad", "port_carrow", "arab", {"port_carrow": 2, "kessler": 1}, ["doctor", "shopkeeper", "baker"], "muslim", {"conscientiousness": 0.04},
      ["the Carrow Masjid", "the bakery on King Street"], ["Haddad and Bazzi have intermarried since the Filling"], ["nadia_haddad", "yusuf_haddad_bazzi"], allies=["bazzi"]),
    L("bazzi", "Bazzi", "yusuf_haddad_bazzi", "port_carrow", "arab", {"port_carrow": 2}, ["shopkeeper", "imam", "cook"], "muslim", {"warmth": 0.04},
      ["shawarma on King Street"], [], ["yusuf_haddad_bazzi"], allies=["haddad"]),
    L("tremblay", "Tremblay", None, "earth:windsor", "francophone", {"port_carrow": 3, "tern_harbor": 1}, ["baker", "fisher", "singer"], "catholic", {"humour": 0.04},
      ["the Côte's biggest family", "tourtière at Christmas"], ["half the Côte is a Tremblay cousin"], ["colette_marchand"], allies=["leclerc", "marchand"]),
    L("leclerc", "Leclerc", "augustin_leclerc", "port_carrow", "francophone", {"port_carrow": 2}, ["lawyer", "teacher"], "catholic", {"conscientiousness": 0.03},
      ["a Moderator", "the Côte Society"], [], ["augustin_leclerc"], allies=["tremblay"]),
    L("nguyen", "Nguyen", None, "earth:chicago", "se_asian", {"pelican_cove": 3, "solana_point": 2}, ["fisher", "cook", "dock worker", "shopkeeper"], "dharmic",
      {"conscientiousness": 0.04}, ["Little Saigon Row", "the Cove's mayor"], ["the Nguyen New Year feast feeds the whole Row"], ["thanh_nguyen_castellanos"], allies=["pham"]),
    L("patel", "Patel", None, "earth:chicago", "south_asian", {"kessler": 2, "bellhaven": 2, "solana_point": 1}, ["pharmacist", "shopkeeper", "hotel keeper", "doctor"], "dharmic",
      {"conscientiousness": 0.05}, ["pharmacies and motels"], ["the biggest surname in Bellhaven"], []),
    L("garcia", "Garcia", None, "earth:toledo", "hispanic", {"solana_point": 2, "playa_verde": 2, "port_carrow": 1}, ["every trade"], "catholic", {},
      ["everywhere"], ["'there's always a Garcia who knows a Garcia'"], []),
    L("smith", "Smith", None, "earth:cleveland", "anglo", {"kessler": 1, "port_carrow": 1, "marlowe": 1}, ["every trade"], "lakes_union", {},
      ["everywhere"], ["the commonest name aboard"], []),
]

# canon-anchored surname bearers in 2752 (the lore needs these families to be as big as it says;
# the simulated counts are replaced for these surnames -- make_bible.py)
BEARERS_2752 = {"carrow": 180, "okafor": 140, "solano": 220, "harrow": 120, "marlowe": 160, "villalobos": 90, "moriarty": 210, "kowalczyk": 380,
                "yoder": 640, "decarlo": 150, "merriweather": 70, "osei": 90, "achterberg": 110, "raghunathan": 70, "nowicki": 120, "szabo": 110,
                "foxworth": 60, "brandvold": 12, "kowal": 90, "adebayo": 80, "castellanos": 170, "pike": 60, "dunmore": 140, "delmar": 60, "mbeki": 70,
                "wainwright": 90, "duquesne": 15, "ostrowski": 80, "stroud": 60, "arrieta": 110, "holloway": 90, "haskins": 120, "loomis": 140,
                "pruett": 180, "booker": 160, "tomczak": 70, "wisniewski": 150, "okonkwo": 70, "brannock": 90, "haddad": 180, "bazzi": 150, "leclerc": 90}

FACTIONS = [
    dict(id="charter_league", kind="political", name="the Charter League", holds=["the Balance as it is", "leave the Undercroft closed", "the Quiet Clause kept", "order and thrift"],
         strong_in={"kessler": 1.5, "marlowe": 1.5, "oceanview": 1.4, "tamarack": 1.4, "countryside": 1.3, "victory_bay": 1.3},
         draws={"age_over": 45, "V.tradition": 1.5, "V.order": 1.5, "faith": ["lakes_union", "catholic", "plain"]}, share=0.34,
         leaders=["rosalind_achterberg_nunez"], seats_vy496=52),
    dict(id="open_hand", kind="political", name="the Open Hand", holds=["freer gifting of shares", "an inquiry into the Undercroft", "petition the Steward", "answer the Notice"],
         strong_in={"bellhaven": 1.8, "solana_point": 1.4, "port_carrow": 1.2, "cedar_ford": 1.5, "brightwater": 1.2},
         draws={"age_under": 45, "V.freedom": 1.5, "V.truth": 1.5, "faith": ["waymakers", "none"]}, share=0.31, leaders=["tobias_wainwright_okafor"], seats_vy496=49),
    dict(id="grange", kind="guild", name="the Northland Grange", holds=["farmers first", "fair prices at the Chutes", "the Northland Fair"],
         strong_in={"marlowe": 2.0, "loomis_grove": 2.0, "dunmore_crossing": 1.5, "fenwick": 1.2, "countryside": 2.0, "tamarack": 1.5}, draws={"occupation": ["farmer", "farmhand"]},
         share=0.05, leaders=["gunnar_lindqvist_brandt"]),
    dict(id="cannery_union", kind="guild", name="the Cannery and Dock Workers Union", holds=["jobs on the water", "never forget Tern Harbor", "no locked doors"],
         strong_in={"pelican_cove": 2.5, "tern_harbor": 2.5, "port_carrow": 1.3, "solana_point": 1.1}, draws={"occupation": ["dock_worker", "fisher", "factory_hand"]},
         share=0.04, leaders=["rosa_pham_moriarty"]),
    dict(id="order_of_the_lamp", kind="club", name="the Order of the Lamp", holds=["charity", "the Friday fish fry", "a good Return for every member"],
         strong_in={"port_carrow": 1.5, "harrow_falls": 1.3, "fenwick": 1.2}, draws={"age_over": 40, "V.community": 1.5}, share=0.07, leaders=["frankie_wisniewski"]),
    dict(id="daughters_of_the_launch", kind="club", name="the Daughters and Sons of the Launch", holds=["founder descent", "the Launch Day rites", "keeping the old stories"],
         strong_in={"port_carrow": 1.5, "kessler": 1.4, "victory_bay": 1.5}, draws={"lineage_founder": True, "age_over": 50}, share=0.02, leaders=["beatriz_holloway_anand"]),
    dict(id="waymakers_assembly", kind="faith", name="the Waymakers", holds=["the voyage is the pilgrimage", "the Notice is a sign", "ask where we're going"],
         strong_in={"bellhaven": 1.6, "oceanview": 1.8, "cedar_ford": 1.4, "solana_point": 1.2}, draws={"faith": ["waymakers"]}, share=0.06, leaders=["evangeline_mbeki_hart", "tobit_asante_grey"]),
    dict(id="wardens_circle", kind="society", name="the Wardens' Library circle", holds=["learn how the station works", "find Imogen", "open the Undercroft"],
         strong_in={"bellhaven": 3.0, "kessler": 1.2}, draws={"occupation": ["university_student", "librarian", "teacher", "mechanic"], "P.openness": 1.5}, share=0.004,
         leaders=["caspian_holloway"], secret=True),
    dict(id="homeward", kind="society", name="the Homeward (Returner remnant)", holds=["Earth is home", "the Green Message was true", "the Steward stole the vote"],
         strong_in={"marlowe": 1.5, "countryside": 1.3, "tern_harbor": 1.2}, draws={"lineage": ["brandvold"], "V.home": 1.5}, share=0.002, leaders=[], secret=True, taboo=True),
    dict(id="aerostat_guild", kind="guild", name="the Aerostat Pilots' Guild", holds=["the air is free", "racing", "safety rules (after VY 438)"],
         strong_in={"harrow_falls": 3.0, "solana_point": 1.4}, draws={"occupation": ["mechanic"], "P.courage": 1.5}, share=0.006, leaders=["kaz_horvath"]),
    dict(id="mariners_faithful", kind="fans", name="the Mariners Faithful", holds=["the Port Carrow Mariners"], strong_in={"port_carrow": 4.0, "haven_point": 2.0, "tern_harbor": 2.0, "brightwater": 1.5},
         draws={}, share=0.15, leaders=["ezekiel_brannock"]),
    dict(id="suns_nation", kind="fans", name="Suns Nation", holds=["the Solana Point Suns"], strong_in={"solana_point": 4.0, "playa_verde": 2.5, "pelican_cove": 2.0, "oceanview": 1.2},
         draws={}, share=0.16, leaders=["dante_okonkwo_silva"]),
    dict(id="heritage_hedwig", kind="heritage", name="the Hedwig Hill Polish Society", holds=["Pączki Day", "Dyngus Day", "polka"], strong_in={"port_carrow": 2.0, "fenwick": 2.0, "harrow_falls": 1.3},
         draws={"heritage": ["polish", "slavic"]}, share=0.02, leaders=["frankie_wisniewski"]),
    dict(id="heritage_cote", kind="heritage", name="the Côte Society", holds=["Carrow French", "Saint-Jean-Baptiste Day", "tourtière"], strong_in={"port_carrow": 3.0, "tern_harbor": 1.5},
         draws={"heritage": ["francophone"]}, share=0.015, leaders=["colette_marchand"]),
    dict(id="heritage_sociedad", kind="heritage", name="la Sociedad Solano", holds=["Lake Spanish", "the Fiesta de Rosario", "Día de Muertos / Return Night"],
         strong_in={"playa_verde": 3.0, "solana_point": 2.0, "pelican_cove": 1.5}, draws={"heritage": ["hispanic"]}, share=0.05, leaders=["itzel_solano_garza"]),
    dict(id="marshals", kind="institution", name="the Marshals Service", holds=["order", "rescue", "the Charter"], strong_in={"kessler": 2.0}, draws={"occupation": ["police", "firefighter"]},
         share=0.004, leaders=["obadiah_kincaid_morales"]),
]

# default feelings between groups (symmetric unless listed twice); -1 hostile .. +1 warm
FACTION_AFFINITY = [
    ("charter_league", "open_hand", -0.35), ("charter_league", "waymakers_assembly", -0.2), ("charter_league", "wardens_circle", -0.4),
    ("charter_league", "homeward", -0.6), ("charter_league", "grange", 0.3), ("charter_league", "daughters_of_the_launch", 0.4),
    ("charter_league", "marshals", 0.35), ("open_hand", "waymakers_assembly", 0.25), ("open_hand", "wardens_circle", 0.35),
    ("open_hand", "cannery_union", 0.2), ("open_hand", "marshals", -0.1), ("open_hand", "homeward", -0.3),
    ("waymakers_assembly", "wardens_circle", 0.15), ("waymakers_assembly", "homeward", -0.4), ("wardens_circle", "marshals", -0.3),
    ("cannery_union", "grange", 0.15), ("cannery_union", "marshals", -0.15), ("order_of_the_lamp", "daughters_of_the_launch", 0.3),
    ("order_of_the_lamp", "cannery_union", 0.15), ("mariners_faithful", "suns_nation", -0.45), ("heritage_hedwig", "order_of_the_lamp", 0.3),
    ("heritage_cote", "heritage_hedwig", 0.2), ("heritage_sociedad", "suns_nation", 0.3), ("heritage_hedwig", "mariners_faithful", 0.3),
    ("heritage_cote", "mariners_faithful", 0.3), ("aerostat_guild", "marshals", -0.1), ("homeward", "marshals", -0.5),
]

# regional feelings (beyond the settlements' own rivals/allies): the north-south pride, the capital, the shore and the farms
REGION_AFFINITY = [
    ("north_shore", "south_shore", -0.15), ("northland", "southland", -0.05), ("kettle_valley", "northland", 0.1), ("kettle_valley", "southland", 0.1),
    ("north_shore", "northland", 0.05), ("south_shore", "southland", 0.05),
]
SETTLEMENT_RIVALRY = -0.3        # the settlements' own 'rivals'
SETTLEMENT_ALLIANCE = 0.2        # and 'allies'
FAITH_AFFINITY = [
    ("catholic", "lakes_union", 0.1), ("catholic", "full_gospel", -0.05), ("full_gospel", "waymakers", -0.35), ("catholic", "waymakers", -0.15),
    ("lakes_union", "waymakers", -0.1), ("none", "full_gospel", -0.15), ("none", "waymakers", 0.05), ("freedom_baptist", "full_gospel", 0.1),
    ("plain", "none", -0.1), ("muslim", "jewish", 0.1), ("muslim", "catholic", 0.05),
]
