"""Columbia game bible: important people, from the Earth-side founders of the Compact to the living
notables of VY 500. Each is a record the engine can use: as history (what people know of them), as
ancestry (lineages, reputation passed down), and -- for the living -- as pinned characters placed
in the world (home, occupation, age, sex, family, faith, temperament).

Fields
  id, given, surname (a joined surname lists both lines), sex F/M, born_vy, died_vy (None = alive in
  VY 500; 'missing' = disappeared), birthplace (settlement id, or 'earth:<city>'),
  origin: earth_side (never aboard) | founder (Earth-born voyager, an immigrant) | station (born
  aboard, a native) | bank (born aboard from the Ark Bank's embryos, a native),
  moved_to (settlement ids they later lived in: internal migrants), home (settlement at death / now),
  occupation (engine occupation id, npc_traits.json) and title, roles (research/roles ids),
  lineages (lineage ids), marital: married | widowed | divorced | never_married | partnered,
  spouse (person id or a short description), children (count), childless (reason if 0):
  gave_share | vocation | chose_not | infertility | died_young | partner_died | duty | protest | share_lapsed |
  unknown, faith (WORLD faith id), traits (psychology-style tokens), reputation:
  revered | hero | beloved | respected | contested | notorious | villain | forgotten | private,
  fame (0-1, how widely known in VY 500), deeds (event ids), memorials, notes.
"""

def P(id, given, surname, sex, born, died, birthplace, origin, home, occupation, title, lineages, marital, spouse, children,
      childless=None, faith="none", traits=(), reputation="respected", fame=0.3, deeds=(), memorials=(), moved_to=(), roles=(), notes=()):
    return dict(id=id, given=given, surname=surname, sex=sex, born_vy=born, died_vy=died, birthplace=birthplace, origin=origin, home=home,
                occupation=occupation, title=title, lineages=list(lineages), marital=marital, spouse=spouse, children=children,
                childless=childless if children == 0 else None, faith=faith, traits=list(traits), reputation=reputation, fame=fame,
                deeds=list(deeds), memorials=list(memorials), moved_to=list(moved_to), roles=list(roles), notes=list(notes))


PEOPLE = [
    # ------------------------------------------------------------------ Earth-side (never aboard)
    P("ingrid_kessler", "Ingrid", "Kessler", "F", -91, -3, "earth:toledo", "earth_side", "earth", None, "Director-General of the Compact", ["kessler"],
      "married", "Anton Kessler (Earth)", 2, faith="lakes_union", traits=["P.conscientiousness:very_high", "P.warmth:high", "V.duty"], reputation="revered", fame=0.55,
      deeds=["compact_founded", "columbia_design"], memorials=["the town of Kessler", "the Kessler Window in the Assembly Hall"],
      notes=["died three years before launch; 'the Mother who stayed behind'", "her two children stayed on Earth"]),
    P("henrik_aaltonen", "Henrik", "Aaltonen", "M", -82, -8, "earth:helsinki", "earth_side", "earth", None, "chief engineer of the drive (ESA)", ["aaltonen"],
      "married", "Kaisa Aaltonen (Earth)", 3, traits=["P.openness:high"], reputation="forgotten", fame=0.03, deeds=["columbia_design"],
      notes=["his daughter Liisa went aboard; he never saw her again"]),
    P("amara_nwosu", "Amara", "Nwosu", "F", -64, 11, "earth:chicago", "earth_side", "earth", None, "designer of the Habitat Autonomy System (the Steward)", ["nwosu"],
      "never_married", None, 0, childless="chose_not", traits=["P.openness:very_high", "P.extraversion:low"], reputation="forgotten", fame=0.02,
      deeds=["steward_commissioned"], notes=["'the Steward was her child', her colleagues said", "wrote the Long Clause: a three-thousand-year service life"]),
    # ------------------------------------------------------------------ the Burn: founders (Earth-born voyagers)
    P("ada_carrow", "Ada", "Carrow", "F", -51, 38, "earth:cleveland", "founder", "port_carrow", None, "Captain-Governor; first Moderator", ["carrow"],
      "married", "Joseph Carrow (founder, harbour pilot)", 3, faith="catholic", traits=["P.conscientiousness:very_high", "P.courage:high", "V.duty", "V.community"],
      reputation="revered", fame=0.9, deeds=["launch", "charter_signed", "first_assembly"], memorials=["Port Carrow", "Carrow Pike", "the Carrow Lamp", "Launch Day toast 'To Ada'"],
      roles=["leader_task", "founder"], notes=["'We are the Lakes, carried'", "a Great Lakes ore-boat captain's daughter; a shipyard manager before the Selection"]),
    P("liisa_aaltonen", "Liisa", "Aaltonen", "F", -38, 61, "earth:helsinki", "founder", "bellhaven", None, "Chief Warden", ["aaltonen"],
      "never_married", None, 0, childless="vocation", traits=["P.conscientiousness:very_high", "P.agreeableness:low", "V.competence"], reputation="respected", fame=0.15,
      deeds=["launch", "coasting_day"], memorials=["Aaltonen Hall, Columbia College"], moved_to=["port_carrow"], roles=["engineer", "founder"],
      notes=["one of 140 Europeans aboard; learned English in the yard", "'married to the drive'; gave her share to the Wardens' fund for orphans"]),
    P("joseph_carrow", "Joseph", "Carrow", "M", -53, 33, "earth:cleveland", "founder", "port_carrow", None, "harbour pilot; husband of Ada Carrow", ["carrow"],
      "married", "ada_carrow", 3, faith="catholic", reputation="forgotten", fame=0.05),
    P("marcus_harrow", "Marcus", "Harrow", "M", -30, 3, "earth:buffalo", "founder", "harrow_falls", None, "water engineer", ["harrow"],
      "married", "Ruth Harrow (founder)", 1, faith="freedom_baptist", traits=["P.courage:very_high"], reputation="hero", fame=0.45,
      deeds=["falls_accident"], memorials=["Harrow Falls", "the Harrow Stone at the Falls"], notes=["his son Marcus Jr. was born four months after he died"]),
    P("theo_marlowe", "Theodore", "Marlowe", "M", -43, 49, "earth:toledo", "founder", "marlowe", None, "farmer; leader of the Northland farms", ["marlowe"],
      "married", "Greta Marlowe (founder)", 4, faith="lakes_union", traits=["P.agreeableness:high", "V.tradition"], reputation="respected", fame=0.25,
      memorials=["the town of Marlowe"], roles=["farmer", "founder"]),
    P("chinedu_okafor", "Chinedu", "Okafor", "M", -27, 58, "earth:detroit", "founder", "port_carrow", None, "teacher", ["okafor"],
      "married", "lucia_reyes", 3, faith="catholic", reputation="forgotten", fame=0.1, notes=["father of Tamsin Okafor-Reyes"]),
    P("lucia_reyes", "Lucía", "Reyes", "F", -25, 66, "earth:toledo", "founder", "port_carrow", None, "nurse", ["reyes"],
      "married", "chinedu_okafor", 3, faith="catholic", reputation="forgotten", fame=0.1, notes=["mother of Tamsin Okafor-Reyes"]),
    P("tamsin_okafor_reyes", "Tamsin", "Okafor-Reyes", "F", 0, 91, "port_carrow", "station", "port_tamsin", None, "teacher", ["okafor", "reyes"],
      "widowed", "Aurelio Bianchi (m. VY 21, d. VY 60); then Samuel Greer (m. VY 64)", 3, faith="catholic", traits=["P.warmth:very_high", "P.openness:high"],
      reputation="beloved", fame=0.8, deeds=["first_child"], memorials=["Lake Tamsin", "Port Tamsin", "the name Tamsin", "Tamsin's Day (12 June) in Port Tamsin"],
      moved_to=["port_tamsin"], notes=["the first child born aboard (12 June 2252)", "taught school for 52 years", "hated being called 'the first'"]),
    P("esperanza_villalobos", "Esperanza", "Villalobos", "F", -21, 71, "earth:chicago", "founder", "victory_bay", "doctor", "physician; Moderator VY 26-30", ["villalobos"],
      "married", "Lorenzo Ibarra (m. VY 30)", 0, childless="gave_share", faith="catholic", traits=["P.conscientiousness:very_high", "P.courage:high", "P.warmth:high"],
      reputation="revered", fame=0.6, deeds=["burn_fever", "victory_bay_founded"], memorials=["the Fever Memorial, Victory Bay", "Villalobos Clinic, Port Carrow",
      "a saint to South Shore Catholics (not canonised)"], moved_to=["victory_bay"], roles=["physician"],
      notes=["from Pilsen, Chicago", "gave her share to her sister Graciela, whose third child was named Esperanza"]),
    P("finnegan_moriarty", "Finnegan", "Moriarty", "M", -24, 64, "earth:erie", "founder", "tern_harbor", "fisher", "founder of Tern Harbor", ["moriarty"],
      "married", "Bridget Moriarty (founder)", 5, faith="catholic", traits=["P.extraversion:high", "P.agreeableness:low"], reputation="respected", fame=0.15,
      deeds=["tern_harbor_founded"], memorials=["Moriarty Wharf"], roles=["founder"]),
    P("tomas_reyes", "Tomás", "Reyes", "M", -12, 70, "earth:toledo", "founder", "solana_point", "builder", "co-founder of Solana Point", ["reyes"],
      "married", "Maribel Reyes (station-born)", 4, faith="catholic", traits=["P.conscientiousness:high", "P.courage:high"], reputation="hero", fame=0.35,
      deeds=["solana_point_founded"], moved_to=["solana_point"], notes=["came aboard aged 12; cousin of Lucía Reyes"]),
    P("minnie_kowalczyk", "Wilhelmina", "Kowalczyk", "F", -3, 107, "earth:hamtramck", "founder", "fenwick", None, "the Last Earthborn; seamstress", ["kowalczyk"],
      "widowed", "three husbands (the last, Walter Booker, d. VY 98)", 7, faith="catholic", traits=["P.humour:very_high", "P.warmth:high"], reputation="beloved", fame=0.5,
      deeds=["last_earthborn"], memorials=["Minnie's Line ('I remember a sky with nothing in it') quoted at Returns", "Kowalczyk Park, Fenwick"],
      moved_to=["fenwick"], notes=["aboard at three; remembered the yard's windows, not Earth", "over 900 living descendants in VY 500"]),
    # ------------------------------------------------------------------ the Filling
    P("rosario_solano", "Rosario", "Solano", "F", 6, 79, "port_carrow", "station", "solana_point", None, "founder of Solana Point and Playa Verde", ["solano"],
      "married", "Arturo Luna", 6, faith="catholic", traits=["P.extraversion:very_high", "P.courage:high", "V.community"], reputation="revered", fame=0.5,
      deeds=["solana_point_founded", "playa_verde_founded"], memorials=["Solana Point (named for her, and the sun)", "Plaza Solano, Playa Verde"], moved_to=["solana_point", "playa_verde"],
      roles=["founder", "leader_heart"]),
    P("jonas_yoder", "Jonas", "Yoder", "M", 20, 88, "marlowe", "station", "tamarack", "farmer", "founder of Tamarack", ["yoder"],
      "married", "Anna Yoder", 9, faith="plain", reputation="respected", fame=0.08, deeds=["tamarack_founded"], moved_to=["tamarack"]),
    P("salvatore_decarlo", "Salvatore", "DeCarlo", "M", 18, 90, "harrow_falls", "station", "brightwater", "shopkeeper", "founder of Brightwater; built the first boardwalk", ["decarlo"],
      "married", "Philomena DeCarlo", 5, faith="catholic", traits=["P.extraversion:very_high", "P.humour:high"], reputation="beloved", fame=0.15,
      deeds=["brightwater_founded"], memorials=["DeCarlo's Arcade (still open)"], moved_to=["brightwater"]),
    P("otis_merriweather", "Otis", "Merriweather", "M", 30, 101, "harrow_falls", "station", "harrow_falls", "teacher", "inventor of spinball", ["merriweather"],
      "married", "Clara Merriweather", 2, faith="freedom_baptist", traits=["P.openness:high", "P.humour:high"], reputation="beloved", fame=0.45,
      deeds=["spinball_invented"], memorials=["the Merriweather Trophy (spinball's best player)", "Merriweather Field, Harrow Falls"], roles=["teacher", "coach"]),
    P("eli_haskins", "Eli", "Haskins", "M", 45, 118, "fenwick", "station", "haskins_corner", "shopkeeper", "keeper of the Haskins store", ["haskins"],
      "married", "Dora Haskins", 3, faith="full_gospel", reputation="forgotten", fame=0.05, deeds=["haskins_corner_founded"], moved_to=["haskins_corner"]),
    P("maeve_dunmore_elder", "Maeve", "Dunmore", "F", 50, 122, "marlowe", "station", "dunmore_crossing", "driver", "depot keeper", ["dunmore"],
      "married", "Liam Dunmore", 4, faith="catholic", reputation="forgotten", fame=0.03, deeds=["dunmore_crossing_founded"], moved_to=["dunmore_crossing"]),
    P("abigail_loomis", "Abigail", "Loomis", "F", 60, 140, "marlowe", "station", "loomis_grove", "farmer", "planter of the Loomis orchards", ["loomis"],
      "married", "Nathaniel Loomis", 2, faith="lakes_union", reputation="forgotten", fame=0.05, deeds=["loomis_grove_founded"], moved_to=["loomis_grove"]),
    P("hollis_pruett", "Hollis", "Pruett", "M", 70, 138, "kessler", "station", "pruett", "clerk", "surveyor", ["pruett"],
      "never_married", None, 0, childless="gave_share", reputation="forgotten", fame=0.03, deeds=["pruett_founded"], moved_to=["pruett"],
      notes=["gave his share to his brother Amos; the Pruetts of Pruett descend from Amos"]),
    P("harriet_osei_lindqvist", "Harriet", "Osei-Lindqvist", "F", 55, 131, "kessler", "station", "kessler", "lawyer", "Moderator VY 91-100; author of the Balance Act", ["osei", "lindqvist"],
      "married", "Kofi Lindqvist-Mensah", 2, faith="lakes_union", traits=["P.conscientiousness:very_high", "P.warmth:low", "V.fairness"], reputation="contested", fame=0.4,
      deeds=["balance_act"], memorials=["the Osei-Lindqvist Room at the Registry"], roles=["leader_task", "opinion_leader"],
      notes=["'Every child a choice, every choice a share'", "blamed by some families for 'counting babies'"]),
    P("bank_child_first", "Hope", "Abernathy", "F", 70, 151, "kessler", "bank", "kessler", "teacher", "the first Bank Child", ["abernathy"],
      "married", "Samuel Ortega", 4, faith="lakes_union", reputation="forgotten", fame=0.05, deeds=["ark_bank_children"]),
    # ------------------------------------------------------------------ the Settled Age
    P("wendell_achterberg", "Wendell", "Achterberg", "M", 100, 176, "marlowe", "station", "kessler", "pastor", "first President of the Lakes Union Church; Moderator VY 141-145", ["achterberg"],
      "married", "Hazel Achterberg", 3, faith="lakes_union", traits=["P.agreeableness:high", "V.unity"], reputation="respected", fame=0.12,
      deeds=["lakes_church_union"], moved_to=["kessler"], notes=["ancestor of Moderator Rosalind Achterberg-Nuñez"]),
    P("priya_raghunathan", "Priya", "Raghunathan", "F", 110, 189, "bellhaven", "station", "bellhaven", "teacher", "Warden; founder of the Wardens' College", ["raghunathan"],
      "never_married", None, 0, childless="gave_share", faith="dharmic", traits=["P.openness:very_high", "P.curiosity:very_high"], reputation="revered", fame=0.3,
      deeds=["college_founded"], memorials=["Raghunathan Library, Columbia College"], roles=["teacher", "scientist"],
      notes=["gave her share to her brother Arjun; the Raghunathan-Coles of Bellhaven descend from him"]),
    P("casimir_nowicki", "Casimir", "Nowicki", "M", 120, 199, "port_carrow", "station", "port_carrow", "pastor", "first Bishop of Columbia", ["nowicki"],
      "never_married", None, 0, childless="vocation", faith="catholic", traits=["P.conscientiousness:high", "V.tradition"], reputation="revered", fame=0.2,
      deeds=["columbian_rite"], memorials=["Bishop Nowicki's tomb (the only tomb aboard), St. Hedwig's"], roles=["clergy"]),
    P("agnes_szabo", "Agnes", "Szabo", "F", 150, 232, "harrow_falls", "station", "harrow_falls", "librarian", "author of 'The Book of the Lakes'", ["szabo"],
      "married", "Laszlo Kiss", 2, faith="catholic", traits=["P.openness:high", "V.tradition"], reputation="respected", fame=0.2, deeds=["heritage_revival"],
      memorials=["'The Book of the Lakes' (every school has one)"], roles=["archivist", "elder_storyteller"]),
    P("gerald_foxworth", "Gerald", "Foxworth", "M", 160, 230, "marlowe", "station", "marlowe", "farmer", "the man who brought the foxes", ["foxworth"],
      "married", "Ida Foxworth", 3, faith="lakes_union", reputation="notorious", fame=0.25, deeds=["fox_year"], notes=["'a real Foxworth' means a well-meaning fool"]),
    # ------------------------------------------------------------------ the Troubles
    P("silas_brandvold", "Silas", "Brandvold", "M", 215, 270, "marlowe", "station", "marlowe", "farmer", "leader of the Returners", ["brandvold"],
      "married", "Johanna Brandvold", 1, faith="lakes_union", traits=["P.extraversion:very_high", "P.agreeableness:low", "V.home", "D.narcissism:moderate"],
      reputation="villain", fame=0.6, deeds=["returners_rise", "the_referendum", "sternward_march", "stern_breach"],
      notes=["his daughter Hanne took her mother's name (Lund)", "a martyr to a few quiet Northland families"]),
    P("magdalena_oyelaran", "Magdalena", "Oyelaran", "F", 220, 301, "port_carrow", "station", "pelican_cove", "teacher", "Returner orator", ["oyelaran"],
      "married", "Emmanuel Adeyemi", 0, childless="protest", faith="catholic", traits=["P.openness:high", "P.courage:high", "V.truth"], reputation="contested", fame=0.3,
      deeds=["returners_rise", "sternward_march"], moved_to=["pelican_cove"],
      notes=["refused her share: 'no child of mine born going the wrong way'", "renounced sabotage after the Breach; pardoned VY 280"]),
    P("thaddeus_kowal", "Thaddeus", "Kowal", "M", 238, 270, "fenwick", "station", "kessler", "mechanic", "Warden who sealed the Stern Breach", ["kowal"],
      "married", "Irena Kowal", 2, faith="catholic", traits=["P.courage:very_high", "P.conscientiousness:high"], reputation="hero", fame=0.5,
      deeds=["stern_breach"], memorials=["the Kowal Medal (bravery)", "Kowal Street in every town"], roles=["engineer"]),
    P("rukmini_desai", "Rukmini", "Desai", "F", 222, 305, "kessler", "station", "kessler", "police", "Marshal-General; Moderator VY 261-275 (emergency)", ["desai"],
      "never_married", None, 0, childless="duty", faith="dharmic", traits=["P.conscientiousness:very_high", "P.warmth:low", "V.order"], reputation="contested", fame=0.3,
      deeds=["the_referendum", "marshal_rule"], roles=["marshal", "leader_task"], notes=["kept the station together or kept it down, depending who's telling"]),
    P("josephine_adebayo_ruiz", "Josephine", "Adebayo-Ruiz", "F", 240, 318, "solana_point", "station", "kessler", "lawyer", "the Reconciler; Moderator VY 276-285", ["adebayo", "ruiz"],
      "married", "Daniel Ruiz-Takahashi", 3, faith="catholic", traits=["P.agreeableness:very_high", "P.warmth:very_high", "V.peace"], reputation="revered", fame=0.45,
      deeds=["the_reconciliation"], memorials=["Reconciliation Day (the first Sunday of October)", "the Adebayo-Ruiz Bridge over the Kettle"], moved_to=["kessler"],
      roles=["peacemaker", "leader_heart"]),
    # ------------------------------------------------------------------ the Long Calm
    P("cornelius_bright", "Cornelius", "Bright", "M", 290, 362, "port_carrow", "station", "port_carrow", "shopkeeper", "founder of the Order of the Lamp", ["bright"],
      "married", "Eunice Bright", 4, faith="freedom_baptist", reputation="respected", fame=0.15, deeds=["order_of_the_lamp"], roles=["club_president"]),
    P("raymundo_castellanos", "Raymundo", "Castellanos", "M", 300, 372, "pelican_cove", "station", "pelican_cove", "shopkeeper", "cannery founder", ["castellanos"],
      "married", "gwendolyn_pike", 5, faith="catholic", traits=["P.conscientiousness:high", "D.machiavellianism:moderate"], reputation="contested", fame=0.2,
      deeds=["cannery_boom"], notes=["'share-rich': gathered gifted shares for five children"]),
    P("gwendolyn_pike", "Gwendolyn", "Pike", "F", 305, 380, "tern_harbor", "station", "pelican_cove", "shopkeeper", "co-founder of Castellanos-Pike Canning", ["pike"],
      "married", "raymundo_castellanos", 5, faith="lakes_union", traits=["P.conscientiousness:very_high"], reputation="respected", fame=0.15, deeds=["cannery_boom"], moved_to=["pelican_cove"]),
    P("maeve_dunmore", "Maeve", "Dunmore", "F", 350, 430, "dunmore_crossing", "station", "pelican_cove", "dock_worker", "founder of the Cannery and Dock Workers Union", ["dunmore"],
      "married", "Sean Pham", 2, faith="catholic", traits=["P.courage:high", "V.fairness"], reputation="hero", fame=0.2, deeds=["cannery_union"], moved_to=["pelican_cove"],
      roles=["union_steward"]),
    # ------------------------------------------------------------------ the Fourth Lockdown and the three vehicle works (bible industry)
    P("absalom_thorne", "Absalom", "Thorne", "M", 301, "missing", "bellhaven", "station", "bellhaven", None, "College engineer of an old Warden line; builder of the Lantern", ["thorne"],
      "never_married", None, 0, childless="vocation", faith="none", traits=["P.openness:very_high", "P.conscientiousness:high", "V.truth"], reputation="contested", fame=0.3,
      deeds=["the_lantern", "the_lockout"], notes=["went down into the Chute galleries the night the Lantern woke; was there when the Steward closed them", "a saint to the Wardens' Library circle; a fool to most"]),
    P("augusta_brenneman", "Augusta", "Brenneman", "F", 318, 397, "harrow_falls", "station", "harrow_falls", "mechanic", "'Gus'; forewoman of the Falls Yard; founder of Harrow Motor Works", ["brenneman"],
      "married", "Otto Brenneman", 3, faith="lakes_union", traits=["P.conscientiousness:very_high", "P.agreeableness:low", "P.courage:high", "V.duty"], reputation="hero", fame=0.3,
      deeds=["three_yards", "yard_raids", "allotment_compact", "old_kettle"], memorials=["the Brenneman Gate at the Falls Yard"], roles=["founder", "leader_task"],
      notes=["held the Falls Yard the week the Wardens dissolved: 'the boards keep coming, so we keep building'", "'slept on the Drop with a shotgun' (it was a wrench)"]),
    P("elias_thornbury", "Elias", "Thornbury", "M", 341, 419, "dunmore_crossing", "station", "harrow_falls", "mechanic", "engineer of Old Kettle, the first people-made board", ["thornbury"],
      "married", "Ada Thornbury", 2, faith="lakes_union", traits=["P.openness:high", "P.conscientiousness:high", "P.extraversion:low"], reputation="respected", fame=0.2,
      deeds=["old_kettle"], moved_to=["harrow_falls"], roles=["engineer"], notes=["a Ring Line rail fitter; built the first ladder from salvaged rail steel"]),
    P("hiram_okonkwo_brenneman", "Hiram", "Okonkwo-Brenneman", "M", 372, 451, "harrow_falls", "station", "harrow_falls", "mechanic", "president of Harrow Motor Works VY 401-445", ["okonkwo", "brenneman"],
      "married", "Lydia Okonkwo-Brenneman", 4, faith="lakes_union", traits=["P.extraversion:high", "P.agreeableness:low", "V.success"], reputation="contested", fame=0.2,
      deeds=["board_wars", "standard_pattern_act", "allotment_inquiry"], roles=["leader_task", "rival"],
      notes=["Gus Brenneman's grandson by marriage; won the Board Wars by outlasting everyone", "accused of cheering the Keel Recall"]),
    P("della_brenneman_szabo", "Della", "Brenneman-Szabo", "F", 448, None, "harrow_falls", "station", "harrow_falls", "mechanic", "president of Harrow Motor Works since VY 489", ["brenneman", "szabo"],
      "married", "Gerald Szabo", 2, faith="lakes_union", traits=["P.conscientiousness:high", "P.warmth:high", "V.community"], reputation="beloved", fame=0.35,
      deeds=["harrow_mill_closure"], roles=["leader_heart", "manager"], notes=["took on 600 of the Mill No. 2 hands in VY 494", "wants a new Ladder and the Works' old men won't hear of it"]),
    P("theodora_lindqvist_vance", "Theodora", "Lindqvist-Vance", "F", 315, 392, "port_carrow", "station", "port_carrow", "builder", "'the Captain'; shipwright; founder of Carrow Coach Company", ["lindqvist", "vance"],
      "widowed", "Erling Vance", 2, faith="lakes_union", traits=["P.conscientiousness:very_high", "P.extraversion:high", "V.order"], reputation="revered", fame=0.3,
      deeds=["three_yards", "yard_raids", "allotment_compact", "carrow_keel_launched"], memorials=["the Captain's Slip at the Harbour Yard"], roles=["founder", "leader_task"]),
    P("bartholomew_achebe", "Bartholomew", "Achebe", "M", 350, 431, "port_carrow", "station", "port_carrow", "builder", "naval architect; designer of the Carrow Keel", ["achebe"],
      "married", "Constance Achebe", 3, faith="catholic", traits=["P.openness:very_high", "P.neuroticism:high"], reputation="contested", fame=0.25,
      deeds=["carrow_keel_launched", "board_wars", "standard_pattern_act", "keel_recall"], roles=["engineer"],
      notes=["his steel keels cracked forty years on; he lived to see the Recall and never designed again"]),
    P("octavia_fairweather", "Octavia", "Fairweather", "F", 405, 488, "loomis_grove", "station", "port_carrow", "banker", "'the Coach Queen'; president of Carrow Coach Company VY 445-469", ["fairweather"],
      "divorced", "once", 1, faith="lakes_union", traits=["P.extraversion:high", "P.agreeableness:low", "V.success"], reputation="notorious", fame=0.35,
      deeds=["allotment_inquiry"], moved_to=["port_carrow"], roles=["manager", "broker"], notes=["Moderator Cordelia Fairweather's cousin", "sold Steward boards out of the Harbour Yard; resigned VY 469"]),
    P("lionel_vance_okafor", "Lionel", "Vance-Okafor", "M", 452, None, "port_carrow", "station", "port_carrow", "mechanic", "president of Carrow Coach Company since VY 486", ["vance", "okafor"],
      "married", "Miriam Vance-Okafor", 1, faith="lakes_union", traits=["P.conscientiousness:high", "P.extraversion:low"], reputation="respected", fame=0.15,
      roles=["manager", "engineer"], notes=["the Captain's great-great-grandson; an engineer, not a salesman", "rebuilding Carrow's name after the Inquiry"]),
    P("ignacio_ybarra", "Ignacio", "Ybarra", "M", 322, 401, "solana_point", "station", "solana_point", "mechanic", "'Nacho'; bicycle builder; founder of Solana Cycle & Motor", ["ybarra"],
      "married", "Rosa Ybarra", 4, faith="catholic", traits=["P.humour:high", "P.extraversion:high", "P.openness:high"], reputation="beloved", fame=0.25,
      deeds=["three_yards", "allotment_compact", "golondrina"], roles=["founder", "leader_heart"], notes=["took over the South Yard with his cycle works in VY 356, because nobody else wanted it"]),
    P("pilar_ybarra_solano", "Pilar", "Ybarra-Solano", "F", 358, 446, "solana_point", "station", "solana_point", "mechanic", "designer of the Solana Lattice and the Golondrina; winner of the first Ring Run", ["ybarra", "solano"],
      "married", "Teodoro Solano", 2, faith="catholic", traits=["P.courage:very_high", "P.openness:high", "P.humour:high"], reputation="hero", fame=0.45,
      deeds=["golondrina", "board_wars", "standard_pattern_act", "first_ring_run"], memorials=["Pilar's Bend on the Coast Highway", "the Pilar Cup of the Ring Run"],
      roles=["engineer"], notes=["won the first Ring Run at 54, in a car she designed at 26"]),
    P("rafael_quintero", "Rafael", "Quintero", "M", 461, None, "playa_verde", "station", "solana_point", "driver", "'Rafa'; Solana's racing driver; seven-time Ring Run winner", ["quintero"],
      "partnered", "Lena Haddad", 0, childless="chose_not", faith="catholic", traits=["P.extraversion:very_high", "P.courage:very_high", "P.agreeableness:low"], reputation="beloved", fame=0.5,
      moved_to=["solana_point"], roles=["public_character"], notes=["won the Ring Run in VY 487, 489, 491, 493, 495, 496 and 498", "Port Carrow boos him"]),
    P("ines_ybarra_moreno", "Inés", "Ybarra-Moreno", "F", 457, None, "solana_point", "station", "solana_point", "mechanic", "president of Solana Cycle & Motor since VY 491", ["ybarra", "moreno"],
      "married", "Marco Moreno", 2, faith="catholic", traits=["P.openness:high", "P.extraversion:high", "V.success"], reputation="respected", fame=0.3,
      roles=["manager", "engineer"], notes=["Nacho Ybarra's great-granddaughter", "means to sell a Solana in Harrow Falls"]),
    # ------------------------------------------------------------------ the Present Age: the dead of living memory
    P("ruth_abernathy_chen", "Ruth", "Abernathy-Chen", "F", 390, 471, "kessler", "station", "kessler", "builder", "architect of the new Assembly Hall", ["abernathy", "chen"],
      "married", "Paul Chen", 1, faith="lakes_union", reputation="respected", fame=0.1, deeds=["assembly_hall_fire"]),
    P("ignatius_bhatt", "Ignatius", "Bhatt", "M", 395, 470, "bellhaven", "station", "kessler", "lawyer", "Moderator VY 436-445; the Gifting Act", ["bhatt"],
      "married", "Lorraine Bhatt", 2, faith="catholic", traits=["P.openness:high", "V.freedom"], reputation="respected", fame=0.35, deeds=["gifting_act"], moved_to=["kessler"]),
    P("declan_moriarty", "Declan", "Moriarty", "M", 400, 476, "tern_harbor", "station", "tern_harbor", "dock_worker", "leader of the Forty Days strike", ["moriarty"],
      "married", "Nora Moriarty", 3, faith="catholic", traits=["P.extraversion:high", "P.courage:high", "P.agreeableness:low"], reputation="hero", fame=0.45,
      deeds=["tern_cannery_strike"], memorials=["the Moriarty mural, Tern Harbor"], roles=["union_steward", "leader_heart"]),
    P("leopold_varga_hayes", "Leopold", "Varga-Hayes", "M", 410, 488, "harrow_falls", "station", "kessler", "editor", "founder of the Wire", ["varga", "hayes"],
      "divorced", "twice", 2, faith="none", traits=["P.openness:high", "P.extraversion:very_high"], reputation="respected", fame=0.4, deeds=["wire_founded"], moved_to=["kessler"]),
    P("wilhelm_ostrowski", "Wilhelm", "Ostrowski", "M", 425, 490, "fenwick", "station", "kessler", "editor", "editor of the Kessler Courier; broke the Share Scandal", ["ostrowski"],
      "married", "Dolores Ostrowski", 1, faith="catholic", traits=["P.conscientiousness:high", "V.truth"], reputation="respected", fame=0.3, deeds=["share_scandal"], moved_to=["kessler"],
      roles=["journalist"]),
    P("augustin_leclerc", "Augustin", "Leclerc", "M", 420, 497, "port_carrow", "station", "port_carrow", "lawyer", "Moderator VY 476-485", ["leclerc"],
      "married", "Simone Leclerc", 2, faith="catholic", reputation="respected", fame=0.3),
    # ------------------------------------------------------------------ the living (VY 500): the present's notable people
    P("rosalind_achterberg_nunez", "Rosalind", "Achterberg-Nuñez", "F", 447, None, "kessler", "station", "kessler", "lawyer", "Moderator of the Assembly (Charter League)",
      ["achterberg", "nunez"], "married", "Martín Achterberg-Nuñez (a Kessler bookbinder)", 2, faith="lakes_union",
      traits=["P.conscientiousness:very_high", "P.agreeableness:moderate", "V.tradition", "V.order", "speech:formal"], reputation="respected", fame=0.9,
      deeds=["long_session", "moderator_election_496", "quincentennial"], roles=["mayor", "leader_task"],
      notes=["cautious; wants the Notice studied quietly", "descended from Wendell Achterberg"]),
    P("tobias_wainwright_okafor", "Tobias", "Wainwright-Okafor", "M", 452, None, "bellhaven", "station", "bellhaven", "lawyer", "leader of the Open Hand; Assembly member for Bellhaven",
      ["wainwright", "okafor"], "married", "Ines Wainwright-Okafor (a nurse)", 0, childless="gave_share", faith="waymakers",
      traits=["P.openness:very_high", "P.extraversion:high", "V.freedom", "V.truth"], reputation="contested", fame=0.75,
      deeds=["long_session", "moderator_election_496", "flicker_petition"], roles=["council_member", "opinion_leader"],
      notes=["wants the Undercroft opened and the Notice answered", "he and Ines gave both their shares to his sister's family"]),
    P("evangeline_mbeki_hart", "Evangeline", "Mbeki-Hart", "F", 425, None, "oceanview", "station", "oceanview", "pastor", "founder of the Waymakers",
      ["mbeki", "hart"], "never_married", None, 0, childless="vocation", faith="waymakers", traits=["P.extraversion:very_high", "P.openness:high", "V.meaning"],
      reputation="contested", fame=0.8, deeds=["waymakers_founded"], roles=["clergy", "public_character"], notes=["75; preaches from the Oceanview Stage Plaza every Sunday at dusk"]),
    P("tobit_asante_grey", "Tobit", "Asante-Grey", "M", 470, None, "bellhaven", "station", "bellhaven", "pastor", "Waymaker minister; Mbeki-Hart's chosen successor", ["asante", "grey"],
      "partnered", "Ruben Delgado", 0, childless="unknown", faith="waymakers", traits=["P.openness:high", "P.warmth:high"], reputation="respected", fame=0.3),
    P("harlan_duquesne", "Harlan", "Duquesne", "M", 412, None, "kessler", "station", "oceanview", "retired", "former Moderator (VY 456-466), disgraced", ["duquesne"],
      "divorced", "Celeste Duquesne (divorced VY 469)", 1, faith="lakes_union", traits=["P.agreeableness:low", "D.narcissism:high"], reputation="notorious", fame=0.7,
      deeds=["gray_fever", "share_scandal", "duquesne_trial"], moved_to=["oceanview"], notes=["88; his son Bernard doesn't speak to him"]),
    P("margit_kovacs_lee", "Margit", "Kovacs-Lee", "F", 448, None, "harrow_falls", "station", "kessler", "editor", "Wire journalist; read the Registry Leak on air", ["kovacs", "lee"],
      "divorced", "Jun Lee (div. VY 489)", 1, faith="none", traits=["P.courage:high", "P.agreeableness:low", "V.truth"], reputation="contested", fame=0.65,
      deeds=["registry_leak"], moved_to=["kessler"], roles=["journalist"], notes=["won't name her source"]),
    P("marisol_ybarra_quinn", "Marisol", "Ybarra-Quinn", "F", 420, None, "dunmore_crossing", "station", "cedar_ford", "retired", "retired constable; hero of the Kettle Flood",
      ["ybarra", "quinn"], "widowed", "Patrick Quinn (d. VY 480)", 3, faith="catholic", traits=["P.courage:very_high", "P.warmth:high", "P.humour:high"], reputation="hero", fame=0.7,
      deeds=["kettle_flood"], memorials=["the Ybarra-Quinn Boat, Cedar Ford"], moved_to=["cedar_ford"], roles=["police"], notes=["80; still swims the Kettle every morning"]),
    P("juniper_stroud", "Juniper", "Stroud", "F", 430, None, "harrow_falls", "station", "harrow_falls", "retired", "first aerostat racing champion", ["stroud"],
      "widowed", "Emmett Okoye", 2, faith="none", traits=["P.courage:very_high", "P.extraversion:high"], reputation="beloved", fame=0.55, deeds=["aerostat_racing"]),
    P("linnet_okoye_stroud", "Linnet", "Okoye-Stroud", "F", 476, None, "harrow_falls", "station", "harrow_falls", "mechanic", "aerostat racing champion VY 497-499; Juniper Stroud's granddaughter",
      ["okoye", "stroud"], "never_married", None, 0, childless="chose_not", faith="none", traits=["P.courage:very_high", "P.conscientiousness:low"], reputation="beloved", fame=0.6),
    P("anh_tran_delacroix", "Anh", "Tran-Delacroix", "F", 428, None, "pelican_cove", "station", "pelican_cove", "retired", "nurse; hero of the Gray Fever", ["tran", "delacroix"],
      "married", "Pierre Delacroix", 2, faith="dharmic", traits=["P.warmth:very_high", "P.conscientiousness:very_high"], reputation="hero", fame=0.6, deeds=["gray_fever"], roles=["nurse"]),
    P("luis_arrieta_wu", "Luis", "Arrieta-Wu", "M", 438, None, "tern_harbor", "station", "solana_point", "agent", "'Lucky Luis', developer of Pier Plaza and Pacific City", ["arrieta", "wu"],
      "married", "his third wife, Vanessa Arrieta-Wu", 4, faith="full_gospel", traits=["P.extraversion:very_high", "D.narcissism:moderate", "V.success"], reputation="contested", fame=0.7,
      deeds=["solana_boom"], moved_to=["solana_point"], notes=["a Tern Exodus boy made good", "four children by three marriages, two from gifted shares"]),
    P("dante_okonkwo_silva", "Dante", "Okonkwo-Silva", "M", 455, None, "solana_point", "station", "solana_point", "teacher", "spinball legend (six Spin Cups); coach of the Suns", ["okonkwo", "silva"],
      "married", "Ximena Okonkwo-Silva", 2, faith="catholic", traits=["P.extraversion:high", "P.conscientiousness:high"], reputation="beloved", fame=0.85, deeds=["suns_dynasty"], roles=["coach"]),
    P("hector_delmar", "Héctor", "Delmar", "M", 430, None, "pelican_cove", "station", "pelican_cove", "retired", "owner of the burned Delmar Cannery", ["delmar"],
      "widowed", "Consuelo Delmar", 3, faith="catholic", traits=["P.agreeableness:low", "P.neuroticism:high"], reputation="contested", fame=0.4, deeds=["delmar_fire"],
      notes=["70; swears he's innocent; half the Cove doesn't believe him"]),
    P("imogen_sato_ferris", "Imogen", "Sato-Ferris", "F", 460, "missing", "bellhaven", "station", "bellhaven", "university_student", "the student who never came back from the Bellhaven Dig",
      ["sato", "ferris"], "never_married", None, 0, childless="died_young", faith="none", traits=["P.curiosity:very_high", "P.courage:high"], reputation="beloved", fame=0.75,
      deeds=["bellhaven_dig"], memorials=["a lamp kept lit in the Wardens' Library window"], notes=["missing since VY 481, aged 21"]),
    P("caspian_holloway", "Caspian", "Holloway", "M", 459, None, "bellhaven", "station", "bellhaven", "librarian", "keeper of the Wardens' Library; one of the Bellhaven Five", ["holloway"],
      "never_married", None, 0, childless="chose_not", faith="none", traits=["P.openness:very_high", "P.neuroticism:high"], reputation="contested", fame=0.5,
      deeds=["bellhaven_dig"], roles=["archivist", "librarian"], notes=["hasn't stopped looking for Imogen"]),
    P("nadia_haddad", "Nadia", "Haddad", "F", 460, None, "port_carrow", "station", "port_carrow", "doctor", "physician; one of the Bellhaven Five", ["haddad"],
      "married", "Omar Bazzi", 2, faith="muslim", traits=["P.conscientiousness:high"], reputation="private", fame=0.3, deeds=["bellhaven_dig"], moved_to=["port_carrow"],
      notes=["never speaks of the Dig"]),
    P("tomasz_wieczorek", "Tomasz", "Wieczorek", "M", 461, None, "fenwick", "station", "fenwick", "mechanic", "machinist; one of the Bellhaven Five", ["wieczorek"],
      "married", "Hana Wieczorek", 1, faith="catholic", reputation="private", fame=0.3, deeds=["bellhaven_dig"], moved_to=["fenwick"], notes=["drinks; says the hatch 'hummed'"]),
    P("yusuf_okonjo", "Yusuf", "Okonjo", "M", 460, None, "kessler", "station", "kessler", "teacher", "teacher; one of the Bellhaven Five", ["okonjo"],
      "married", "Grace Okonjo", 3, faith="muslim", reputation="private", fame=0.3, deeds=["bellhaven_dig"]),
    P("colette_marchand", "Colette", "Marchand", "F", 445, None, "port_carrow", "station", "port_carrow", "editor", "writer of 'The Lamplighters'", ["marchand"],
      "married", "Bea Tremblay", 1, faith="catholic", traits=["P.openness:very_high", "P.humour:very_high"], reputation="beloved", fame=0.7, deeds=["lamplighters_serial"],
      roles=["artist"], notes=["lives in the Côte; her wife Bea runs a bakery"]),
    P("honor_achebe", "Honor", "Achebe", "F", 469, None, "kessler", "station", "port_carrow", "unemployed", "the voice of Delia Lamp in 'The Lamplighters'", ["achebe"],
      "never_married", None, 0, childless="chose_not", faith="none", reputation="beloved", fame=0.65, moved_to=["port_carrow"], roles=["artist"]),
    P("obadiah_kincaid_morales", "Obadiah", "Kincaid-Morales", "M", 440, None, "tamarack", "station", "kessler", "police", "Marshal-General", ["kincaid", "morales"],
      "married", "Helen Kincaid-Morales", 3, faith="full_gospel", traits=["P.conscientiousness:very_high", "V.order"], reputation="respected", fame=0.5,
      deeds=["southland_marshal"], moved_to=["kessler"], roles=["marshal"]),
    P("beatriz_holloway_anand", "Beatriz", "Holloway-Anand", "F", 438, None, "port_carrow", "station", "kessler", "clerk", "chair of the Quincentennial Commission", ["holloway", "anand"],
      "widowed", "Raj Anand (d. VY 490)", 3, faith="catholic", traits=["P.extraversion:high", "P.conscientiousness:high"], reputation="respected", fame=0.55,
      deeds=["quincentennial_commission", "quincentennial"], moved_to=["kessler"], notes=["suspected by some of staging the Notice"]),
    P("ezekiel_brannock", "Ezekiel", "Brannock", "M", 470, None, "port_carrow", "station", "port_carrow", "dock_worker", "captain of the Port Carrow Mariners (Spin Cup VY 499)", ["brannock"],
      "never_married", None, 0, childless="chose_not", faith="catholic", traits=["P.extraversion:high", "P.courage:high"], reputation="beloved", fame=0.75, deeds=["mariners_cup_499"]),
    P("cordelia_fairweather", "Cordelia", "Fairweather", "F", 410, None, "loomis_grove", "station", "loomis_grove", "retired", "former Moderator (VY 466-475) who cleaned up after Duquesne", ["fairweather"],
      "widowed", "Arthur Fairweather", 4, faith="lakes_union", traits=["P.conscientiousness:very_high", "P.humour:high"], reputation="respected", fame=0.4, notes=["90; keeps bees"]),
    P("winifred_osei", "Winifred", "Osei", "F", 430, None, "port_carrow", "station", "port_carrow", "retired", "former Moderator (VY 486-495)", ["osei"],
      "married", "Kwame Osei", 2, faith="freedom_baptist", reputation="respected", fame=0.4),
    P("gwendolyn_pike_younger", "Gwendolyn", "Castellanos-Pike", "F", 420, None, "pelican_cove", "station", "port_carrow", "retired", "head of Castellanos-Pike Canning; closed the Tern Harbor cannery",
      ["castellanos", "pike"], "widowed", "Ellis Grant", 2, faith="lakes_union", traits=["P.conscientiousness:high", "P.warmth:low"], reputation="villain", fame=0.5,
      deeds=["tern_cannery_closes"], moved_to=["port_carrow"], notes=["80; hated in Tern Harbor"]),
    # mayors (VY 500)
    P("stan_wojcik_ferreira", "Stanisław", "Wojcik-Ferreira", "M", 451, None, "port_carrow", "station", "port_carrow", "lawyer", "Mayor of Port Carrow", ["wojcik", "ferreira"], "married", "Lena Wojcik-Ferreira", 2,
      faith="catholic", traits=["P.extraversion:high"], fame=0.4, roles=["mayor"]),
    P("graciela_montoya_park", "Graciela", "Montoya-Park", "F", 455, None, "solana_point", "station", "solana_point", "agent", "Mayor of Solana Point", ["montoya", "park"], "married", "David Park", 2,
      faith="catholic", traits=["P.extraversion:very_high"], fame=0.45, roles=["mayor"]),
    P("frederick_hollenbeck", "Frederick", "Hollenbeck", "M", 440, None, "kessler", "station", "kessler", "clerk", "Mayor of Kessler", ["hollenbeck"], "married", "Ann Hollenbeck", 3, faith="lakes_union", fame=0.25, roles=["mayor"]),
    P("dee_kiss_mahoney", "Dolores", "Kiss-Mahoney", "F", 449, None, "harrow_falls", "station", "harrow_falls", "shopkeeper", "Mayor of Harrow Falls", ["kiss", "mahoney"], "married", "Brian Mahoney", 2,
      faith="catholic", traits=["P.agreeableness:low", "P.humour:high"], fame=0.35, roles=["mayor"]),
    P("leonard_pembrook", "Leonard", "Pembrook", "M", 432, None, "oceanview", "station", "oceanview", "hotel_worker", "Mayor of Oceanview", ["pembrook"], "widowed", "Joan Pembrook", 1, faith="lakes_union", fame=0.2, roles=["mayor"]),
    P("vinnie_decarlo", "Vincenzo", "DeCarlo", "M", 458, None, "brightwater", "station", "brightwater", "shopkeeper", "Mayor of Brightwater; owns DeCarlo's Arcade", ["decarlo"], "divorced", "twice", 3,
      faith="catholic", traits=["P.extraversion:very_high", "P.conscientiousness:low"], fame=0.35, roles=["mayor"]),
    P("itzel_solano_garza", "Itzel", "Solano-Garza", "F", 460, None, "playa_verde", "station", "playa_verde", "teacher", "Alcaldesa (Mayor) of Playa Verde", ["solano", "garza"], "married", "Rubén Garza", 2,
      faith="catholic", traits=["P.warmth:high"], fame=0.3, roles=["mayor"]),
    P("gunnar_lindqvist_brandt", "Gunnar", "Lindqvist-Brandt", "M", 444, None, "marlowe", "station", "marlowe", "farmer", "Mayor of Marlowe", ["lindqvist", "brandt"], "married", "Karin Lindqvist-Brandt", 4,
      faith="lakes_union", traits=["P.extraversion:low", "V.tradition"], fame=0.2, roles=["mayor", "farmer"]),
    P("anjali_raghunathan_cole", "Anjali", "Raghunathan-Cole", "F", 450, None, "bellhaven", "station", "bellhaven", "teacher", "Mayor of Bellhaven", ["raghunathan", "cole"], "married", "Martin Cole", 1,
      faith="dharmic", traits=["P.openness:high"], fame=0.25, roles=["mayor"]),
    P("siobhan_moriarty", "Siobhan", "Moriarty", "F", 462, None, "tern_harbor", "station", "tern_harbor", "fisher", "Mayor of Tern Harbor; Declan Moriarty's granddaughter", ["moriarty"], "never_married", None, 0,
      childless="gave_share", faith="catholic", traits=["P.courage:high", "P.agreeableness:low"], fame=0.3, roles=["mayor"], notes=["gave her share to keep a Tern family from leaving"]),
    P("thanh_nguyen_castellanos", "Thanh", "Nguyen-Castellanos", "M", 453, None, "pelican_cove", "station", "pelican_cove", "dock_worker", "Mayor of Pelican Cove", ["nguyen", "castellanos"], "married", "Lupe Nguyen-Castellanos", 2,
      faith="dharmic", fame=0.25, roles=["mayor"]),
    P("clarence_kowalczyk_booker", "Clarence", "Kowalczyk-Booker", "M", 438, None, "fenwick", "station", "fenwick", "pastor", "Mayor of Fenwick; pastor of Mount Zion", ["kowalczyk", "booker"], "married", "Mae Kowalczyk-Booker", 4,
      faith="freedom_baptist", traits=["P.extraversion:high", "P.warmth:high"], fame=0.3, roles=["mayor", "clergy"], notes=["a Minnie Kowalczyk descendant, and proud of it"]),
    P("pieter_vandermolen", "Pieter", "VanderMolen", "M", 446, None, "port_tamsin", "station", "port_tamsin", "shopkeeper", "Mayor of Port Tamsin; runs the marina", ["vandermolen"], "married", "Els VanderMolen", 2,
      faith="lakes_union", fame=0.15, roles=["mayor"]),
    P("ingrid_halvorsen", "Ingrid", "Halvorsen", "F", 457, None, "haven_point", "station", "haven_point", "clerk", "Mayor of Haven Point", ["halvorsen"], "partnered", "Tove Ask", 1, faith="lakes_union", fame=0.15, roles=["mayor"]),
    P("mabel_freeman_ortiz", "Mabel", "Freeman-Ortiz", "F", 434, None, "victory_bay", "station", "victory_bay", "retired", "Mayor of Victory Bay", ["freeman", "ortiz"], "widowed", "Luis Ortiz", 3,
      faith="freedom_baptist", fame=0.15, roles=["mayor"]),
    P("amos_yoder_stoltz", "Amos", "Yoder-Stoltz", "M", 441, None, "tamarack", "station", "tamarack", "farmer", "Mayor of Tamarack; cheesemaker", ["yoder", "stoltz"], "married", "Ruth Yoder-Stoltz", 6,
      faith="plain", traits=["P.agreeableness:high", "V.tradition"], fame=0.15, roles=["mayor", "farmer"], notes=["six children: his sisters and cousins gifted him shares"]),
    P("lamar_haskins", "Lamar", "Haskins", "M", 448, None, "haskins_corner", "station", "haskins_corner", "cook", "Mayor of Haskins Corner; owns the Corner Diner", ["haskins"], "married", "Debra Haskins", 2,
      faith="full_gospel", traits=["P.extraversion:high"], fame=0.2, roles=["mayor"]),
    P("wren_castellano", "Wren", "Castellano", "F", 468, None, "cedar_ford", "station", "cedar_ford", "shopkeeper", "Mayor of Cedar Ford; potter", ["castellano"], "never_married", None, 0,
      childless="chose_not", faith="none", traits=["P.openness:very_high"], fame=0.15, roles=["mayor", "artist"]),
    P("harold_loomis_petrie", "Harold", "Loomis-Petrie", "M", 431, None, "loomis_grove", "station", "loomis_grove", "farmer", "Mayor of Loomis Grove; the cider mill", ["loomis", "petrie"], "married", "Joan Loomis-Petrie", 2,
      faith="lakes_union", fame=0.1, roles=["mayor", "farmer"]),
    P("ruth_ann_pruett_doyle", "Ruth Ann", "Pruett-Doyle", "F", 443, None, "pruett", "station", "pruett", "shopkeeper", "Chair of Pruett; keeps the Pruett Store", ["pruett", "doyle"], "married", "Walt Doyle", 3,
      faith="lakes_union", fame=0.05, roles=["mayor"]),
    P("fergus_dunmore", "Fergus", "Dunmore", "M", 439, None, "dunmore_crossing", "station", "dunmore_crossing", "driver", "Mayor of Dunmore Crossing; the depot master", ["dunmore"], "married", "Aileen Dunmore", 2,
      faith="catholic", fame=0.1, roles=["mayor"]),
    # institutions and faiths (VY 500)
    P("teodoro_nowicki_ramos", "Teodoro", "Nowicki-Ramos", "M", 444, None, "port_carrow", "station", "port_carrow", "pastor", "Bishop of Columbia", ["nowicki", "ramos"], "married", "Clara Nowicki-Ramos", 2,
      faith="catholic", traits=["P.agreeableness:high", "V.tradition"], fame=0.5, roles=["clergy"]),
    P("margaret_achterberg_voss", "Margaret", "Achterberg-Voss", "F", 436, None, "kessler", "station", "kessler", "pastor", "President of the Lakes Union Church; the Moderator's aunt", ["achterberg", "voss"],
      "widowed", "Harold Voss", 2, faith="lakes_union", fame=0.35, roles=["clergy"]),
    P("yusuf_haddad_bazzi", "Yusuf", "Haddad-Bazzi", "M", 450, None, "port_carrow", "station", "port_carrow", "pastor", "Imam of the Carrow Masjid", ["haddad", "bazzi"], "married", "Layla Haddad-Bazzi", 3,
      faith="muslim", traits=["P.warmth:high"], fame=0.3, roles=["clergy"]),
    P("miriam_adler_castro", "Miriam", "Adler-Castro", "F", 458, None, "kessler", "station", "kessler", "pastor", "Rabbi of Temple Beth Columbia", ["adler", "castro"], "married", "Eli Adler-Castro", 2,
      faith="jewish", fame=0.2, roles=["clergy"]),
    P("jerome_booker", "Jerome", "Booker", "M", 445, None, "fenwick", "station", "fenwick", "pastor", "President of the Freedom Baptist Convention", ["booker"], "married", "Angela Booker", 3,
      faith="freedom_baptist", traits=["P.extraversion:very_high"], fame=0.35, roles=["clergy"]),
    P("clay_tuttle", "Clay", "Tuttle", "M", 461, None, "haskins_corner", "station", "haskins_corner", "pastor", "Full Gospel revival preacher ('Brother Clay')", ["tuttle"], "married", "Lacey Tuttle", 5,
      faith="full_gospel", traits=["P.extraversion:very_high", "D.narcissism:moderate"], reputation="contested", fame=0.4, roles=["clergy", "public_character"],
      notes=["preaches that the Notice is the first trumpet"]),
    P("philippa_strand_ochoa", "Philippa", "Strand-Ochoa", "F", 437, None, "kessler", "station", "kessler", "banker", "Governor of the Commons Bank", ["strand", "ochoa"], "married", "Raúl Ochoa", 2,
      faith="none", traits=["P.conscientiousness:very_high", "P.warmth:low"], fame=0.3),
    P("henrietta_oduya", "Henrietta", "Oduya", "F", 442, None, "kessler", "station", "kessler", "clerk", "Chief Registrar", ["oduya"], "never_married", None, 0, childless="gave_share",
      faith="freedom_baptist", traits=["P.conscientiousness:very_high"], reputation="contested", fame=0.35, notes=["under fire since the Leak"]),
    P("solomon_achebe_hart", "Solomon", "Achebe-Hart", "M", 433, None, "kessler", "station", "kessler", "lawyer", "Chief Justice of the Station Court", ["achebe", "hart"], "married", "Ruth Achebe-Hart", 2,
      faith="lakes_union", fame=0.3, roles=["judge"]),
    P("rafael_iturbide_marsh", "Rafael", "Iturbide-Marsh", "M", 445, None, "bellhaven", "station", "bellhaven", "teacher", "President of Columbia College", ["iturbide", "marsh"], "married", "Joanne Marsh", 2,
      faith="catholic", traits=["P.openness:high", "P.conscientiousness:high"], fame=0.3),
    P("rosa_pham_moriarty", "Rosa", "Pham-Moriarty", "F", 452, None, "pelican_cove", "station", "pelican_cove", "dock_worker", "President of the Cannery and Dock Workers Union", ["pham", "moriarty"],
      "married", "Kevin Pham", 2, faith="catholic", traits=["P.courage:high", "P.agreeableness:low"], fame=0.35, roles=["union_steward"]),
    P("kaz_horvath", "Kasimir", "Horvath", "M", 447, None, "harrow_falls", "station", "harrow_falls", "mechanic", "Master of the Aerostat Pilots' Guild", ["horvath"], "married", "Edie Horvath", 2, faith="catholic", fame=0.2),
    P("barnaby_quist", "Barnaby", "Quist", "M", 442, None, "kessler", "station", "kessler", "editor", "'Uncle Barnaby', host of the Wire's morning show", ["quist"], "married", "Lottie Quist", 3,
      faith="lakes_union", traits=["P.extraversion:very_high", "P.humour:very_high"], reputation="beloved", fame=0.8, roles=["public_character"]),
    P("estrella_vance_nakamura", "Estrella", "Vance-Nakamura", "F", 474, None, "solana_point", "station", "solana_point", "waiter", "singer ('Sunline', 'Third of the Way')", ["vance", "nakamura"],
      "never_married", None, 0, childless="chose_not", faith="none", traits=["P.extraversion:very_high", "P.openness:high"], reputation="beloved", fame=0.8, roles=["musician"],
      notes=["her song 'Third of the Way' (written the week of the Notice) is everywhere"]),
    P("frankie_wisniewski", "Frankie", "Wisniewski", "M", 439, None, "port_carrow", "station", "port_carrow", "bartender", "bandleader, 'Frankie Wiz and the Hedwig Hill Boys' (polka)", ["wisniewski"],
      "married", "Dot Wisniewski", 4, faith="catholic", traits=["P.extraversion:very_high"], reputation="beloved", fame=0.5, roles=["musician"]),
    P("consuelo_arrieta", "Consuelo", "Arrieta", "F", 431, None, "playa_verde", "station", "playa_verde", "baker", "'Mamá Chelo' of La Estrella bakery", ["arrieta"], "widowed", "Joaquín Arrieta", 5,
      faith="catholic", traits=["P.warmth:very_high"], reputation="beloved", fame=0.4, notes=["Lucky Luis's aunt; says so often"]),
    P("walt_tomczak", "Walter", "Tomczak", "M", 428, None, "harrow_falls", "station", "harrow_falls", "bartender", "Tomczak's Tavern: the station's most famous fish fry", ["tomczak"], "widowed", "Irene Tomczak", 2,
      faith="catholic", traits=["P.humour:high"], reputation="beloved", fame=0.35, roles=["regular", "public_character"]),
    P("dot_mbeki", "Dorothea", "Mbeki", "F", 392, None, "victory_bay", "station", "victory_bay", "retired", "the oldest person aboard (108)", ["mbeki"], "widowed", "twice", 6, faith="freedom_baptist",
      traits=["P.humour:very_high"], reputation="beloved", fame=0.45, notes=["remembers the Long Calm; Evangeline Mbeki-Hart is her great-niece"]),
    P("horace_blythe", "Horace", "Blythe", "M", 436, None, "tern_harbor", "station", "tern_harbor", "retired", "'Captain' Blythe, who claims he has been to the Port", ["blythe"], "divorced", "long ago", 1,
      faith="none", traits=["P.openness:very_high", "P.neuroticism:high"], reputation="contested", fame=0.3, roles=["town_character"]),
    P("millie_grabowski", "Mildred", "Grabowski", "F", 437, None, "fenwick", "station", "fenwick", "retired", "euchre champion of the station (nine times)", ["grabowski"], "widowed", "Stan Grabowski", 3,
      faith="catholic", traits=["P.agreeableness:low", "P.humour:high"], reputation="beloved", fame=0.25, roles=["town_character"]),
    P("ezra_yoder", "Ezra", "Yoder", "M", 450, None, "tamarack", "station", "tamarack", "farmer", "cheesemaker (Tamarack Blue)", ["yoder"], "married", "Leah Yoder", 7, faith="plain", fame=0.15),
    P("agnes_tillotson", "Agnes", "Tillotson", "F", 440, None, "haven_point", "station", "haven_point", "clerk", "keeper of the Haven Light", ["tillotson"], "never_married", None, 0, childless="chose_not",
      faith="lakes_union", reputation="respected", fame=0.15),
    P("ifeoma_okafor", "Ifeoma", "Okafor", "F", 478, None, "port_carrow", "station", "port_carrow", "shop_clerk", "one of the Okafor twins (spinball, Mariners)", ["okafor"], "never_married", None, 0, childless="chose_not",
      faith="catholic", reputation="beloved", fame=0.4, notes=["Tamsin Okafor-Reyes's line"]),
    P("chidi_okafor", "Chidi", "Okafor", "M", 478, None, "port_carrow", "station", "port_carrow", "dock_worker", "one of the Okafor twins (spinball, Mariners)", ["okafor"], "never_married", None, 0, childless="chose_not",
      faith="catholic", reputation="beloved", fame=0.4),
]

# who is kin to whom among the people above (for the family tree and affinity priors)
KIN = [
    ("della_brenneman_szabo", "augusta_brenneman", "descendant_of"), ("hiram_okonkwo_brenneman", "augusta_brenneman", "grandchild_of"),
    ("lionel_vance_okafor", "theodora_lindqvist_vance", "descendant_of"), ("octavia_fairweather", "cordelia_fairweather", "cousin"),
    ("pilar_ybarra_solano", "ignacio_ybarra", "child_of"), ("ines_ybarra_moreno", "ignacio_ybarra", "descendant_of"),
    ("ada_carrow", "joseph_carrow", "spouse"), ("chinedu_okafor", "lucia_reyes", "spouse"), ("tamsin_okafor_reyes", "chinedu_okafor", "child_of"),
    ("tamsin_okafor_reyes", "lucia_reyes", "child_of"), ("tomas_reyes", "lucia_reyes", "cousin"), ("raymundo_castellanos", "gwendolyn_pike", "spouse"),
    ("gwendolyn_pike_younger", "raymundo_castellanos", "descendant_of"), ("declan_moriarty", "finnegan_moriarty", "descendant_of"),
    ("siobhan_moriarty", "declan_moriarty", "grandchild_of"), ("rosa_pham_moriarty", "declan_moriarty", "grandchild_of"),
    ("rosalind_achterberg_nunez", "wendell_achterberg", "descendant_of"), ("margaret_achterberg_voss", "rosalind_achterberg_nunez", "aunt_of"),
    ("linnet_okoye_stroud", "juniper_stroud", "grandchild_of"), ("evangeline_mbeki_hart", "dot_mbeki", "great_niece_of"),
    ("clarence_kowalczyk_booker", "minnie_kowalczyk", "descendant_of"), ("ifeoma_okafor", "tamsin_okafor_reyes", "descendant_of"),
    ("chidi_okafor", "ifeoma_okafor", "twin"), ("luis_arrieta_wu", "consuelo_arrieta", "nephew_of"), ("itzel_solano_garza", "rosario_solano", "descendant_of"),
    ("anjali_raghunathan_cole", "priya_raghunathan", "collateral_descendant_of"), ("teodoro_nowicki_ramos", "casimir_nowicki", "collateral_descendant_of"),
    ("vinnie_decarlo", "salvatore_decarlo", "descendant_of"), ("amos_yoder_stoltz", "jonas_yoder", "descendant_of"), ("ezra_yoder", "jonas_yoder", "descendant_of"),
    ("fergus_dunmore", "maeve_dunmore_elder", "descendant_of"), ("lamar_haskins", "eli_haskins", "descendant_of"), ("harold_loomis_petrie", "abigail_loomis", "descendant_of"),
    ("ruth_ann_pruett_doyle", "hollis_pruett", "collateral_descendant_of"), ("caspian_holloway", "beatriz_holloway_anand", "nephew_of"),
    ("imogen_sato_ferris", "caspian_holloway", "friend"), ("tobias_wainwright_okafor", "tamsin_okafor_reyes", "descendant_of"),
]
