#!/usr/bin/env python3
"""Pixel art for the NYNEX Communicator's "The System" (godot_project/ui/pda/), in the LCD's four greys:
    K black   D dark grey   L light grey   W white   . clear
  system_logo.png      16 x 16  the System button: a cassette tape
  system_logo_32.png   32 x 32  the same, for the About page and the System menu's banner
  icon_ai.png          32 x 32  the NPC AI app: a speech balloon with a spark
  icon_summon.png      32 x 32  the Summon Aerostat app: an aerostat over its landing marks
    python3 tools/pda_art.py
"""
import os

from PIL import Image

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "godot_project", "ui", "pda")
PAL = {"K": (0, 0, 0, 255), "D": (85, 85, 85, 255), "L": (170, 170, 170, 255), "W": (255, 255, 255, 255),
       ".": (0, 0, 0, 0)}

# a compact cassette: the label, the window with its two reels and the tape between, the tapered
# head opening along the bottom with its two guide holes
LOGO_16 = """
................
................
KKKKKKKKKKKKKKKK
KWWWWWWWWWWWWWWK
KWKKKKKKKKKKKKWK
KWKWWWWWWWWWWKWK
KWKWKKWWWWKKWKWK
KWKWKKLLLLKKWKWK
KWKWWWWWWWWWWKWK
KWKKKKKKKKKKKKWK
KWWWWWWWWWWWWWWK
KWWWKKKKKKKKWWWK
KWWKWKWWWWKWKWWK
KKKKKKKKKKKKKKKK
................
................
"""

LOGO_32 = """
................................
................................
................................
................................
..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..
.KWWWWWWWWWWWWWWWWWWWWWWWWWWWWK.
.KWKWWWWWWWWWWWWWWWWWWWWWWWWKWK.
.KWWWKKKKKKKKKKKKKKKKKKKKKKWWWK.
.KWWKWWWWWWWWWWWWWWWWWWWWWWKWWK.
.KWWKWLLLLLLLLLLLLLLLLLLLLWKWWK.
.KWWKWWWWWWWWWWWWWWWWWWWWWWKWWK.
.KWWKWWKKKKKKKKKKKKKKKKKKWWKWWK.
.KWWKWKWWWWWWWWWWWWWWWWWWKWKWWK.
.KWWKWKWKKWWLLLLLLLLWWKKWKWKWWK.
.KWWKWKKWWKWLDDDDDDLWKWWKKWKWWK.
.KWWKWKKWWKLLDDDDDDLLKWWKKWKWWK.
.KWWKWKWKKWWLLLLLLLLWWKKWKWKWWK.
.KWWKWKWWWWWWWWWWWWWWWWWWKWKWWK.
.KWWKWWKKKKKKKKKKKKKKKKKKWWKWWK.
.KWWKWWWWWWWWWWWWWWWWWWWWWWKWWK.
.KWWKWLLLLLLLLLLLLLLLLLLLLWKWWK.
.KWWWKKKKKKKKKKKKKKKKKKKKKKWWWK.
.KWWWWWWWKKKKKKKKKKKKKKKWWWWWWK.
.KWWWWWWKWWWWWWWWWWWWWWWKWWWWWK.
.KWKWWWKWWKKWWWWWWWWKKWWWKWWKWK.
.KWWWWKWWWKKWWWWWWWWKKWWWWKWWWK.
..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..
................................
................................
................................
................................
................................
"""

ICON_AI = """
................................
................................
...KKKKKKKKKKKKKKKKKKKKKKKK.....
..KWWWWWWWWWWWWWWWWWWWWWWWWK....
.KWWWWWWWWWWWWWWWWWWWWWWWWWWK...
.KWWWWWWWWWWWWWKKWWWWWWWWWWWK...
.KWWWWWWWWWWWWKWWKWWWWWWWWWWKD..
.KWWWKKWWWWWWKWWKWWWWWWWWWWWKD..
.KWWKWWKWWWWKWWKKKKWWWWWWWWWKD..
.KWWKWWKWWWKWWWWWWKWWWWWWWWWKD..
.KWWWKKWWWWKKKKWWKWWWWKKWWWWKD..
.KWWWWWWWWWWWWKWKWWWWKWWKWWWKD..
.KWWWWWWWWWWWWKKWWWWWKWWKWWWKD..
.KWWWWWWWWWWWWKWWWWWWWKKWWWWKD..
.KWWWWWWWWWWWWWWWWWWWWWWWWWWKD..
..KWWWWWWWWWWWWWWWWWWWWWWWWKDD..
...KKKKKWWWKKKKKKKKKKKKKKKKDD...
.......KWWKDDDDDDDDDDDDDDDD.....
......KWWKD.....................
.....KWWKD......................
....KKKKD.......................
....DDDD........................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
"""

# an aerostat: the balloon with its seam, the rigging, the cabin with its windows and side fans,
# and the landing marks under it
ICON_SUMMON = """
................................
................................
..........KKKKKKKKKKKK..........
........KKWWWWWWWWWWWWKK........
......KKWWWWWWWWWWWWLLLLKK......
.....KKWWWWWWWWWWWWWWWLLLKK.....
.....KWWWWWWWWWWWWWWWWWLLLK.....
....KKWWWWWWWWWWWWWWWWWWLLKK....
....KDDDDDDDDDDDDDDDDDDDDDDK....
....KWWWWWWWWWWWWWWWWWWWLLLK....
....KKWWWWWWWWWWWWWWWWWWLLKK....
.....KWWWWWWWWWWWWWWWWWLLLK.....
.....KKWWWWWWWWWWWWWWWLLLKK.....
......KKWWWWWWWWWWWWLLLLKK......
........KKWWWWWWWWLLLLKK........
..........KKKKKKKKKKKK..........
.........K............K.........
.........K............K.........
..........K..........K..........
..........K..........K..........
.........KKKKKKKKKKKKKK.........
.........KWWWWWWWWWWWWK.........
.........KWDDWDDWDDWDDK.........
......K..KWDDWDDWDDWDDK..K......
.....KKKKKWWWWWWWWWWWWKKKKK.....
......K..KLLLLLLLLLLLLK..K......
.........KWWWWWWWWWWWWK.........
.........KKKKKKKKKKKKKK.........
................................
................................
.......KK.KK.KK.KK.KK.KK........
................................
"""


def draw(art, path):
    rows = [r for r in art.strip("\n").split("\n")]
    w = max(len(r) for r in rows)
    im = Image.new("RGBA", (w, len(rows)), PAL["."])
    for y, r in enumerate(rows):
        for x, ch in enumerate(r):
            im.putpixel((x, y), PAL[ch])
    im.save(os.path.join(OUT, path))
    return im


if __name__ == "__main__":
    draw(LOGO_16, "system_logo.png")
    draw(LOGO_32, "system_logo_32.png")
    draw(ICON_AI, "icon_ai.png")
    draw(ICON_SUMMON, "icon_summon.png")
    print("pda art ->", OUT)
