#!/usr/bin/env python3
"""Pixel art for the NYNEX Communicator's "The System" (godot_project/ui/pda/), in the LCD's four greys:
    K black   D dark grey   L light grey   W white   . clear
  system_logo.png      16 x 16  the System button: a fist clutching a lightning bolt
  system_logo_32.png   32 x 32  the same, for the About page and the System menu's banner
  icon_ai.png          32 x 32  the NPC AI app: a speech balloon with a spark
    python3 tools/pda_art.py
"""
import os

from PIL import Image

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "godot_project", "ui", "pda")
PAL = {"K": (0, 0, 0, 255), "D": (85, 85, 85, 255), "L": (170, 170, 170, 255), "W": (255, 255, 255, 255),
       ".": (0, 0, 0, 0)}

# the bolt comes down through the fist from the upper right and leaves it low on the left; four
# fingers wrap it, the thumb crosses over the top two
LOGO_16 = """
........KKKKK...
.......KWWWK....
......KWWWKKKK..
.....KKKKWWWK...
........KWWK....
.KKKKKKKKWK.....
KWWWWWWWKKKKKK..
KWLWWWWWKWWWWLK.
KKKKKKKKKKKKKLK.
KWWWWWWWWWWWLK..
KWLWWWWWWWWWLK..
KKKKKKKKKKKKLK..
KWWWWWWWWWLLK...
.KKKKKKKKKKK....
...KWWK.........
..KWK...........
"""

LOGO_32 = """
.................KKKKKKKKK......
................KWWWWWWWK.......
...............KWWWWWWWK........
..............KWWWWWWWK.........
.............KWWWWWWWKKKKKKK....
............KWWWWWWWWWWWWWK.....
...........KKKKKKKWWWWWWWK......
.................KWWWWWWK.......
................KWWWWWWK........
..KKKKKKKKKKKKKKKWWWWWK.........
.KWWWWWWWWWWWWWWKWWWWK..........
KWWLLWWWWWWWWWWWKWWWK.KKKKK.....
KWLLWWWWWWWWWWWWWKKKKKWWWWWKK...
KWLWWWWWWWWWWWWWWKWWWWWWWWWLLK..
KKKKKKKKKKKKKKKKKKWWWWWWWWWWLK..
KWWWWWWWWWWWWWWWWWKKKKKKKKKWLK..
KWLLWWWWWWWWWWWWWWWWWWWWWWWLLK..
KWLWWWWWWWWWWWWWWWWWWWWWWWLLK...
KKKKKKKKKKKKKKKKKKKKKKKKKKKLK...
KWWWWWWWWWWWWWWWWWWWWWWWWWLLK...
KWLLWWWWWWWWWWWWWWWWWWWWWLLK....
KWLWWWWWWWWWWWWWWWWWWWWWLLLK....
KKKKKKKKKKKKKKKKKKKKKKKKKKK.....
KWWWWWWWWWWWWWWWWWWWWWWLLK......
.KWLWWWWWWWWWWWWWWWWWLLLK.......
..KKKKKKKKKKKKKKKKKKKKKK........
.......KWWWWWK..................
......KWWWWK....................
.....KWWWK......................
....KWWK........................
...KWK..........................
...KK...........................
"""

ICON_AI = """
................................
................................
...KKKKKKKKKKKKKKKKKKKKKKKK.....
..KWWWWWWWWWWWWWWWWWWWWWWWWK....
.KWWWWWWWWWWWWWWWWWWWWWWWWWWK...
.KWWWWWWWWWWWWWKKWWWWWWWWWWWK...
.KWWWWWWWWWWWWKWWKWWWWWWWWWWKD..
.KWWWKKWWWWWWKWWKWWWWWWWWWWWKD..
.KWWKWWKWWWWKWWKKKKWWWWWWWWWKD..
.KWWKWWKWWWKWWWWWWKWWWWWWWWWKD..
.KWWWKKWWWWKKKKWWKWWWWKKWWWWKD..
.KWWWWWWWWWWWWKWKWWWWKWWKWWWKD..
.KWWWWWWWWWWWWKKWWWWWKWWKWWWKD..
.KWWWWWWWWWWWWKWWWWWWWKKWWWWKD..
.KWWWWWWWWWWWWWWWWWWWWWWWWWWKD..
..KWWWWWWWWWWWWWWWWWWWWWWWWKDD..
...KKKKKWWWKKKKKKKKKKKKKKKKDD...
.......KWWKDDDDDDDDDDDDDDDD.....
......KWWKD.....................
.....KWWKD......................
....KKKKD.......................
....DDDD........................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
"""


def draw(art, path):
    rows = [r for r in art.strip("\n").split("\n")]
    w = max(len(r) for r in rows)
    im = Image.new("RGBA", (w, len(rows)), PAL["."])
    for y, r in enumerate(rows):
        for x, ch in enumerate(r):
            im.putpixel((x, y), PAL[ch])
    im.save(os.path.join(OUT, path))
    return im


if __name__ == "__main__":
    draw(LOGO_16, "system_logo.png")
    draw(LOGO_32, "system_logo_32.png")
    draw(ICON_AI, "icon_ai.png")
    print("pda art ->", OUT)
